	' Keystone Kapers art -- GENERATED by assets/genart.py. Do not edit; regenerate.
	'
	' EVERY SPRITE IS 16x16: sprite size and magnification are GLOBAL on the
	' TMS9918, so small objects are drawn small INSIDE a 16x16 box rather than
	' being small sprites.
	'
	' EVERY 8-PX OBJECT SITS IN ROWS 8-15 OF ITS BOX, ducked Kelly included, so
	' one rule places them all: bottom edge = y + 16, and a thing resting on the
	' floor is at y = FLOORY - 16.
	'
	' Sprite bytes are QUADRANT-ORDERED: 16 rows of the left half, then 16 of
	' the right. Every block is an EVEN number of bytes -- an odd DATA BYTE run
	' silently misaligns every word table after it (CLAUDE.md 3A).

spr_kelly:	' Kelly RIGHT then LEFT: hat, face, tunic, leg1, leg2, duck-hat, duck-face. Patterns 0..52
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$0F,$1F,$3F
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$C0,$E0,$F0
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$0F,$0F,$0F
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$C0,$C0,$C0
	DATA BYTE $1F,$3B,$33,$33,$33,$33,$03,$03
	DATA BYTE $07,$07,$00,$00,$00,$00,$00,$00
	DATA BYTE $E0,$70,$CC,$CC,$CC,$CC,$C0,$C0
	DATA BYTE $E0,$E0,$00,$00,$00,$00,$00,$00
	DATA BYTE $06,$06,$0E,$0E,$1E,$1C,$3C,$3C
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $60,$60,$70,$70,$78,$38,$3C,$3C
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $06,$06,$0E,$1C,$1C,$3C,$78,$78
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $C0,$C0,$E0,$70,$70,$78,$3C,$3C
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $1E,$3F,$00,$00,$3F,$3F,$18,$3C
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $78,$F0,$00,$00,$FC,$F0,$70,$38
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$35,$3F,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$B0,$F0,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$03,$07,$0F
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$F0,$F8,$FC
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$03,$03,$03
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$F0,$F0,$F0
	DATA BYTE $07,$0E,$33,$33,$33,$33,$03,$03
	DATA BYTE $07,$07,$00,$00,$00,$00,$00,$00
	DATA BYTE $F8,$DC,$CC,$CC,$CC,$CC,$C0,$C0
	DATA BYTE $E0,$E0,$00,$00,$00,$00,$00,$00
	DATA BYTE $06,$06,$0E,$0E,$1E,$1C,$3C,$3C
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $60,$60,$70,$70,$78,$38,$3C,$3C
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $03,$03,$07,$0E,$0E,$1E,$3C,$3C
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $60,$60,$70,$38,$38,$3C,$1E,$1E
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $1E,$0F,$00,$00,$3F,$0F,$0E,$1C
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $78,$FC,$00,$00,$FC,$FC,$18,$3C
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$0D,$0F,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$AC,$FC,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00

spr_harry:	' Harry RIGHT then LEFT: white, face, stripes, leg1, leg2. Patterns 56..92
	DATA BYTE $1F,$00,$0F,$00,$00,$00,$39,$00
	DATA BYTE $30,$00,$30,$00,$0F,$00,$0F,$00
	DATA BYTE $C0,$00,$80,$00,$00,$00,$DF,$00
	DATA BYTE $7C,$00,$18,$00,$C8,$00,$C0,$00
	DATA BYTE $0F,$0F,$1F,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $80,$80,$CE,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$3F,$00,$00,$00,$00,$00,$30
	DATA BYTE $00,$30,$00,$07,$00,$0F,$00,$0F
	DATA BYTE $00,$E0,$00,$00,$00,$00,$00,$FE
	DATA BYTE $00,$18,$00,$98,$00,$C0,$00,$C0
	DATA BYTE $0C,$0C,$1C,$1C,$3C,$38,$78,$78
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $C0,$C0,$E0,$E0,$F0,$70,$78,$78
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $0D,$0D,$1D,$38,$38,$78,$F0,$F0
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $80,$80,$C0,$E0,$E0,$F0,$78,$78
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $03,$00,$01,$00,$00,$00,$FB,$00
	DATA BYTE $3E,$00,$18,$00,$13,$00,$03,$00
	DATA BYTE $F8,$00,$F0,$00,$00,$00,$9C,$00
	DATA BYTE $0C,$00,$0C,$00,$F0,$00,$F0,$00
	DATA BYTE $01,$01,$73,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $F0,$F0,$F8,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$07,$00,$00,$00,$00,$00,$7F
	DATA BYTE $00,$18,$00,$19,$00,$03,$00,$03
	DATA BYTE $00,$FC,$00,$00,$00,$00,$00,$0C
	DATA BYTE $00,$0C,$00,$E0,$00,$F0,$00,$F0
	DATA BYTE $03,$03,$07,$07,$0F,$0E,$1E,$1E
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $30,$30,$38,$38,$3C,$1C,$1E,$1E
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $01,$01,$03,$07,$07,$0F,$1E,$1E
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $B0,$B0,$B8,$1C,$1C,$1E,$0F,$0F
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00

spr_cart:	' shopping cart -- jump it. Pattern 56
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $3F,$2A,$2A,$3F,$3F,$10,$38,$38
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $FC,$A4,$A4,$FC,$FC,$08,$1C,$1C

spr_ball:	' beach ball -- jump it LOW, duck it HIGH. Pattern 60
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $07,$1F,$3F,$7F,$7F,$3F,$1F,$07
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $E0,$F8,$FC,$FE,$FE,$FC,$F8,$E0

spr_radio:	' cathedral radio, stationary. Pattern 64
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $0C,$07,$1F,$3F,$3F,$3F,$3F,$3F
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $30,$E0,$F8,$FC,$FC,$FC,$FC,$FC

spr_plane:	' toy biplane -- DUCK. The only thing that kills. Patterns 68,72
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $19,$01,$0F,$3F,$7F,$3F,$0F,$01
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $98,$80,$F0,$FC,$F6,$FC,$F0,$80
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $19,$01,$0F,$3F,$6F,$3F,$0F,$01
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $98,$80,$F0,$FC,$FE,$FC,$F0,$80
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $0F,$01,$0F,$3F,$7F,$3F,$0F,$01
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $F0,$80,$F0,$FC,$F6,$FC,$F0,$80
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $0F,$01,$0F,$3F,$6F,$3F,$0F,$01
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $F0,$80,$F0,$FC,$FE,$FC,$F0,$80

	' ------------------------------------------------ store characters
	' Codes 96-115. Loaded as ONE contiguous run, so the order here is
	' the order of the codes -- a gap would shift every char after it.

store_pat:	' 61 chars, 8 bytes each
	DATA BYTE $FF,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
	DATA BYTE $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $FF,$7F,$1F,$C7,$F1,$FC,$FF,$3F
	DATA BYTE $00,$00,$00,$00,$FF,$7F,$1F,$C7
	DATA BYTE $01,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $80,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$FF,$FE,$F8,$E3
	DATA BYTE $FF,$FE,$F8,$E3,$8F,$3F,$FF,$FC
	DATA BYTE $FF,$7F,$1F,$C7,$F1,$FC,$FF,$3F
	DATA BYTE $00,$00,$00,$00,$FF,$7F,$1F,$C7
	DATA BYTE $01,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $80,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$FF,$FE,$F8,$E3
	DATA BYTE $FF,$FE,$F8,$E3,$8F,$3F,$FF,$FC
	DATA BYTE $FF,$7F,$1F,$C7,$F1,$FC,$FF,$3F
	DATA BYTE $00,$00,$00,$00,$FF,$7F,$1F,$C7
	DATA BYTE $01,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $0F,$0F,$18,$18,$18,$18,$18,$18
	DATA BYTE $FF,$FF,$00,$00,$00,$00,$00,$00
	DATA BYTE $F0,$F0,$1C,$07,$01,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$C0,$70,$1C,$07
	DATA BYTE $19,$0C,$0F,$0F,$0F,$03,$00,$00
	DATA BYTE $C0,$70,$1C,$07,$01,$00,$00,$00
	DATA BYTE $0F,$03,$00,$00,$00,$00,$00,$00
	DATA BYTE $F1,$FC,$FF,$3F,$0F,$03,$00,$00
	DATA BYTE $C0,$70,$0C,$0C,$0C,$0C,$0C,$0C
	DATA BYTE $00,$00,$00,$00,$03,$0E,$38,$E0
	DATA BYTE $0F,$0F,$38,$E0,$80,$00,$00,$00
	DATA BYTE $FF,$FF,$00,$00,$00,$00,$00,$00
	DATA BYTE $F0,$F0,$18,$18,$18,$18,$18,$18
	DATA BYTE $03,$0E,$38,$E0,$80,$00,$00,$00
	DATA BYTE $98,$30,$F0,$F0,$F0,$C0,$00,$00
	DATA BYTE $8F,$3F,$FF,$FC,$F0,$C0,$00,$00
	DATA BYTE $F0,$C0,$00,$00,$00,$00,$00,$00
	DATA BYTE $03,$0E,$30,$30,$30,$30,$30,$30
	DATA BYTE $00,$00,$00,$00,$C0,$70,$1C,$07
	DATA BYTE $19,$0C,$0F,$0F,$0F,$03,$00,$00
	DATA BYTE $C0,$70,$1C,$07,$01,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$03,$0E,$38,$E0
	DATA BYTE $03,$0E,$38,$E0,$80,$00,$00,$00
	DATA BYTE $98,$30,$F0,$F0,$F0,$C0,$00,$00
	DATA BYTE $0F,$0F,$18,$18,$18,$18,$18,$18
	DATA BYTE $FF,$FF,$00,$00,$00,$00,$00,$00
	DATA BYTE $F0,$F0,$1C,$07,$01,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$C0,$70,$1C,$07
	DATA BYTE $00,$00,$00,$00,$C0,$70,$1C,$07
	DATA BYTE $19,$0C,$0F,$0F,$0F,$03,$00,$00
	DATA BYTE $C0,$70,$1C,$07,$01,$00,$00,$00
	DATA BYTE $33,$33,$FB,$FF,$FF,$FF,$FF,$FF
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $3C,$7E,$5A,$3C,$7E,$66,$66,$42
	DATA BYTE $FF,$81,$BD,$A5,$A5,$BD,$81,$FF
	DATA BYTE $3C,$66,$FF,$FF,$DB,$FF,$7E,$3C
	DATA BYTE $18,$7E,$FF,$FF,$E7,$FF,$FF,$00
	DATA BYTE $FF,$FF,$00,$00,$00,$00,$00,$00
	DATA BYTE $C3,$C3,$C3,$C3,$C3,$C3,$C3,$C3
	DATA BYTE $DF,$DF,$00,$FB,$FB,$00,$DF,$DF
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00

store_col:	' EIGHT colour bytes per char, not one
	DATA BYTE $BA,$BA,$BA,$BA,$BA,$B2,$B2,$B2
	DATA BYTE $44,$44,$44,$44,$44,$44,$44,$44
	DATA BYTE $EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE
	DATA BYTE $FE,$FE,$FE,$FE,$FE,$FE,$FE,$FE
	DATA BYTE $F7,$F7,$F7,$F7,$F7,$F7,$F7,$F7
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $1B,$1A,$1A,$1A,$1A,$12,$12,$12
	DATA BYTE $1B,$1A,$1A,$1A,$1A,$12,$12,$12
	DATA BYTE $1B,$1A,$1A,$1A,$1A,$12,$12,$12
	DATA BYTE $1B,$1A,$1A,$1A,$1A,$12,$12,$12
	DATA BYTE $1B,$1A,$1A,$1A,$1A,$12,$12,$12
	DATA BYTE $1B,$1A,$1A,$1A,$1A,$12,$12,$12
	DATA BYTE $1F,$1F,$1E,$1E,$1E,$1E,$1E,$1E
	DATA BYTE $1F,$1F,$1E,$1E,$1E,$1E,$1E,$1E
	DATA BYTE $1F,$1F,$1E,$1E,$1E,$1E,$1E,$1E
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $12,$12,$12,$12,$12,$12,$12,$12
	DATA BYTE $1B,$1A,$1A,$1A,$1A,$12,$12,$12
	DATA BYTE $1B,$1A,$1A,$1A,$1A,$12,$12,$12
	DATA BYTE $1B,$1A,$1A,$1A,$1A,$12,$12,$12
	DATA BYTE $1B,$1A,$1A,$1A,$1A,$12,$12,$12
	DATA BYTE $1B,$1A,$1A,$1A,$1A,$12,$12,$12
	DATA BYTE $1B,$1A,$1A,$1A,$1A,$12,$12,$12
	DATA BYTE $1E,$1E,$1E,$1E,$1E,$1E,$1E,$1E
	DATA BYTE $1E,$1E,$1E,$1E,$1E,$1E,$1E,$1E
	DATA BYTE $1E,$1E,$1E,$1E,$1E,$1E,$1E,$1E
	DATA BYTE $1E,$1E,$1E,$1E,$1E,$1E,$1E,$1E
	DATA BYTE $1F,$1F,$1E,$1E,$1E,$1E,$1E,$1E
	DATA BYTE $1F,$1F,$1E,$1E,$1E,$1E,$1E,$1E
	DATA BYTE $1F,$1F,$1E,$1E,$1E,$1E,$1E,$1E
	DATA BYTE $87,$87,$87,$87,$87,$87,$87,$87
	DATA BYTE $F2,$F2,$F2,$F2,$F2,$F2,$F2,$F2
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $B2,$B2,$B2,$B2,$B2,$B2,$B2,$B2
	DATA BYTE $62,$62,$62,$62,$62,$62,$62,$62
	DATA BYTE $FE,$FE,$FE,$FE,$FE,$FE,$FE,$FE
	DATA BYTE $17,$17,$17,$17,$17,$17,$17,$17
	DATA BYTE $EC,$EC,$EC,$EC,$EC,$EC,$EC,$EC
	DATA BYTE $11,$11,$11,$11,$11,$11,$11,$11

esc_ph0:	' chars 101-115, phase 0 -- DEFINE CHAR 101,15,esc_ph0
	DATA BYTE $FF,$7F,$1F,$C7,$F1,$FC,$FF,$3F
	DATA BYTE $00,$00,$00,$00,$FF,$7F,$1F,$C7
	DATA BYTE $01,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $80,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$FF,$FE,$F8,$E3
	DATA BYTE $FF,$FE,$F8,$E3,$8F,$3F,$FF,$FC
	DATA BYTE $FF,$7F,$1F,$C7,$F1,$FC,$FF,$3F
	DATA BYTE $00,$00,$00,$00,$FF,$7F,$1F,$C7
	DATA BYTE $01,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $80,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$FF,$FE,$F8,$E3
	DATA BYTE $FF,$FE,$F8,$E3,$8F,$3F,$FF,$FC
	DATA BYTE $FF,$7F,$1F,$C7,$F1,$FC,$FF,$3F
	DATA BYTE $00,$00,$00,$00,$FF,$7F,$1F,$C7
	DATA BYTE $01,$00,$00,$00,$00,$00,$00,$00

esc_ph1:	' chars 101-115, phase 1 -- DEFINE CHAR 101,15,esc_ph1
	DATA BYTE $FC,$7C,$1C,$C7,$F1,$FC,$FF,$3F
	DATA BYTE $00,$00,$00,$FC,$FC,$7C,$1C,$C7
	DATA BYTE $01,$00,$00,$00,$00,$00,$00,$FC
	DATA BYTE $80,$00,$00,$00,$00,$00,$00,$3F
	DATA BYTE $00,$00,$00,$3F,$3F,$3E,$38,$E3
	DATA BYTE $3F,$3E,$38,$E3,$8F,$3F,$FF,$FC
	DATA BYTE $FC,$7C,$1C,$C7,$F1,$FC,$FF,$3F
	DATA BYTE $00,$00,$00,$FC,$FC,$7C,$1C,$C7
	DATA BYTE $01,$00,$00,$00,$00,$00,$00,$FC
	DATA BYTE $80,$00,$00,$00,$00,$00,$00,$3F
	DATA BYTE $00,$00,$00,$3F,$3F,$3E,$38,$E3
	DATA BYTE $3F,$3E,$38,$E3,$8F,$3F,$FF,$FC
	DATA BYTE $FC,$7C,$1C,$C7,$F1,$FC,$FF,$3F
	DATA BYTE $00,$00,$00,$FC,$FC,$7C,$1C,$C7
	DATA BYTE $01,$00,$00,$00,$00,$00,$00,$FC

esc_ph2:	' chars 101-115, phase 2 -- DEFINE CHAR 101,15,esc_ph2
	DATA BYTE $F0,$70,$1F,$C7,$F1,$FC,$FF,$3F
	DATA BYTE $00,$00,$F0,$F0,$F0,$70,$1F,$C7
	DATA BYTE $01,$00,$00,$00,$00,$00,$F0,$F0
	DATA BYTE $80,$00,$00,$00,$00,$00,$0F,$0F
	DATA BYTE $00,$00,$0F,$0F,$0F,$0E,$F8,$E3
	DATA BYTE $0F,$0E,$F8,$E3,$8F,$3F,$FF,$FC
	DATA BYTE $F0,$70,$1F,$C7,$F1,$FC,$FF,$3F
	DATA BYTE $00,$00,$F0,$F0,$F0,$70,$1F,$C7
	DATA BYTE $01,$00,$00,$00,$00,$00,$F0,$F0
	DATA BYTE $80,$00,$00,$00,$00,$00,$0F,$0F
	DATA BYTE $00,$00,$0F,$0F,$0F,$0E,$F8,$E3
	DATA BYTE $0F,$0E,$F8,$E3,$8F,$3F,$FF,$FC
	DATA BYTE $F0,$70,$1F,$C7,$F1,$FC,$FF,$3F
	DATA BYTE $00,$00,$F0,$F0,$F0,$70,$1F,$C7
	DATA BYTE $01,$00,$00,$00,$00,$00,$F0,$F0

esc_ph3:	' chars 101-115, phase 3 -- DEFINE CHAR 101,15,esc_ph3
	DATA BYTE $C0,$7F,$1F,$C7,$F1,$FC,$FF,$3F
	DATA BYTE $00,$C0,$C0,$C0,$C0,$7F,$1F,$C7
	DATA BYTE $01,$00,$00,$00,$00,$C0,$C0,$C0
	DATA BYTE $80,$00,$00,$00,$00,$03,$03,$03
	DATA BYTE $00,$03,$03,$03,$03,$FE,$F8,$E3
	DATA BYTE $03,$FE,$F8,$E3,$8F,$3F,$FF,$FC
	DATA BYTE $C0,$7F,$1F,$C7,$F1,$FC,$FF,$3F
	DATA BYTE $00,$C0,$C0,$C0,$C0,$7F,$1F,$C7
	DATA BYTE $01,$00,$00,$00,$00,$C0,$C0,$C0
	DATA BYTE $80,$00,$00,$00,$00,$03,$03,$03
	DATA BYTE $00,$03,$03,$03,$03,$FE,$F8,$E3
	DATA BYTE $03,$FE,$F8,$E3,$8F,$3F,$FF,$FC
	DATA BYTE $C0,$7F,$1F,$C7,$F1,$FC,$FF,$3F
	DATA BYTE $00,$C0,$C0,$C0,$C0,$7F,$1F,$C7
	DATA BYTE $01,$00,$00,$00,$00,$C0,$C0,$C0

	' -------------------------------------------------- scanner canvas
	' Chars 160-207: 16 cols x 3 rows over screen rows 21-23. Blank to start;
	' dots are plotted by VPOKEing the PATTERN table (rows 21-23 sit in the
	' third screen third, so every scanner pattern is at base 4096).

	' --------------------------------------------------- font colours
	' Chars 32-90, EIGHT bytes each. Without this the font keeps whatever
	' CVBasic left in the colour table, which on a green store made the HUD
	' unreadable.

scan_col3:	' one 8-byte block per canvas row: 4 px of BLACK margin, then furniture grey / Kelly black / Harry white / floor line yellow per 4 px level, on dark green
	DATA BYTE $11,$11,$11,$11,$EC,$1C,$FC,$BC
	DATA BYTE $EC,$1C,$FC,$BC,$EC,$1C,$FC,$BC
	DATA BYTE $EC,$1C,$FC,$BC,$11,$11,$11,$11

	' code map, for the source to reference:
	'   96  SLAB
	'   97  SHELFT
	'   98  COUNTR
	'   99  SHAFT
	'   100 ECAR
	'   101 ESCW5
	'   102 ESCW6
	'   103 ESCW7
	'   104 ESCE5
	'   105 ESCE6
	'   106 ESCE7
	'   107 ESCWB5
	'   108 ESCWB6
	'   109 ESCWB7
	'   110 ESCEB5
	'   111 ESCEB6
	'   112 ESCEB7
	'   113 ESCWD5
	'   114 ESCWD6
	'   115 ESCWD7
	'   116 ESCW0
	'   117 ESCW1
	'   118 ESCW2
	'   119 ESCW3
	'   120 ESCW4
	'   121 ESCW8
	'   122 ESCW9
	'   123 ESCW10
	'   124 ESCW11
	'   125 ESCE0
	'   126 ESCE1
	'   127 ESCE2
	'   128 ESCE3
	'   129 ESCE4
	'   130 ESCE8
	'   131 ESCE9
	'   132 ESCE10
	'   133 ESCE11
	'   134 ESCWB3
	'   135 ESCWB4
	'   136 ESCWB8
	'   137 ESCEB0
	'   138 ESCEB4
	'   139 ESCEB8
	'   140 ESCWR0
	'   141 ESCWR1
	'   142 ESCWR2
	'   143 ESCWR3
	'   144 ESCWD3
	'   145 ESCWD4
	'   146 ESCWD8
	'   147 PARAP
	'   148 WALL
	'   149 KOPIC
	'   150 EXITC
	'   151 BAG
	'   152 CASE
	'   153 ROOFS
	'   154 EDHALF
	'   155 ENDWALL
	'   156 SCANBK
