	' Keystone Kapers font -- GENERATED by assets/genfont.py. Do not edit; regenerate.
	'
	' Characters 32-90 (59 of them), 8 bytes each = 472 bytes. Williams' cabinet face:
	' heavy, squared, flat terminals, no serifs -- drawn 5x7 inside the 8x8 cell so a
	' blank column at the right and a blank row at the bottom keep it legible.
	'
	' Loaded with DEFINE CHAR 32,59,font_bits. The run must be CONTIGUOUS, so slots
	' with no glyph emit blanks rather than being skipped -- a gap would shift every
	' letter after it.

font_bits:
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00	' space
	DATA BYTE $20,$20,$20,$20,$20,$00,$20,$00	' !
	DATA BYTE $00,$00,$38,$04,$3C,$44,$3C,$00	' "
	DATA BYTE $04,$04,$3C,$44,$44,$44,$3C,$00	' #
	DATA BYTE $00,$00,$38,$44,$7C,$40,$38,$00	' $
	DATA BYTE $30,$10,$10,$10,$10,$10,$38,$00	' %
	DATA BYTE $60,$90,$A0,$40,$A8,$90,$68,$00	' &
	DATA BYTE $20,$20,$00,$00,$00,$00,$00,$00	' '
	DATA BYTE $00,$00,$78,$44,$78,$40,$40,$40	' (
	DATA BYTE $00,$00,$58,$64,$40,$40,$40,$00	' )
	DATA BYTE $00,$00,$88,$50,$20,$50,$88,$00	' *
	DATA BYTE $00,$00,$3C,$40,$38,$04,$78,$00	' +
	DATA BYTE $00,$00,$78,$44,$44,$44,$44,$00	' ,
	DATA BYTE $00,$00,$00,$F8,$00,$00,$00,$00	' -
	DATA BYTE $00,$00,$00,$00,$00,$60,$60,$00	' .
	DATA BYTE $08,$08,$10,$20,$40,$80,$80,$00	' /
	DATA BYTE $70,$88,$98,$A8,$C8,$88,$70,$00	' 0
	DATA BYTE $20,$60,$20,$20,$20,$20,$70,$00	' 1
	DATA BYTE $70,$88,$08,$30,$40,$80,$F8,$00	' 2
	DATA BYTE $F0,$08,$08,$70,$08,$08,$F0,$00	' 3
	DATA BYTE $10,$30,$50,$90,$F8,$10,$10,$00	' 4
	DATA BYTE $F8,$80,$F0,$08,$08,$88,$70,$00	' 5
	DATA BYTE $70,$80,$80,$F0,$88,$88,$70,$00	' 6
	DATA BYTE $F8,$08,$10,$20,$40,$40,$40,$00	' 7
	DATA BYTE $70,$88,$88,$70,$88,$88,$70,$00	' 8
	DATA BYTE $70,$88,$88,$78,$08,$08,$70,$00	' 9
	DATA BYTE $00,$60,$60,$00,$60,$60,$00,$00	' :
	DATA BYTE $00,$60,$60,$00,$60,$60,$40,$00	' ;
	DATA BYTE $10,$20,$40,$80,$40,$20,$10,$00	' <
	DATA BYTE $00,$00,$F8,$00,$F8,$00,$00,$00	' =
	DATA BYTE $40,$20,$10,$08,$10,$20,$40,$00	' >
	DATA BYTE $70,$88,$08,$30,$20,$00,$20,$00	' ?
	DATA BYTE $70,$88,$B8,$A8,$B8,$80,$70,$00	' @
	DATA BYTE $70,$88,$88,$88,$F8,$88,$88,$00	' A
	DATA BYTE $F0,$88,$88,$F0,$88,$88,$F0,$00	' B
	DATA BYTE $70,$88,$80,$80,$80,$88,$70,$00	' C
	DATA BYTE $E0,$90,$88,$88,$88,$90,$E0,$00	' D
	DATA BYTE $F8,$80,$80,$F0,$80,$80,$F8,$00	' E
	DATA BYTE $F8,$80,$80,$F0,$80,$80,$80,$00	' F
	DATA BYTE $70,$88,$80,$B8,$88,$88,$78,$00	' G
	DATA BYTE $88,$88,$88,$F8,$88,$88,$88,$00	' H
	DATA BYTE $70,$20,$20,$20,$20,$20,$70,$00	' I
	DATA BYTE $38,$10,$10,$10,$90,$90,$60,$00	' J
	DATA BYTE $88,$90,$A0,$C0,$A0,$90,$88,$00	' K
	DATA BYTE $80,$80,$80,$80,$80,$80,$F8,$00	' L
	DATA BYTE $88,$D8,$A8,$A8,$88,$88,$88,$00	' M
	DATA BYTE $88,$C8,$A8,$A8,$98,$88,$88,$00	' N
	DATA BYTE $70,$88,$88,$88,$88,$88,$70,$00	' O
	DATA BYTE $F0,$88,$88,$F0,$80,$80,$80,$00	' P
	DATA BYTE $70,$88,$88,$88,$A8,$90,$68,$00	' Q
	DATA BYTE $F0,$88,$88,$F0,$A0,$90,$88,$00	' R
	DATA BYTE $78,$80,$80,$70,$08,$08,$F0,$00	' S
	DATA BYTE $F8,$20,$20,$20,$20,$20,$20,$00	' T
	DATA BYTE $88,$88,$88,$88,$88,$88,$70,$00	' U
	DATA BYTE $88,$88,$88,$88,$88,$50,$20,$00	' V
	DATA BYTE $88,$88,$88,$A8,$A8,$D8,$88,$00	' W
	DATA BYTE $88,$88,$50,$20,$50,$88,$88,$00	' X
	DATA BYTE $88,$88,$50,$20,$20,$20,$20,$00	' Y
	DATA BYTE $F8,$08,$10,$20,$40,$80,$F8,$00	' Z

	' THE COLOUR TABLE, 472 bytes of the same value ($B4 = light yellow ink on dark blue).
	'
	' Loaded with DEFINE COLOR 32,59,font_col, which is ONE synchronous call that
	' writes all three screen thirds (define_color always does the LDIRVM3 triple
	' copy). It replaced a VPOKE loop that wrote this one value 1,416 times paced by
	' 24 WAITs -- the largest scripted delay in the boot, and the reason the title
	' screen used to fill in visibly rather than appearing at once.
	'
	' EIGHT BYTES PER CHARACTER, not one. Supply fewer and DEFINE COLOR reads
	' whatever follows in ROM as colour data, with no error at build or run time.

#if NES
	' NES uses nes_fcol; omit this identical 472-byte TMS colour table.
#else
font_col:
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' space
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' !
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' "
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' #
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' $
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' %
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' &
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' '
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' (
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' )
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' *
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' +
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' ,
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' -
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' .
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' /
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' 0
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' 1
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' 2
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' 3
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' 4
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' 5
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' 6
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' 7
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' 8
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' 9
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' :
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' ;
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' <
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' =
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' >
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' ?
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' @
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' A
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' B
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' C
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' D
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' E
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' F
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' G
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' H
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' I
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' J
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' K
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' L
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' M
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' N
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' O
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' P
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' Q
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' R
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' S
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' T
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' U
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' V
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' W
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' X
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' Y
	DATA BYTE $B4,$B4,$B4,$B4,$B4,$B4,$B4,$B4	' Z
#endif
