	' ==================================================
	' THE END-OF-ROUND MESSAGE BOXES
	' Generated by assets/gentitle.py -- do not edit here.
	'
	' row, col, length, then `length` bytes; 255 ends -- the
	' same format as the title's display list, walked by the
	' same run_list, from do_catch and lose_kop.
	'
	' THESE STAY IN BANK 1. They are read MID-GAME, when a
	' round ends, so they must sit on the permanently mapped
	' page. The display list went to bank 2 (titledl.bas);
	' these following it would fail exactly when a life is
	' lost, and silently.
	' ==================================================

msg_away:
	DATA BYTE 10,10,13,32,32,32,32,32
	DATA BYTE 32,32,32,32,32,32,32,32
	DATA BYTE 11,10,13,32,72,69,32,71
	DATA BYTE 79,84,32,65,87,65,89,32
	DATA BYTE 12,10,13,32,32,32,32,32
	DATA BYTE 32,32,32,32,32,32,32,32
	DATA BYTE 255,255

msg_gothim:
	DATA BYTE 10,10,13,32,32,32,32,32
	DATA BYTE 32,32,32,32,32,32,32,32
	DATA BYTE 11,10,13,32,32,71,79,84
	DATA BYTE 32,72,73,77,33,32,32,32
	DATA BYTE 12,10,13,32,32,32,32,32
	DATA BYTE 32,32,32,32,32,32,32,32
	DATA BYTE 255,255

msg_over:
	DATA BYTE 8,10,13,32,32,32,32,32
	DATA BYTE 32,32,32,32,32,32,32,32
	DATA BYTE 9,10,13,32,32,71,65,77
	DATA BYTE 69,32,79,86,69,82,32,32
	DATA BYTE 255,255

msg_plane:
	DATA BYTE 10,10,13,32,32,32,32,32
	DATA BYTE 32,32,32,32,32,32,32,32
	DATA BYTE 11,10,13,32,84,72,69,32
	DATA BYTE 66,73,80,76,65,78,69,32
	DATA BYTE 12,10,13,32,32,32,32,32
	DATA BYTE 32,32,32,32,32,32,32,32
	DATA BYTE 255,255

msg_timeup:
	DATA BYTE 10,10,13,32,32,32,32,32
	DATA BYTE 32,32,32,32,32,32,32,32
	DATA BYTE 11,10,13,32,32,84,73,77
	DATA BYTE 69,32,85,80,33,32,32,32
	DATA BYTE 12,10,13,32,32,32,32,32
	DATA BYTE 32,32,32,32,32,32,32,32
	DATA BYTE 255,255
