	' ==================================================
	' THE TITLE'S NAME -- whole kerned words, sliced
	' Generated by assets/gentitle.py from titleword.py.
	' Do not edit here; edit the glyphs and rebuild.
	'
	' 44 distinct cells; blanks use the space character and
	' repeated cells share a code. setup_font must load them
	' with EXACTLY these arguments:
	'     DEFINE CHAR    0,32,tfont_pat0
	'     DEFINE COLOR   0,32,tfont_col0
	'     DEFINE CHAR  185,12,tfont_pat1
	'     DEFINE COLOR 185,12,tfont_col1
	'
	' LIVES IN BANK 2 -- read once by those DEFINEs.
	' ==================================================

tfont_pat0:	' codes 0..31
	DATA BYTE $00,$00,$78,$78,$30,$30,$31,$33
	DATA BYTE $00,$00,$F7,$F7,$63,$C3,$83,$03
	DATA BYTE $00,$00,$FE,$FE,$00,$00,$00,$00
	DATA BYTE $00,$00,$78,$78,$30,$18,$18,$0D
	DATA BYTE $00,$00,$F1,$F3,$67,$C6,$C6,$87
	DATA BYTE $00,$00,$F8,$FC,$0E,$06,$00,$00
	DATA BYTE $00,$00,$7F,$7F,$06,$06,$06,$06
	DATA BYTE $00,$00,$E1,$E3,$07,$06,$06,$06
	DATA BYTE $00,$00,$F8,$FC,$0E,$06,$06,$06
	DATA BYTE $00,$00,$78,$78,$38,$38,$3C,$36
	DATA BYTE $00,$00,$F7,$67,$63,$63,$63,$63
	DATA BYTE $36,$3E,$3C,$3E,$36,$33,$31,$30
	DATA BYTE $03,$03,$03,$03,$03,$03,$83,$C3
	DATA BYTE $00,$F8,$F8,$F8,$00,$00,$00,$00
	DATA BYTE $0D,$07,$07,$03,$03,$03,$03,$03
	DATA BYTE $83,$01,$00,$00,$00,$00,$00,$00
	DATA BYTE $C0,$E0,$F0,$78,$3C,$1E,$0E,$06
	DATA BYTE $06,$06,$06,$06,$06,$06,$06,$06
	DATA BYTE $36,$33,$33,$33,$31,$31,$30,$30
	DATA BYTE $63,$63,$63,$63,$E3,$E3,$E3,$E3
	DATA BYTE $30,$30,$30,$30,$78,$78,$00,$00
	DATA BYTE $63,$63,$33,$33,$F7,$F7,$00,$00
	DATA BYTE $00,$00,$00,$00,$FE,$FE,$00,$00
	DATA BYTE $03,$03,$03,$03,$0F,$0F,$00,$00
	DATA BYTE $00,$06,$06,$07,$C3,$C1,$00,$00
	DATA BYTE $06,$06,$06,$0E,$FC,$F8,$00,$00
	DATA BYTE $06,$06,$06,$06,$1F,$1F,$00,$00
	DATA BYTE $06,$06,$06,$07,$83,$81,$00,$00
	DATA BYTE $63,$63,$63,$63,$F7,$F7,$00,$00
	DATA BYTE $00,$00,$F0,$F0,$60,$C0,$81,$01
	DATA BYTE $00,$00,$60,$F0,$F0,$F0,$98,$98
	DATA BYTE $00,$00,$7F,$7F,$30,$30,$30,$30

tfont_col0:
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4

tfont_pat1:	' codes 185..196
	DATA BYTE $00,$00,$C7,$E7,$63,$63,$63,$63
	DATA BYTE $00,$00,$C1,$E3,$67,$66,$66,$67
	DATA BYTE $01,$03,$03,$03,$03,$03,$86,$C6
	DATA BYTE $98,$0C,$0C,$FC,$FC,$0C,$06,$06
	DATA BYTE $30,$30,$3F,$3F,$30,$30,$30,$30
	DATA BYTE $63,$C3,$C3,$83,$03,$03,$03,$03
	DATA BYTE $30,$3F,$3F,$36,$33,$33,$31,$31
	DATA BYTE $C3,$C1,$80,$00,$00,$00,$80,$80
	DATA BYTE $66,$66,$36,$36,$FF,$FF,$00,$00
	DATA BYTE $06,$06,$06,$06,$0F,$0F,$00,$00
	DATA BYTE $03,$03,$03,$03,$07,$07,$00,$00
	DATA BYTE $C0,$C6,$66,$67,$F3,$F1,$00,$00

tfont_col1:
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
