	' ==================================================
	' THE TITLE'S DISPLAY FACE -- 16x16 letters
	' Generated by assets/gentitle.py from titleface.py.
	' Do not edit here; edit the glyphs and rebuild.
	'
	' Four characters per letter: TL TR BL BR, in the order
	' A E K N O P R S T Y
	'
	' IN TWO PIECES, because the character table has no run
	' long enough -- see titleface.FREE_RUNS. setup_font must
	' load them with EXACTLY these arguments:
	'     DEFINE CHAR  182,26,tfont_pat0
	'     DEFINE COLOR 182,26,tfont_col0
	'     DEFINE CHAR    0,14,tfont_pat1
	'     DEFINE COLOR   0,14,tfont_col1
	'
	' LIVES IN BANK 2 -- read once by those DEFINEs, never
	' during play.
	' ==================================================

tfont_pat0:	' codes 182..207
	DATA BYTE $00,$07,$0F,$0C,$18,$18,$3F,$3F
	DATA BYTE $00,$80,$C0,$C0,$60,$60,$F0,$F0
	DATA BYTE $30,$60,$60,$70,$00,$00,$00,$00
	DATA BYTE $30,$18,$18,$38,$00,$00,$00,$00
	DATA BYTE $00,$7F,$7F,$30,$30,$30,$3F,$3F
	DATA BYTE $00,$E0,$E0,$00,$00,$00,$C0,$C0
	DATA BYTE $30,$30,$30,$7F,$7F,$00,$00,$00
	DATA BYTE $00,$00,$00,$E0,$E0,$00,$00,$00
	DATA BYTE $00,$70,$30,$31,$33,$36,$3E,$3E
	DATA BYTE $00,$70,$C0,$80,$00,$00,$00,$00
	DATA BYTE $36,$33,$31,$30,$30,$70,$00,$00
	DATA BYTE $00,$00,$80,$C0,$60,$38,$00,$00
	DATA BYTE $00,$70,$78,$7C,$6C,$66,$63,$61
	DATA BYTE $00,$70,$70,$70,$70,$70,$70,$F0
	DATA BYTE $60,$60,$60,$70,$00,$00,$00,$00
	DATA BYTE $F0,$70,$70,$70,$00,$00,$00,$00
	DATA BYTE $00,$0F,$1F,$38,$30,$30,$30,$30
	DATA BYTE $00,$C0,$E0,$70,$30,$30,$30,$30
	DATA BYTE $30,$38,$1F,$0F,$00,$00,$00,$00
	DATA BYTE $30,$70,$E0,$C0,$00,$00,$00,$00
	DATA BYTE $00,$7F,$7F,$60,$60,$60,$7F,$7F
	DATA BYTE $00,$C0,$E0,$60,$60,$60,$E0,$C0
	DATA BYTE $60,$60,$60,$78,$78,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$7F,$7F,$60,$60,$7F,$7F,$63
	DATA BYTE $00,$C0,$E0,$60,$60,$E0,$C0,$00

tfont_col0:
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4

tfont_pat1:	' codes 0..13
	DATA BYTE $61,$60,$60,$70,$00,$00,$00,$00
	DATA BYTE $80,$C0,$60,$38,$00,$00,$00,$00
	DATA BYTE $00,$1F,$3F,$38,$30,$38,$1F,$07
	DATA BYTE $00,$C0,$E0,$60,$00,$00,$80,$E0
	DATA BYTE $00,$30,$38,$3F,$1F,$00,$00,$00
	DATA BYTE $70,$70,$E0,$E0,$C0,$00,$00,$00
	DATA BYTE $00,$7F,$7F,$06,$06,$06,$06,$06
	DATA BYTE $00,$F0,$F0,$00,$00,$00,$00,$00
	DATA BYTE $06,$06,$06,$0F,$0F,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$70,$30,$30,$19,$1B,$0E,$0E
	DATA BYTE $00,$70,$60,$C0,$80,$00,$00,$00
	DATA BYTE $06,$06,$06,$0F,$0F,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00

tfont_col1:
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
	DATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4
