	' BUST-A-BOBBLE art + tables -- GENERATED by assets/genart.py
	' Do not edit. Regenerate instead.

	' The 16x16 bubble as four 8x8 characters (TL,TR,BL,BR). ALL EIGHT COLOURS
	' SHARE THIS ONE PATTERN -- only DEFINE COLOR differs -- so the game issues
	' eight DEFINE CHAR calls against these same 32 bytes instead of storing
	' 8 x 32 bytes of identical pixels.
bub_pat:
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$FF,$FF,$FF	' TL, rows 0-7
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$FF,$FF,$FF	' TR, rows 0-7
	DATA BYTE $FF,$FF,$FF,$7F,$7F,$3F,$1F,$0F	' BL, rows 8-15
	DATA BYTE $FF,$FF,$FF,$FE,$FE,$FC,$F8,$F0	' BR, rows 8-15

	' Per-scan-line colours for chars 128..159 (8 colours x TL,TR,BL,BR).
	' fg*16+bg; bg is always black. The TOP chars switch from lit to base at
	' pixel row 6; the BOTTOM chars are all base.
bub_col:
	' colour 1  base=8  lit=9 
	DATA BYTE $91,$91,$91,$91,$91,$91,$81,$81	' TL
	DATA BYTE $91,$91,$91,$91,$91,$91,$81,$81	' TR
	DATA BYTE $81,$81,$81,$81,$81,$81,$81,$81	' BL
	DATA BYTE $81,$81,$81,$81,$81,$81,$81,$81	' BR
	' colour 2  base=12 lit=3 
	DATA BYTE $31,$31,$31,$31,$31,$31,$C1,$C1	' TL
	DATA BYTE $31,$31,$31,$31,$31,$31,$C1,$C1	' TR
	DATA BYTE $C1,$C1,$C1,$C1,$C1,$C1,$C1,$C1	' BL
	DATA BYTE $C1,$C1,$C1,$C1,$C1,$C1,$C1,$C1	' BR
	' colour 3  base=4  lit=5 
	DATA BYTE $51,$51,$51,$51,$51,$51,$41,$41	' TL
	DATA BYTE $51,$51,$51,$51,$51,$51,$41,$41	' TR
	DATA BYTE $41,$41,$41,$41,$41,$41,$41,$41	' BL
	DATA BYTE $41,$41,$41,$41,$41,$41,$41,$41	' BR
	' colour 4  base=10 lit=11
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$A1,$A1	' TL
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$A1,$A1	' TR
	DATA BYTE $A1,$A1,$A1,$A1,$A1,$A1,$A1,$A1	' BL
	DATA BYTE $A1,$A1,$A1,$A1,$A1,$A1,$A1,$A1	' BR
	' colour 5  base=7  lit=15
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$71,$71	' TL
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$71,$71	' TR
	DATA BYTE $71,$71,$71,$71,$71,$71,$71,$71	' BL
	DATA BYTE $71,$71,$71,$71,$71,$71,$71,$71	' BR
	' colour 6  base=13 lit=15
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$D1,$D1	' TL
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$D1,$D1	' TR
	DATA BYTE $D1,$D1,$D1,$D1,$D1,$D1,$D1,$D1	' BL
	DATA BYTE $D1,$D1,$D1,$D1,$D1,$D1,$D1,$D1	' BR
	' colour 7  base=14 lit=15
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$E1,$E1	' TL
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$E1,$E1	' TR
	DATA BYTE $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1	' BL
	DATA BYTE $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1	' BR
	' colour 8  base=6  lit=9 
	DATA BYTE $91,$91,$91,$91,$91,$91,$61,$61	' TL
	DATA BYTE $91,$91,$91,$91,$91,$91,$61,$61	' TR
	DATA BYTE $61,$61,$61,$61,$61,$61,$61,$61	' BL
	DATA BYTE $61,$61,$61,$61,$61,$61,$61,$61	' BR

	' Flying bubble = TWO overlaid 16x16 sprites so it is pixel-identical to the
	' same bubble once it sticks and becomes characters (a sprite is one colour).
	' 16 bytes left column then 16 bytes right column -- NOT sequential scan lines.
spr_cap:	' lit upper cap, pixel rows 0-5
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$FF,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$FF,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
spr_body:	' base lower body, pixel rows 6-15
	DATA BYTE $00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$FF,$7F,$7F,$3F,$1F,$0F
	DATA BYTE $00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$FF,$FE,$FE,$FC,$F8,$F0
spr_dot:	' 4x4 aim-guide dot, centred in the 16x16 cell
	DATA BYTE $00,$00,$00,$00,$00,$00,$03,$03,$03,$03,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$C0,$C0,$C0,$C0,$00,$00,$00,$00,$00,$00

	' Aim table: 32 steps from vertical to 80 degrees, speed 5 px/frame, 8.8 fixed
	' point. BOTH MAGNITUDES ARE POSITIVE -- direction is a separate flag, because
	' CVBasic compiles every #var comparison UNSIGNED (a signed velocity would
	' silently misbehave at every sign test).
#aimdx:
	DATA 0,58,115,172,229,286,342,397
	DATA 451,505,557,609,659,707,755,800
	DATA 845,887,928,967,1003,1038,1071,1101
	DATA 1129,1155,1179,1200,1219,1235,1249,1261
#aimdy:
	DATA 1280,1279,1275,1268,1259,1248,1234,1217
	DATA 1198,1176,1152,1126,1098,1067,1034,999
	DATA 962,923,882,839,795,749,701,652
	DATA 602,551,498,445,390,335,279,222

	' Drop score. The i-th dropped bubble is worth 20 * 2^(i-1) POINTS, which is
	' exactly 2^i UNITS OF 10. Capped at i=17 -> 131072 units = 1,310,720 points,
	' the documented arcade maximum for one drop.
	' Stored as 6 BCD digits, most significant first, so adding into the score is
	' a digit-wise add with carry -- no division, no 32-bit arithmetic, no overflow.
dropbcd:
	DATA BYTE $00,$00,$00,$00,$00,$02	'  1 bubbles:      2 units = 20 pts
	DATA BYTE $00,$00,$00,$00,$00,$04	'  2 bubbles:      4 units = 40 pts
	DATA BYTE $00,$00,$00,$00,$00,$08	'  3 bubbles:      8 units = 80 pts
	DATA BYTE $00,$00,$00,$00,$01,$06	'  4 bubbles:     16 units = 160 pts
	DATA BYTE $00,$00,$00,$00,$03,$02	'  5 bubbles:     32 units = 320 pts
	DATA BYTE $00,$00,$00,$00,$06,$04	'  6 bubbles:     64 units = 640 pts
	DATA BYTE $00,$00,$00,$01,$02,$08	'  7 bubbles:    128 units = 1,280 pts
	DATA BYTE $00,$00,$00,$02,$05,$06	'  8 bubbles:    256 units = 2,560 pts
	DATA BYTE $00,$00,$00,$05,$01,$02	'  9 bubbles:    512 units = 5,120 pts
	DATA BYTE $00,$00,$01,$00,$02,$04	' 10 bubbles:   1024 units = 10,240 pts
	DATA BYTE $00,$00,$02,$00,$04,$08	' 11 bubbles:   2048 units = 20,480 pts
	DATA BYTE $00,$00,$04,$00,$09,$06	' 12 bubbles:   4096 units = 40,960 pts
	DATA BYTE $00,$00,$08,$01,$09,$02	' 13 bubbles:   8192 units = 81,920 pts
	DATA BYTE $00,$01,$06,$03,$08,$04	' 14 bubbles:  16384 units = 163,840 pts
	DATA BYTE $00,$03,$02,$07,$06,$08	' 15 bubbles:  32768 units = 327,680 pts
	DATA BYTE $00,$06,$05,$05,$03,$06	' 16 bubbles:  65536 units = 655,360 pts
	DATA BYTE $01,$03,$01,$00,$07,$02	' 17 bubbles: 131072 units = 1,310,720 pts

