	' BUST-A-BOBBLE art + tables -- GENERATED by assets/genart.py
	' Do not edit. Regenerate instead.

	' The 16x16 bubble as four 8x8 characters (TL,TR,BL,BR), PER COLOUR --
	' 32 chars in one DEFINE CHAR. They used to share one pattern, but a
	' dithered colour needs its own pixels: on a two-colours-per-line display
	' a gradient can only come from pixel density, not from more colours.
bub_pat:
	' colour 1  DITHERED
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5	' TL
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55	' TR
	DATA BYTE $AA,$91,$A2,$44,$48,$31,$12,$0F	' BL
	DATA BYTE $AB,$11,$23,$46,$8A,$14,$28,$F0	' BR
	' colour 2  DITHERED
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5	' TL
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55	' TR
	DATA BYTE $AA,$91,$A2,$44,$48,$31,$12,$0F	' BL
	DATA BYTE $AB,$11,$23,$46,$8A,$14,$28,$F0	' BR
	' colour 3  DITHERED
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5	' TL
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55	' TR
	DATA BYTE $AA,$91,$A2,$44,$48,$31,$12,$0F	' BL
	DATA BYTE $AB,$11,$23,$46,$8A,$14,$28,$F0	' BR
	' colour 4  DITHERED
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5	' TL
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55	' TR
	DATA BYTE $AA,$91,$A2,$44,$48,$31,$12,$0F	' BL
	DATA BYTE $AB,$11,$23,$46,$8A,$14,$28,$F0	' BR
	' colour 5  DITHERED
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5	' TL
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55	' TR
	DATA BYTE $AA,$91,$A2,$44,$48,$31,$12,$0F	' BL
	DATA BYTE $AB,$11,$23,$46,$8A,$14,$28,$F0	' BR
	' colour 6  DITHERED
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5	' TL
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55	' TR
	DATA BYTE $AA,$91,$A2,$44,$48,$31,$12,$0F	' BL
	DATA BYTE $AB,$11,$23,$46,$8A,$14,$28,$F0	' BR
	' colour 7  DITHERED
	DATA BYTE $0F,$1F,$3F,$44,$48,$91,$A2,$C0	' TL
	DATA BYTE $F0,$F8,$FC,$46,$8A,$11,$23,$41	' TR
	DATA BYTE $80,$81,$82,$44,$48,$30,$10,$0F	' BL
	DATA BYTE $81,$01,$03,$06,$0A,$14,$28,$F0	' BR
	' colour 8  DITHERED
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$FF,$FF,$FF	' TL
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$FF,$FF,$FF	' TR
	DATA BYTE $FF,$FF,$FF,$55,$6A,$35,$1A,$0F	' BL
	DATA BYTE $FF,$FF,$FF,$56,$AA,$54,$A8,$F0	' BR

	' Pop animation: 3 frames x 4 chars (TL,TR,BL,BR), chars 164-175.
	' Shared by every colour: the burst flashes white/yellow/grey rather than
	' inheriting the bubble's hue, which would cost 8 times the characters.
bur_pat:
	' frame 0
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$FF,$FF,$FF	' TL
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$FF,$FF,$FF	' TR
	DATA BYTE $FF,$FF,$FF,$7F,$7F,$3F,$1F,$0F	' BL
	DATA BYTE $FF,$FF,$FF,$FE,$FE,$FC,$F8,$F0	' BR
	' frame 1
	DATA BYTE $0A,$15,$2A,$55,$2A,$55,$AA,$55	' TL
	DATA BYTE $A0,$50,$A8,$54,$AA,$55,$AA,$55	' TR
	DATA BYTE $AA,$55,$AA,$55,$2A,$15,$0A,$05	' BL
	DATA BYTE $AA,$55,$AA,$54,$AA,$54,$A8,$50	' BR
	' frame 2
	DATA BYTE $08,$11,$22,$44,$08,$11,$22,$44	' TL
	DATA BYTE $80,$10,$20,$44,$88,$11,$22,$44	' TR
	DATA BYTE $88,$11,$22,$44,$08,$11,$02,$04	' BL
	DATA BYTE $88,$11,$22,$44,$88,$10,$20,$40	' BR
bur_col:	' white flash -> yellow -> grey, one colour per frame
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1
	DATA BYTE $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1
	DATA BYTE $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1
	DATA BYTE $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1
	DATA BYTE $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1

	' Per-scan-line colours for chars 128..159 (8 colours x TL,TR,BL,BR).
	' fg*16+bg; bg is always black. The TOP chars switch from lit to base at
	' pixel row 6; the BOTTOM chars are all base.
bub_col:
	' colour 1  base=9  lit=9  litrows=5  DITHERED
	DATA BYTE $91,$91,$91,$91,$91,$91,$91,$91	' TL
	DATA BYTE $91,$91,$91,$91,$91,$91,$91,$91	' TR
	DATA BYTE $91,$91,$91,$91,$91,$91,$91,$91	' BL
	DATA BYTE $91,$91,$91,$91,$91,$91,$91,$91	' BR
	' colour 2  base=3  lit=3  litrows=5  DITHERED
	DATA BYTE $31,$31,$31,$31,$31,$31,$31,$31	' TL
	DATA BYTE $31,$31,$31,$31,$31,$31,$31,$31	' TR
	DATA BYTE $31,$31,$31,$31,$31,$31,$31,$31	' BL
	DATA BYTE $31,$31,$31,$31,$31,$31,$31,$31	' BR
	' colour 3  base=5  lit=5  litrows=5  DITHERED
	DATA BYTE $51,$51,$51,$51,$51,$51,$51,$51	' TL
	DATA BYTE $51,$51,$51,$51,$51,$51,$51,$51	' TR
	DATA BYTE $51,$51,$51,$51,$51,$51,$51,$51	' BL
	DATA BYTE $51,$51,$51,$51,$51,$51,$51,$51	' BR
	' colour 4  base=11 lit=11 litrows=5  DITHERED
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1	' TL
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1	' TR
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1	' BL
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1	' BR
	' colour 5  base=7  lit=7  litrows=5  DITHERED
	DATA BYTE $71,$71,$71,$71,$71,$71,$71,$71	' TL
	DATA BYTE $71,$71,$71,$71,$71,$71,$71,$71	' TR
	DATA BYTE $71,$71,$71,$71,$71,$71,$71,$71	' BL
	DATA BYTE $71,$71,$71,$71,$71,$71,$71,$71	' BR
	' colour 6  base=13 lit=13 litrows=5  DITHERED
	DATA BYTE $D1,$D1,$D1,$D1,$D1,$D1,$D1,$D1	' TL
	DATA BYTE $D1,$D1,$D1,$D1,$D1,$D1,$D1,$D1	' TR
	DATA BYTE $D1,$D1,$D1,$D1,$D1,$D1,$D1,$D1	' BL
	DATA BYTE $D1,$D1,$D1,$D1,$D1,$D1,$D1,$D1	' BR
	' colour 7  base=14 lit=14 litrows=5  DITHERED
	DATA BYTE $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1	' TL
	DATA BYTE $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1	' TR
	DATA BYTE $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1	' BL
	DATA BYTE $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1	' BR
	' colour 8  base=15 lit=15 litrows=5  DITHERED
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1	' TL
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1	' TR
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1	' BL
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1	' BR

	' Bubbles WITH the death line through them, chars 186-217 (4 per colour).
	' Scan lines 2 and 5 are cleared to black -- the spacers; 3-4 keep the ball's
	' silhouette and are recoloured by bub_colx/bub_colxf.
bub_patx:
	' colour 1
	DATA BYTE $0F,$1F,$00,$3C,$3C,$00,$AA,$D5	' TL
	DATA BYTE $F0,$F8,$00,$3C,$3C,$00,$AB,$55	' TR
	DATA BYTE $AA,$91,$00,$3C,$3C,$00,$12,$0F	' BL
	DATA BYTE $AB,$11,$00,$3C,$3C,$00,$28,$F0	' BR
	' colour 2
	DATA BYTE $0F,$1F,$00,$3C,$3C,$00,$AA,$D5	' TL
	DATA BYTE $F0,$F8,$00,$3C,$3C,$00,$AB,$55	' TR
	DATA BYTE $AA,$91,$00,$3C,$3C,$00,$12,$0F	' BL
	DATA BYTE $AB,$11,$00,$3C,$3C,$00,$28,$F0	' BR
	' colour 3
	DATA BYTE $0F,$1F,$00,$3C,$3C,$00,$AA,$D5	' TL
	DATA BYTE $F0,$F8,$00,$3C,$3C,$00,$AB,$55	' TR
	DATA BYTE $AA,$91,$00,$3C,$3C,$00,$12,$0F	' BL
	DATA BYTE $AB,$11,$00,$3C,$3C,$00,$28,$F0	' BR
	' colour 4
	DATA BYTE $0F,$1F,$00,$3C,$3C,$00,$AA,$D5	' TL
	DATA BYTE $F0,$F8,$00,$3C,$3C,$00,$AB,$55	' TR
	DATA BYTE $AA,$91,$00,$3C,$3C,$00,$12,$0F	' BL
	DATA BYTE $AB,$11,$00,$3C,$3C,$00,$28,$F0	' BR
	' colour 5
	DATA BYTE $0F,$1F,$00,$3C,$3C,$00,$AA,$D5	' TL
	DATA BYTE $F0,$F8,$00,$3C,$3C,$00,$AB,$55	' TR
	DATA BYTE $AA,$91,$00,$3C,$3C,$00,$12,$0F	' BL
	DATA BYTE $AB,$11,$00,$3C,$3C,$00,$28,$F0	' BR
	' colour 6
	DATA BYTE $0F,$1F,$00,$3C,$3C,$00,$AA,$D5	' TL
	DATA BYTE $F0,$F8,$00,$3C,$3C,$00,$AB,$55	' TR
	DATA BYTE $AA,$91,$00,$3C,$3C,$00,$12,$0F	' BL
	DATA BYTE $AB,$11,$00,$3C,$3C,$00,$28,$F0	' BR
	' colour 7
	DATA BYTE $0F,$1F,$00,$3C,$3C,$00,$A2,$C0	' TL
	DATA BYTE $F0,$F8,$00,$3C,$3C,$00,$23,$41	' TR
	DATA BYTE $80,$81,$00,$3C,$3C,$00,$10,$0F	' BL
	DATA BYTE $81,$01,$00,$3C,$3C,$00,$28,$F0	' BR
	' colour 8
	DATA BYTE $0F,$1F,$00,$3C,$3C,$00,$FF,$FF	' TL
	DATA BYTE $F0,$F8,$00,$3C,$3C,$00,$FF,$FF	' TR
	DATA BYTE $FF,$FF,$00,$3C,$3C,$00,$1A,$0F	' BL
	DATA BYTE $FF,$FF,$00,$3C,$3C,$00,$A8,$F0	' BR

	' at rest: yellow line -- scan lines 3-4 are the line, the rest is the bubble.
bub_colx:
	' colour 1
	DATA BYTE $91,$91,$91,$B1,$B1,$91,$91,$91	' TL
	DATA BYTE $91,$91,$91,$B1,$B1,$91,$91,$91	' TR
	DATA BYTE $91,$91,$91,$B1,$B1,$91,$91,$91	' BL
	DATA BYTE $91,$91,$91,$B1,$B1,$91,$91,$91	' BR
	' colour 2
	DATA BYTE $31,$31,$31,$B1,$B1,$31,$31,$31	' TL
	DATA BYTE $31,$31,$31,$B1,$B1,$31,$31,$31	' TR
	DATA BYTE $31,$31,$31,$B1,$B1,$31,$31,$31	' BL
	DATA BYTE $31,$31,$31,$B1,$B1,$31,$31,$31	' BR
	' colour 3
	DATA BYTE $51,$51,$51,$B1,$B1,$51,$51,$51	' TL
	DATA BYTE $51,$51,$51,$B1,$B1,$51,$51,$51	' TR
	DATA BYTE $51,$51,$51,$B1,$B1,$51,$51,$51	' BL
	DATA BYTE $51,$51,$51,$B1,$B1,$51,$51,$51	' BR
	' colour 4
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1	' TL
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1	' TR
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1	' BL
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1	' BR
	' colour 5
	DATA BYTE $71,$71,$71,$B1,$B1,$71,$71,$71	' TL
	DATA BYTE $71,$71,$71,$B1,$B1,$71,$71,$71	' TR
	DATA BYTE $71,$71,$71,$B1,$B1,$71,$71,$71	' BL
	DATA BYTE $71,$71,$71,$B1,$B1,$71,$71,$71	' BR
	' colour 6
	DATA BYTE $D1,$D1,$D1,$B1,$B1,$D1,$D1,$D1	' TL
	DATA BYTE $D1,$D1,$D1,$B1,$B1,$D1,$D1,$D1	' TR
	DATA BYTE $D1,$D1,$D1,$B1,$B1,$D1,$D1,$D1	' BL
	DATA BYTE $D1,$D1,$D1,$B1,$B1,$D1,$D1,$D1	' BR
	' colour 7
	DATA BYTE $E1,$E1,$E1,$B1,$B1,$E1,$E1,$E1	' TL
	DATA BYTE $E1,$E1,$E1,$B1,$B1,$E1,$E1,$E1	' TR
	DATA BYTE $E1,$E1,$E1,$B1,$B1,$E1,$E1,$E1	' BL
	DATA BYTE $E1,$E1,$E1,$B1,$B1,$E1,$E1,$E1	' BR
	' colour 8
	DATA BYTE $F1,$F1,$F1,$B1,$B1,$F1,$F1,$F1	' TL
	DATA BYTE $F1,$F1,$F1,$B1,$B1,$F1,$F1,$F1	' TR
	DATA BYTE $F1,$F1,$F1,$B1,$B1,$F1,$F1,$F1	' BL
	DATA BYTE $F1,$F1,$F1,$B1,$B1,$F1,$F1,$F1	' BR

	' death flash: red line -- scan lines 3-4 are the line, the rest is the bubble.
bub_colxf:
	' colour 1
	DATA BYTE $91,$91,$91,$91,$91,$91,$91,$91	' TL
	DATA BYTE $91,$91,$91,$91,$91,$91,$91,$91	' TR
	DATA BYTE $91,$91,$91,$91,$91,$91,$91,$91	' BL
	DATA BYTE $91,$91,$91,$91,$91,$91,$91,$91	' BR
	' colour 2
	DATA BYTE $31,$31,$31,$91,$91,$31,$31,$31	' TL
	DATA BYTE $31,$31,$31,$91,$91,$31,$31,$31	' TR
	DATA BYTE $31,$31,$31,$91,$91,$31,$31,$31	' BL
	DATA BYTE $31,$31,$31,$91,$91,$31,$31,$31	' BR
	' colour 3
	DATA BYTE $51,$51,$51,$91,$91,$51,$51,$51	' TL
	DATA BYTE $51,$51,$51,$91,$91,$51,$51,$51	' TR
	DATA BYTE $51,$51,$51,$91,$91,$51,$51,$51	' BL
	DATA BYTE $51,$51,$51,$91,$91,$51,$51,$51	' BR
	' colour 4
	DATA BYTE $B1,$B1,$B1,$91,$91,$B1,$B1,$B1	' TL
	DATA BYTE $B1,$B1,$B1,$91,$91,$B1,$B1,$B1	' TR
	DATA BYTE $B1,$B1,$B1,$91,$91,$B1,$B1,$B1	' BL
	DATA BYTE $B1,$B1,$B1,$91,$91,$B1,$B1,$B1	' BR
	' colour 5
	DATA BYTE $71,$71,$71,$91,$91,$71,$71,$71	' TL
	DATA BYTE $71,$71,$71,$91,$91,$71,$71,$71	' TR
	DATA BYTE $71,$71,$71,$91,$91,$71,$71,$71	' BL
	DATA BYTE $71,$71,$71,$91,$91,$71,$71,$71	' BR
	' colour 6
	DATA BYTE $D1,$D1,$D1,$91,$91,$D1,$D1,$D1	' TL
	DATA BYTE $D1,$D1,$D1,$91,$91,$D1,$D1,$D1	' TR
	DATA BYTE $D1,$D1,$D1,$91,$91,$D1,$D1,$D1	' BL
	DATA BYTE $D1,$D1,$D1,$91,$91,$D1,$D1,$D1	' BR
	' colour 7
	DATA BYTE $E1,$E1,$E1,$91,$91,$E1,$E1,$E1	' TL
	DATA BYTE $E1,$E1,$E1,$91,$91,$E1,$E1,$E1	' TR
	DATA BYTE $E1,$E1,$E1,$91,$91,$E1,$E1,$E1	' BL
	DATA BYTE $E1,$E1,$E1,$91,$91,$E1,$E1,$E1	' BR
	' colour 8
	DATA BYTE $F1,$F1,$F1,$91,$91,$F1,$F1,$F1	' TL
	DATA BYTE $F1,$F1,$F1,$91,$91,$F1,$F1,$F1	' TR
	DATA BYTE $F1,$F1,$F1,$91,$91,$F1,$F1,$F1	' BL
	DATA BYTE $F1,$F1,$F1,$91,$91,$F1,$F1,$F1	' BR

	' ONE 16x16 sprite per bubble colour. 16 bytes left column then 16 bytes
	' right column -- NOT sequential scan lines.
	'
	' This used to be THREE patterns per colour -- cap, body and full -- so the
	' flying bubble could be two overlaid sprites, a lit cap over a base body,
	' matching the two-tone character version. The dither rewrite made every ball
	' a SINGLE hue (base == lit for all eight), which quietly made the cap/body
	' split meaningless: two sprites of the same colour drawn on top of each
	' other are just the full ball. Collapsing it frees 512 bytes of pattern
	' table, halves the sprites the loop touches, and removes the class of bug
	' where the cap lagged the body by a frame.
spr_bub:
	' colour 1
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5,$AA,$91,$A2,$44,$48,$31,$12,$0F
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55,$AB,$11,$23,$46,$8A,$14,$28,$F0
	' colour 2
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5,$AA,$91,$A2,$44,$48,$31,$12,$0F
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55,$AB,$11,$23,$46,$8A,$14,$28,$F0
	' colour 3
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5,$AA,$91,$A2,$44,$48,$31,$12,$0F
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55,$AB,$11,$23,$46,$8A,$14,$28,$F0
	' colour 4
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5,$AA,$91,$A2,$44,$48,$31,$12,$0F
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55,$AB,$11,$23,$46,$8A,$14,$28,$F0
	' colour 5
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5,$AA,$91,$A2,$44,$48,$31,$12,$0F
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55,$AB,$11,$23,$46,$8A,$14,$28,$F0
	' colour 6
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5,$AA,$91,$A2,$44,$48,$31,$12,$0F
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55,$AB,$11,$23,$46,$8A,$14,$28,$F0
	' colour 7
	DATA BYTE $0F,$1F,$3F,$44,$48,$91,$A2,$C0,$80,$81,$82,$44,$48,$30,$10,$0F
	DATA BYTE $F0,$F8,$FC,$46,$8A,$11,$23,$41,$81,$01,$03,$06,$0A,$14,$28,$F0
	' colour 8
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$FF,$FF,$FF,$FF,$FF,$FF,$55,$6A,$35,$1A,$0F
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$FF,$FF,$FF,$FF,$FF,$FF,$56,$AA,$54,$A8,$F0
bub_base:	' sprite colour per bubble colour 1..8
	DATA BYTE $09,$03,$05,$0B,$07,$0D,$0E,$0F

	' The spare-life creature, 8x8. Eyes are UNLIT pixels -- a character is one
	' colour per scan line, so holes are how you draw a face at this size.
life_pat:
	DATA BYTE $3C,$7E,$DB,$FF,$FF,$7E,$66,$E7
life_col:
	DATA BYTE $31,$31,$31,$31,$31,$31,$31,$31

	' The same creature at 2x as a 16x16 SPRITE, two walk frames, for the title
	' screen. 16 bytes left column then 16 bytes right column -- NOT scan lines.
spr_walk:
	' frame A  legs apart
	DATA BYTE $0F,$0F,$3F,$3F,$F3,$F3,$FF,$FF,$FF,$FF,$3F,$3F,$3C,$3C,$FC,$FC
	DATA BYTE $F0,$F0,$FC,$FC,$CF,$CF,$FF,$FF,$FF,$FF,$FC,$FC,$3C,$3C,$3F,$3F
	' frame B  legs together
	DATA BYTE $0F,$0F,$3F,$3F,$F3,$F3,$FF,$FF,$FF,$FF,$3F,$3F,$03,$03,$0F,$0F
	DATA BYTE $F0,$F0,$FC,$FC,$CF,$CF,$FF,$FF,$FF,$FF,$FC,$FC,$C0,$C0,$F0,$F0

	' The waving arm: patterns 27-28 wave with the RIGHT hand, 29-30 with the
	' LEFT. Laid over the body at the same y, 8 px to whichever side is waving,
	' so the shoulder meets his body at shoulder height and clears his eyes.
spr_wave:
	' right hand -- frame A, hand out
	DATA BYTE $00,$01,$01,$00,$03,$06,$06,$0C,$0C,$18,$18,$00,$00,$00,$00,$00
	DATA BYTE $E0,$F0,$F0,$E0,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	' right hand -- frame B, hand rocked back
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$03,$06,$0C,$18,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$70,$F8,$F8,$70,$00,$00,$00,$00,$00,$00,$00,$00,$00
	' left hand (mirrored) -- frame A, hand out
	DATA BYTE $07,$0F,$0F,$07,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$80,$80,$00,$C0,$60,$60,$30,$30,$18,$18,$00,$00,$00,$00,$00
	' left hand (mirrored) -- frame B, hand rocked back
	DATA BYTE $00,$00,$00,$0E,$1F,$1F,$0E,$00,$00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$C0,$60,$30,$18,$00,$00,$00,$00,$00

spr_dot:	' 4x4 aim-guide dot, centred in the 16x16 cell
	DATA BYTE $00,$00,$00,$00,$00,$00,$03,$03,$03,$03,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$C0,$C0,$C0,$C0,$00,$00,$00,$00,$00,$00

	' Aim table: 32 steps from vertical to 80 degrees, speed 5 px/frame, 8.8 fixed
	' point. BOTH MAGNITUDES ARE POSITIVE -- direction is a separate flag, because
	' CVBasic compiles every #var comparison UNSIGNED (a signed velocity would
	' silently misbehave at every sign test).
#aimdx:
	DATA 0,58,115,172,229,286,342,397
	DATA 451,505,557,609,659,707,755,800
	DATA 845,887,928,967,1003,1038,1071,1101
	DATA 1129,1155,1179,1200,1219,1235,1249,1261
#aimdy:
	DATA 1280,1279,1275,1268,1259,1248,1234,1217
	DATA 1198,1176,1152,1126,1098,1067,1034,999
	DATA 962,923,882,839,795,749,701,652
	DATA 602,551,498,445,390,335,279,222

	' NEXT, 16x5, in a 3x5 font: N E X T at 3 px each with 1 px between = 15 px,
	' which is why two characters is exactly enough. Rows 1-5 of the cell, so it
	' clears the death line above and the waiting bubble below.
sign_pat:
	DATA BYTE $00,$AE,$E8,$EC,$A8,$AE,$00,$00
	DATA BYTE $00,$AE,$A4,$44,$A4,$A4,$00,$00

