	' BUST-A-BOBBLE art + tables -- GENERATED by assets/genart.py
	' Do not edit. Regenerate instead.

	' The 16x16 bubble as four 8x8 characters (TL,TR,BL,BR), PER COLOUR --
	' 32 chars in one DEFINE CHAR. They used to share one pattern, but a
	' dithered colour needs its own pixels: on a two-colours-per-line display
	' a gradient can only come from pixel density, not from more colours.
bub_pat:
	' colour 1  DITHERED
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5	' TL
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55	' TR
	DATA BYTE $AA,$91,$A2,$44,$48,$31,$12,$0F	' BL
	DATA BYTE $AB,$11,$23,$46,$8A,$14,$28,$F0	' BR
	' colour 2  DITHERED
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5	' TL
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55	' TR
	DATA BYTE $AA,$91,$A2,$44,$48,$31,$12,$0F	' BL
	DATA BYTE $AB,$11,$23,$46,$8A,$14,$28,$F0	' BR
	' colour 3  DITHERED
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5	' TL
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55	' TR
	DATA BYTE $AA,$91,$A2,$44,$48,$31,$12,$0F	' BL
	DATA BYTE $AB,$11,$23,$46,$8A,$14,$28,$F0	' BR
	' colour 4  DITHERED
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5	' TL
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55	' TR
	DATA BYTE $AA,$91,$A2,$44,$48,$31,$12,$0F	' BL
	DATA BYTE $AB,$11,$23,$46,$8A,$14,$28,$F0	' BR
	' colour 5  DITHERED
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5	' TL
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55	' TR
	DATA BYTE $AA,$91,$A2,$44,$48,$31,$12,$0F	' BL
	DATA BYTE $AB,$11,$23,$46,$8A,$14,$28,$F0	' BR
	' colour 6  DITHERED
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5	' TL
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55	' TR
	DATA BYTE $AA,$91,$A2,$44,$48,$31,$12,$0F	' BL
	DATA BYTE $AB,$11,$23,$46,$8A,$14,$28,$F0	' BR
	' colour 7  DITHERED
	DATA BYTE $0F,$1F,$3F,$44,$48,$91,$A2,$C0	' TL
	DATA BYTE $F0,$F8,$FC,$46,$8A,$11,$23,$41	' TR
	DATA BYTE $80,$81,$82,$44,$48,$30,$10,$0F	' BL
	DATA BYTE $81,$01,$03,$06,$0A,$14,$28,$F0	' BR
	' colour 8  DITHERED
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$FF,$FF,$FF	' TL
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$FF,$FF,$FF	' TR
	DATA BYTE $FF,$FF,$FF,$55,$6A,$35,$1A,$0F	' BL
	DATA BYTE $FF,$FF,$FF,$56,$AA,$54,$A8,$F0	' BR

	' Pop animation: 3 frames x 4 chars (TL,TR,BL,BR), chars 164-175.
	' Shared by every colour: the burst flashes white/yellow/grey rather than
	' inheriting the bubble's hue, which would cost 8 times the characters.
bur_pat:
	' frame 0
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$FF,$FF,$FF	' TL
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$FF,$FF,$FF	' TR
	DATA BYTE $FF,$FF,$FF,$7F,$7F,$3F,$1F,$0F	' BL
	DATA BYTE $FF,$FF,$FF,$FE,$FE,$FC,$F8,$F0	' BR
	' frame 1
	DATA BYTE $0A,$15,$2A,$55,$2A,$55,$AA,$55	' TL
	DATA BYTE $A0,$50,$A8,$54,$AA,$55,$AA,$55	' TR
	DATA BYTE $AA,$55,$AA,$55,$2A,$15,$0A,$05	' BL
	DATA BYTE $AA,$55,$AA,$54,$AA,$54,$A8,$50	' BR
	' frame 2
	DATA BYTE $08,$11,$22,$44,$08,$11,$22,$44	' TL
	DATA BYTE $80,$10,$20,$44,$88,$11,$22,$44	' TR
	DATA BYTE $88,$11,$22,$44,$08,$11,$02,$04	' BL
	DATA BYTE $88,$11,$22,$44,$88,$10,$20,$40	' BR
bur_col:	' white flash -> yellow -> grey, one colour per frame
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1
	DATA BYTE $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1
	DATA BYTE $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1
	DATA BYTE $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1
	DATA BYTE $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1

	' Per-scan-line colours for chars 128..159 (8 colours x TL,TR,BL,BR).
	' fg*16+bg; bg is always black. The TOP chars switch from lit to base at
	' pixel row 6; the BOTTOM chars are all base.
bub_col:
	' colour 1  base=9  lit=9  litrows=5  DITHERED
	DATA BYTE $91,$91,$91,$91,$91,$91,$91,$91	' TL
	DATA BYTE $91,$91,$91,$91,$91,$91,$91,$91	' TR
	DATA BYTE $91,$91,$91,$91,$91,$91,$91,$91	' BL
	DATA BYTE $91,$91,$91,$91,$91,$91,$91,$91	' BR
	' colour 2  base=3  lit=3  litrows=5  DITHERED
	DATA BYTE $31,$31,$31,$31,$31,$31,$31,$31	' TL
	DATA BYTE $31,$31,$31,$31,$31,$31,$31,$31	' TR
	DATA BYTE $31,$31,$31,$31,$31,$31,$31,$31	' BL
	DATA BYTE $31,$31,$31,$31,$31,$31,$31,$31	' BR
	' colour 3  base=5  lit=5  litrows=5  DITHERED
	DATA BYTE $51,$51,$51,$51,$51,$51,$51,$51	' TL
	DATA BYTE $51,$51,$51,$51,$51,$51,$51,$51	' TR
	DATA BYTE $51,$51,$51,$51,$51,$51,$51,$51	' BL
	DATA BYTE $51,$51,$51,$51,$51,$51,$51,$51	' BR
	' colour 4  base=11 lit=11 litrows=5  DITHERED
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1	' TL
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1	' TR
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1	' BL
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1	' BR
	' colour 5  base=7  lit=7  litrows=5  DITHERED
	DATA BYTE $71,$71,$71,$71,$71,$71,$71,$71	' TL
	DATA BYTE $71,$71,$71,$71,$71,$71,$71,$71	' TR
	DATA BYTE $71,$71,$71,$71,$71,$71,$71,$71	' BL
	DATA BYTE $71,$71,$71,$71,$71,$71,$71,$71	' BR
	' colour 6  base=13 lit=13 litrows=5  DITHERED
	DATA BYTE $D1,$D1,$D1,$D1,$D1,$D1,$D1,$D1	' TL
	DATA BYTE $D1,$D1,$D1,$D1,$D1,$D1,$D1,$D1	' TR
	DATA BYTE $D1,$D1,$D1,$D1,$D1,$D1,$D1,$D1	' BL
	DATA BYTE $D1,$D1,$D1,$D1,$D1,$D1,$D1,$D1	' BR
	' colour 7  base=14 lit=14 litrows=5  DITHERED
	DATA BYTE $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1	' TL
	DATA BYTE $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1	' TR
	DATA BYTE $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1	' BL
	DATA BYTE $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1	' BR
	' colour 8  base=15 lit=15 litrows=5  DITHERED
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1	' TL
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1	' TR
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1	' BL
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1	' BR

	' Flying bubble = TWO overlaid 16x16 sprites so it is pixel-identical to the
	' same bubble once it sticks and becomes characters (a sprite is one colour).
	' 16 bytes left column then 16 bytes right column -- NOT sequential scan lines.
	' THREE patterns per colour: 3k = cap, 3k+1 = body, 3k+2 = FULL ball.
	' cap/body are per colour because litrows is -- the flying bubble must
	' split at the same row its character form does or it stops matching the
	' moment it lands. FULL is for falling debris: one sprite instead of two,
	' which halves the slots used AND keeps them off each other's scanlines
	' (only four sprites show per line). Drawing debris with the body pattern
	' alone is what made the falling bubbles look like bottom halves.
spr_bub:
	' colour 1 cap (rows 0-4)
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	' colour 1 body (rows 5-15)
	DATA BYTE $00,$00,$00,$00,$00,$D5,$AA,$D5,$AA,$91,$A2,$44,$48,$31,$12,$0F
	DATA BYTE $00,$00,$00,$00,$00,$55,$AB,$55,$AB,$11,$23,$46,$8A,$14,$28,$F0
	' colour 1 full
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5,$AA,$91,$A2,$44,$48,$31,$12,$0F
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55,$AB,$11,$23,$46,$8A,$14,$28,$F0
	' colour 2 cap (rows 0-4)
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	' colour 2 body (rows 5-15)
	DATA BYTE $00,$00,$00,$00,$00,$D5,$AA,$D5,$AA,$91,$A2,$44,$48,$31,$12,$0F
	DATA BYTE $00,$00,$00,$00,$00,$55,$AB,$55,$AB,$11,$23,$46,$8A,$14,$28,$F0
	' colour 2 full
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5,$AA,$91,$A2,$44,$48,$31,$12,$0F
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55,$AB,$11,$23,$46,$8A,$14,$28,$F0
	' colour 3 cap (rows 0-4)
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	' colour 3 body (rows 5-15)
	DATA BYTE $00,$00,$00,$00,$00,$D5,$AA,$D5,$AA,$91,$A2,$44,$48,$31,$12,$0F
	DATA BYTE $00,$00,$00,$00,$00,$55,$AB,$55,$AB,$11,$23,$46,$8A,$14,$28,$F0
	' colour 3 full
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5,$AA,$91,$A2,$44,$48,$31,$12,$0F
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55,$AB,$11,$23,$46,$8A,$14,$28,$F0
	' colour 4 cap (rows 0-4)
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	' colour 4 body (rows 5-15)
	DATA BYTE $00,$00,$00,$00,$00,$D5,$AA,$D5,$AA,$91,$A2,$44,$48,$31,$12,$0F
	DATA BYTE $00,$00,$00,$00,$00,$55,$AB,$55,$AB,$11,$23,$46,$8A,$14,$28,$F0
	' colour 4 full
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5,$AA,$91,$A2,$44,$48,$31,$12,$0F
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55,$AB,$11,$23,$46,$8A,$14,$28,$F0
	' colour 5 cap (rows 0-4)
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	' colour 5 body (rows 5-15)
	DATA BYTE $00,$00,$00,$00,$00,$D5,$AA,$D5,$AA,$91,$A2,$44,$48,$31,$12,$0F
	DATA BYTE $00,$00,$00,$00,$00,$55,$AB,$55,$AB,$11,$23,$46,$8A,$14,$28,$F0
	' colour 5 full
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5,$AA,$91,$A2,$44,$48,$31,$12,$0F
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55,$AB,$11,$23,$46,$8A,$14,$28,$F0
	' colour 6 cap (rows 0-4)
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	' colour 6 body (rows 5-15)
	DATA BYTE $00,$00,$00,$00,$00,$D5,$AA,$D5,$AA,$91,$A2,$44,$48,$31,$12,$0F
	DATA BYTE $00,$00,$00,$00,$00,$55,$AB,$55,$AB,$11,$23,$46,$8A,$14,$28,$F0
	' colour 6 full
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$D5,$AA,$D5,$AA,$91,$A2,$44,$48,$31,$12,$0F
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$55,$AB,$55,$AB,$11,$23,$46,$8A,$14,$28,$F0
	' colour 7 cap (rows 0-4)
	DATA BYTE $0F,$1F,$3F,$44,$48,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $F0,$F8,$FC,$46,$8A,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	' colour 7 body (rows 5-15)
	DATA BYTE $00,$00,$00,$00,$00,$91,$A2,$C0,$80,$81,$82,$44,$48,$30,$10,$0F
	DATA BYTE $00,$00,$00,$00,$00,$11,$23,$41,$81,$01,$03,$06,$0A,$14,$28,$F0
	' colour 7 full
	DATA BYTE $0F,$1F,$3F,$44,$48,$91,$A2,$C0,$80,$81,$82,$44,$48,$30,$10,$0F
	DATA BYTE $F0,$F8,$FC,$46,$8A,$11,$23,$41,$81,$01,$03,$06,$0A,$14,$28,$F0
	' colour 8 cap (rows 0-4)
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	' colour 8 body (rows 5-15)
	DATA BYTE $00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$FF,$FF,$55,$6A,$35,$1A,$0F
	DATA BYTE $00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$FF,$FF,$56,$AA,$54,$A8,$F0
	' colour 8 full
	DATA BYTE $0F,$1F,$3F,$7F,$7F,$FF,$FF,$FF,$FF,$FF,$FF,$55,$6A,$35,$1A,$0F
	DATA BYTE $F0,$F8,$FC,$FE,$FE,$FF,$FF,$FF,$FF,$FF,$FF,$56,$AA,$54,$A8,$F0
bub_base:	' body colour per bubble colour 1..8
	DATA BYTE $09,$03,$05,$0B,$07,$0D,$0E,$0F
bub_lit:	' cap colour per bubble colour 1..8
	DATA BYTE $09,$03,$05,$0B,$07,$0D,$0E,$0F

spr_dot:	' 4x4 aim-guide dot, centred in the 16x16 cell
	DATA BYTE $00,$00,$00,$00,$00,$00,$03,$03,$03,$03,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$C0,$C0,$C0,$C0,$00,$00,$00,$00,$00,$00

	' Aim table: 32 steps from vertical to 80 degrees, speed 5 px/frame, 8.8 fixed
	' point. BOTH MAGNITUDES ARE POSITIVE -- direction is a separate flag, because
	' CVBasic compiles every #var comparison UNSIGNED (a signed velocity would
	' silently misbehave at every sign test).
#aimdx:
	DATA 0,58,115,172,229,286,342,397
	DATA 451,505,557,609,659,707,755,800
	DATA 845,887,928,967,1003,1038,1071,1101
	DATA 1129,1155,1179,1200,1219,1235,1249,1261
#aimdy:
	DATA 1280,1279,1275,1268,1259,1248,1234,1217
	DATA 1198,1176,1152,1126,1098,1067,1034,999
	DATA 962,923,882,839,795,749,701,652
	DATA 602,551,498,445,390,335,279,222

	' Drop score. The i-th dropped bubble is worth 20 * 2^(i-1) POINTS, which is
	' exactly 2^i UNITS OF 10. Capped at i=17 -> 131072 units = 1,310,720 points,
	' the documented arcade maximum for one drop.
	' Stored as 6 BCD digits, most significant first, so adding into the score is
	' a digit-wise add with carry -- no division, no 32-bit arithmetic, no overflow.
dropbcd:
	DATA BYTE $00,$00,$00,$00,$00,$02	'  1 bubbles:      2 units = 20 pts
	DATA BYTE $00,$00,$00,$00,$00,$04	'  2 bubbles:      4 units = 40 pts
	DATA BYTE $00,$00,$00,$00,$00,$08	'  3 bubbles:      8 units = 80 pts
	DATA BYTE $00,$00,$00,$00,$01,$06	'  4 bubbles:     16 units = 160 pts
	DATA BYTE $00,$00,$00,$00,$03,$02	'  5 bubbles:     32 units = 320 pts
	DATA BYTE $00,$00,$00,$00,$06,$04	'  6 bubbles:     64 units = 640 pts
	DATA BYTE $00,$00,$00,$01,$02,$08	'  7 bubbles:    128 units = 1,280 pts
	DATA BYTE $00,$00,$00,$02,$05,$06	'  8 bubbles:    256 units = 2,560 pts
	DATA BYTE $00,$00,$00,$05,$01,$02	'  9 bubbles:    512 units = 5,120 pts
	DATA BYTE $00,$00,$01,$00,$02,$04	' 10 bubbles:   1024 units = 10,240 pts
	DATA BYTE $00,$00,$02,$00,$04,$08	' 11 bubbles:   2048 units = 20,480 pts
	DATA BYTE $00,$00,$04,$00,$09,$06	' 12 bubbles:   4096 units = 40,960 pts
	DATA BYTE $00,$00,$08,$01,$09,$02	' 13 bubbles:   8192 units = 81,920 pts
	DATA BYTE $00,$01,$06,$03,$08,$04	' 14 bubbles:  16384 units = 163,840 pts
	DATA BYTE $00,$03,$02,$07,$06,$08	' 15 bubbles:  32768 units = 327,680 pts
	DATA BYTE $00,$06,$05,$05,$03,$06	' 16 bubbles:  65536 units = 655,360 pts
	DATA BYTE $01,$03,$01,$00,$07,$02	' 17 bubbles: 131072 units = 1,310,720 pts

