	' BUST-A-BOBBLE victory-screen juggling path -- GENERATED by
	' assets/genjuggle.py. Do not edit; change the shape there and regenerate.
	'
	' 64 steps around one closed loop. Ball i is at step (t + 8*i) AND 63, so
	' all eight balls share this one table and one counter.
	'
	' Ellipse rx=68 ry=44 about (128,92), speed warp 0.0 -- fast across the
	' bottom, slow over the top, so the bottom of the loop (the only part that
	' shares scanlines with the creature and his arms) holds one ball at a time.
	'
	' VERIFIED: worst case 4 sprites on any scanline, of the 4 the TMS9918 will
	' draw, counting all 8 balls + body + 2 arms, over every phase. The 5th
	' sprite on a line is silently dropped, so this is a correctness property,
	' not a nicety. genjuggle.py re-proves it on every run.
	'
	' These are SPRITE coordinates (y reads one low on this VDP), top-left of
	' each 16x16 ball.

jug_x:
	DATA BYTE 120,127,133,140,146,152,158,163
	DATA BYTE 168,173,177,180,183,185,187,188
	DATA BYTE 188,188,187,185,183,180,177,173
	DATA BYTE 168,163,158,152,146,140,133,127
	DATA BYTE 120,113,107,100, 94, 88, 82, 77
	DATA BYTE  72, 67, 63, 60, 57, 55, 53, 52
	DATA BYTE  52, 52, 53, 55, 57, 60, 63, 67
	DATA BYTE  72, 77, 82, 88, 94,100,107,113

jug_y:
	DATA BYTE  40, 40, 41, 42, 43, 45, 47, 50
	DATA BYTE  53, 56, 60, 63, 67, 71, 75, 80
	DATA BYTE  84, 88, 93, 97,101,105,108,112
	DATA BYTE 115,118,121,123,125,126,127,128
	DATA BYTE 128,128,127,126,125,123,121,118
	DATA BYTE 115,112,108,105,101, 97, 93, 88
	DATA BYTE  84, 80, 75, 71, 67, 63, 60, 56
	DATA BYTE  53, 50, 47, 45, 43, 42, 41, 40
