#!/usr/bin/env python3
"""Generate src/music.bas from the New Rally-X MIDI.

Reads assets/newrallyx.mid directly, so the tune is EXACT rather than
transcribed by eye. Two earlier attempts are worth remembering:

  * reading pitches off a rendered score image -- the noteheads are a few
    pixels tall and it came out wrong;
  * writing an original 12-bar blues -- the melody's blue notes ground
    against a walking bass playing the natural third, and two bare square
    waves a semitone apart just sound sour.

The MIDI removes both problems: the notes are the notes.

WHAT THE FILE CONTAINS (see midiscan.py): format 1, 960 ticks/quarter,
151 BPM. Track 1 is the melody (E4..A5), track 2 the bass (D2..A3);
tracks 3 and 4 duplicate them on other channels and are ignored.

GRID: SIXTEENTHS. The bass is pure eighths, but the MELODY has twelve
sixteenth-note pairs -- runs where two notes share one eighth. An eighth
grid silently swallowed the second of each pair, which is why the fast
figures "did not get there". One step is a sixteenth: 60/151/4 = 0.0993 s
= 6 frames, so MUSTICK is 6 and a bar is 16 steps.

That makes the song 336 steps, which is past what a byte holds -- the
player position has to be a 16-bit variable. It was not, and 288 steps
silently wrapped to 32 once before.

THE BASS HAS TO COME UP AN OCTAVE. The SN76489's tone divider is 10 bits,
which puts its floor at about 109 Hz; the MIDI bass goes down to D2 (73 Hz)
and would alias to a wrong pitch rather than simply being quiet. The whole
bass line is transposed up 12 semitones, which keeps every interval intact.
"""
import os
import struct

HERE = os.path.dirname(os.path.abspath(__file__))
CLOCK = 3579545.0
MIDI = os.path.join(HERE, "newrallyx.mid")

MEL_TRACK, BASS_TRACK = 1, 2
BASS_OCTAVE_UP = 12          # see module docstring: chip floor is ~109 Hz
STEPS_PER_BEAT = 4           # sixteenths: the melody needs them


# ----------------------------------------------------------- MIDI reading
def read_midi(path):
    d = open(path, "rb").read()

    def vlq(i):
        v = 0
        while True:
            b = d[i]; i += 1
            v = (v << 7) | (b & 0x7F)
            if not (b & 0x80):
                return v, i

    assert d[:4] == b"MThd", "not a MIDI file"
    hlen, fmt, ntrk, div = struct.unpack(">IHHH", d[4:14])
    i = 8 + hlen
    tracks = []
    for _ in range(ntrk):
        assert d[i:i + 4] == b"MTrk"
        tlen = struct.unpack(">I", d[i + 4:i + 8])[0]
        end, j, tick, status = i + 8 + tlen, i + 8, 0, 0
        notes, live = [], {}
        while j < end:
            dt, j = vlq(j)
            tick += dt
            if d[j] & 0x80:
                status = d[j]; j += 1
            ev = status & 0xF0
            if status == 0xFF:
                j += 1
                ln, j = vlq(j)
                j += ln
            elif status in (0xF0, 0xF7):
                ln, j = vlq(j)
                j += ln
            elif ev in (0x80, 0x90):
                p, v = d[j], d[j + 1]; j += 2
                if ev == 0x90 and v > 0:
                    live.setdefault(p, []).append(tick)
                elif live.get(p):
                    notes.append((live[p].pop(0), tick, p))
            elif ev in (0xA0, 0xB0, 0xE0):
                j += 2
            elif ev in (0xC0, 0xD0):
                j += 1
            else:
                j += 1
        tracks.append(sorted(notes))
        i = end
    return div, tracks


div, tracks = read_midi(MIDI)
STEP_TICKS = div // STEPS_PER_BEAT          # ticks per step (a sixteenth)

mel_notes = [(t0, t1, p) for t0, t1, p in tracks[MEL_TRACK]]
bass_notes = [(t0, t1, p + BASS_OCTAVE_UP) for t0, t1, p in tracks[BASS_TRACK]]

last = max(max(n[1] for n in mel_notes), max(n[1] for n in bass_notes))
STEPS = int(round(last / float(STEP_TICKS)))
STEPS -= STEPS % 16                         # whole bars only


def lay(notes, steps):
    """Quantise to the sixteenth grid. A slot holds a pitch where a note
    STARTS and 0 elsewhere, because index 0 means 'write nothing' -- the
    note already sounding keeps ringing, which is how held notes work."""
    grid = [0] * steps
    for t0, t1, p in notes:
        s = int(round(t0 / float(STEP_TICKS)))
        if 0 <= s < steps:
            grid[s] = max(grid[s], p)       # a chord collapses to its top note
    return grid


mel = lay(mel_notes, STEPS)
bass = lay(bass_notes, STEPS)

NAMES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]


def nm(p):
    return "%s%d" % (NAMES[p % 12], p // 12 - 1)


def freq(p):
    return 440.0 * (2.0 ** ((p - 69) / 12.0))


used = sorted({p for p in mel + bass if p})
IDX = {p: i + 1 for i, p in enumerate(used)}
lo = min(used)
assert CLOCK / (32.0 * freq(lo)) <= 1023, \
    "%s (%.1f Hz) is under the chip floor even after transposing" % (nm(lo), freq(lo))

lines = ["\t' GENERATED by assets/genmusic.py from assets/newrallyx.mid.",
         "\t' New Rally-X BGM, 151 BPM. One step is a SIXTEENTH = 6 frames",
         "\t' (MUSTICK): the bass is eighths but the melody has sixteenth runs,",
         "\t' and an eighth grid swallowed the second note of every pair.",
         "\t' %d steps = %d bars. Position must be 16-BIT -- this is past 255."
         % (STEPS, STEPS // 16),
         "\t' Melody is MIDI track 1, bass track 2 transposed UP AN OCTAVE:",
         "\t' the original bass reaches D2 (73 Hz) and the SN76489's 10-bit",
         "\t' divider bottoms out near 109 Hz, so it would alias rather than",
         "\t' just be quiet. Every interval is preserved.",
         ""]
lines.append("mus_freq:")
lines.append("\tDATA BYTE $00,$00\t' 0 = sustain (writes nothing)")
for p in used:
    d = int(round(CLOCK / (32.0 * freq(p))))
    lines.append("\tDATA BYTE $%02X,$%02X\t' %-4s %6.1f Hz" % (d >> 8, d & 0xFF, nm(p), freq(p)))
lines.append("mus_song:")
for i in range(STEPS):
    if i % 16 == 0:
        lines.append("\t' bar %d" % (i // 16 + 1))
    lines.append("\tDATA BYTE %d,%d" % (IDX.get(mel[i], 0), IDX.get(bass[i], 0)))

open(os.path.join(HERE, "..", "src", "music.bas"), "w").write("\n".join(lines) + "\n")

print("melody %d notes %s..%s / bass %d notes %s..%s (transposed +%d)"
      % (len(mel_notes), nm(min(p for _, _, p in mel_notes)), nm(max(p for _, _, p in mel_notes)),
         len(bass_notes), nm(min(p for _, _, p in bass_notes)), nm(max(p for _, _, p in bass_notes)),
         BASS_OCTAVE_UP))
print("%d distinct pitches, %s (%.1f Hz) lowest" % (len(used), nm(lo), freq(lo)))
print("wrote src/music.bas: %d steps = %d bars = %.1f s at 6 frames/step"
      % (STEPS, STEPS // 16, STEPS * 6 / 60.0))
