#!/usr/bin/env python3
"""Generate src/music.bas -- the in-game tune for our own tiny player.

Why not CVBasic's PLAY: its PSG music player writes the volume registers
itself, from envelope tables baked into the shared prologue, so a game
cannot turn it down. `PLAY INSTRUMENT` only carries volume on FM hardware.
The tune has to sit UNDER the engine and the effects, so we drive two
channels ourselves and set the volume explicitly.

Layout emitted:
  mus_freq   16-bit SN76489 dividers, hi byte then lo, one per note index.
             Index 0 is a rest.
  mus_song   two bytes per step: melody note index, bass note index.
             STEPS steps at MUS_TICKS frames each.

SN76489 divider: N = 3579545 / (32 * f). Smaller N = higher pitch.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
CLOCK = 3579545.0

# note name -> frequency, two octaves of melody plus a bass octave
BASE = {"C": 261.63, "D": 293.66, "E": 329.63, "F": 349.23,
        "G": 392.00, "A": 440.00, "B": 493.88}


def freq(name):
    letter, octv = name[0], int(name[1])
    return BASE[letter] * (2.0 ** (octv - 4))


# every note the song uses, index 1..n (0 = rest)
NOTES = ["C3", "D3", "E3", "F3", "G3", "A3", "B3",
         "C4", "D4", "E4", "F4", "G4", "A4", "B4",
         "C5", "D5", "E5", "F5", "G5", "A5", "B5", "C6"]
IDX = {n: i + 1 for i, n in enumerate(NOTES)}
IDX["-"] = 0

# --- the song ---------------------------------------------------------------
# Four 16-step phrases -- A, B, A', C -- so it runs about ten seconds before
# it comes round again, rather than the four-second loop it replaces.
A = ["C5", "-", "E5", "-", "G5", "-", "E5", "-",
     "F5", "-", "A5", "-", "G5", "-", "E5", "-"]
B = ["D5", "-", "F5", "-", "A5", "-", "F5", "-",
     "G5", "-", "B5", "-", "C6", "-", "B5", "-"]
A2 = ["C5", "-", "E5", "-", "G5", "-", "C6", "-",
      "B5", "-", "G5", "-", "E5", "-", "C5", "-"]
C = ["A4", "-", "C5", "-", "E5", "-", "C5", "-",
     "F5", "-", "E5", "-", "D5", "-", "G4", "-"]
MELODY = A + B + A2 + C

# walking bass, one note per four steps
def bass(seq):
    out = []
    for n in seq:
        out += [n, "-", "-", "-"]
    return out

BASS = (bass(["C3", "F3", "G3", "C3"]) + bass(["D3", "G3", "C4", "G3"]) +
        bass(["C3", "E3", "G3", "C3"]) + bass(["F3", "C3", "G3", "G3"]))

assert len(MELODY) == len(BASS) == 64, (len(MELODY), len(BASS))

lines = ["\t' GENERATED by assets/genmusic.py -- do not hand-edit.",
         "\t' In-game tune for the built-in player (see mus_tick in RALLYX.bas).",
         "\t' MUST live in TI bank 0: the player runs every frame while a maze",
         "\t' bank is selected, and bank 0 is the only one always mapped.",
         "",
         "\t' 16-bit SN76489 dividers, hi byte then lo. Index 0 = rest.",
         "mus_freq:",
         "\tDATA BYTE $00,$00\t' 0 = rest"]
for n in NOTES:
    d = int(round(CLOCK / (32.0 * freq(n))))
    assert 1 <= d <= 1023, (n, d)
    lines.append("\tDATA BYTE $%02X,$%02X\t' %s" % (d >> 8, d & 0xFF, n))

lines += ["", "\t' two bytes per step: melody index, bass index", "mus_song:"]
for i in range(len(MELODY)):
    lines.append("\tDATA BYTE %d,%d" % (IDX[MELODY[i]], IDX[BASS[i]]))

open(os.path.join(HERE, "..", "src", "music.bas"), "w").write("\n".join(lines) + "\n")
print("wrote src/music.bas: %d notes, %d steps" % (len(NOTES), len(MELODY)))
