#!/usr/bin/env python3
"""Generate src/music.bas -- the in-game tune for our own tiny player.

Why not CVBasic's PLAY: its PSG music player writes the volume registers
itself, from envelope tables baked into the shared prologue, so a game
cannot turn it down. `PLAY INSTRUMENT` only carries volume on FM hardware.
The tune has to sit UNDER the engine and the effects, so we drive two
channels ourselves and set the volume explicitly.

Layout emitted:
  mus_freq   16-bit SN76489 dividers, hi byte then lo, one per note index.
             Index 0 is a rest.
  mus_song   two bytes per step: melody note index, bass note index.
             STEPS steps at MUS_TICKS frames each.

SN76489 divider: N = 3579545 / (32 * f). Smaller N = higher pitch.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
CLOCK = 3579545.0

# note name -> frequency, two octaves of melody plus a bass octave
BASE = {"C": 261.63, "D": 293.66, "E": 329.63, "F": 349.23,
        "G": 392.00, "A": 440.00, "B": 493.88}


def freq(name):
    letter, octv = name[0], int(name[1])
    return BASE[letter] * (2.0 ** (octv - 4))


# every note the song uses, index 1..n (0 = rest)
NOTES = ["C3", "D3", "E3", "F3", "G3", "A3", "B3",
         "C4", "D4", "E4", "F4", "G4", "A4", "B4",
         "C5", "D5", "E5", "F5", "G5", "A5", "B5",
         "C6", "D6"]
IDX = {n: i + 1 for i, n in enumerate(NOTES)}
IDX["-"] = 0

# --- the song ---------------------------------------------------------------
# PHRASE A is the ORIGINAL tune, restored note for note: a C-F-G-C arpeggio
# run, one note every two steps with the second step sustaining. An earlier
# attempt threw this away for four contrasting sections and they were worse
# -- this keeps the tune and ANSWERS it instead.
#
# PHRASE B is a new continuation in the SAME arpeggio style, dropping to the
# relative minor and climbing back to resolve on C. Same rhythm, same shape,
# so it reads as more of the tune rather than a different one.
#
# The bass plays at the written pitch, NOT two octaves down as the original
# asked: the SN76489 bottoms out around 110 Hz, so those notes were silent
# and the tune was effectively melody-only.
A_MEL = ["C5", "E5", "G5", "E5", "F5", "A5", "C6", "A5",
         "G5", "B5", "D6", "B5", "C6", "G5", "E5", "C5"]
A_BASS = ["C4", "-", "G4", "-", "F4", "-", "C5", "-",
          "G4", "-", "D5", "-", "C5", "G4", "E4", "C4"]

B_MEL = ["A4", "C5", "E5", "C5", "D5", "F5", "A5", "F5",
         "G4", "B4", "D5", "B4", "C5", "E5", "G5", "C6"]
B_BASS = ["A3", "-", "E4", "-", "D4", "-", "A4", "-",
          "G3", "-", "D4", "-", "C4", "E4", "G4", "C5"]


def spread(seq):
    """one note every two steps; the second step sustains (a rest writes
    nothing, so the note simply keeps ringing)."""
    out = []
    for n in seq:
        out += [n, "-"]
    return out


MELODY = spread(A_MEL) + spread(B_MEL)
BASS = spread(A_BASS) + spread(B_BASS)

assert len(MELODY) == len(BASS) == 64, (len(MELODY), len(BASS))

lines = ["\t' GENERATED by assets/genmusic.py -- do not hand-edit.",
         "\t' In-game tune for the built-in player (see mus_tick in RALLYX.bas).",
         "\t' MUST live in TI bank 0: the player runs every frame while a maze",
         "\t' bank is selected, and bank 0 is the only one always mapped.",
         "",
         "\t' 16-bit SN76489 dividers, hi byte then lo. Index 0 = rest.",
         "mus_freq:",
         "\tDATA BYTE $00,$00\t' 0 = rest"]
for n in NOTES:
    d = int(round(CLOCK / (32.0 * freq(n))))
    assert 1 <= d <= 1023, (n, d)
    lines.append("\tDATA BYTE $%02X,$%02X\t' %s" % (d >> 8, d & 0xFF, n))

lines += ["", "\t' two bytes per step: melody index, bass index", "mus_song:"]
for i in range(len(MELODY)):
    lines.append("\tDATA BYTE %d,%d" % (IDX[MELODY[i]], IDX[BASS[i]]))

open(os.path.join(HERE, "..", "src", "music.bas"), "w").write("\n".join(lines) + "\n")
print("wrote src/music.bas: %d notes, %d steps" % (len(NOTES), len(MELODY)))
