#!/usr/bin/env python3
"""Bake maze1.txt into src/map1.bas for RaltiX (CVBasic).

Emits:
  wallpat: 16 wall-block char patterns (codes 96-111), neighbor-edged --
           variant bit set = wall/tree neighbor on that side (N=1 E=2 S=4 W=8);
           road-facing sides get a 1-px tan inset for the arcade block look.
  wallcol: matching per-row colors (green on tan) for DEFINE COLOR 96,16.
  map1:    34x58 bordered char-code map (tree ring + walls + road),
           row-major, stride 34, for SCREEN blits and PEEK collision.

Char codes must match DESIGN.md section 4: walls 96-111, tree 112, road 113.
Run from assets/: C:\\cygwin64\\bin\\python3.9.exe genmap.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "src", "map1.bas")

rows = [l.rstrip("\n") for l in open(os.path.join(HERE, "maze1.txt")).readlines()[:56]]
assert len(rows) == 56 and all(len(r) == 32 for r in rows), "maze1.txt must be 56 rows x 32 cols"

WALL0, TREE, ROAD = 96, 112, 113
COLS, ROWS = 34, 58  # bordered

def solid(r, c):
    """True if bordered cell (r,c) is wall or tree (border ring counts)."""
    if r <= 0 or r >= ROWS - 1 or c <= 0 or c >= COLS - 1:
        return True
    return rows[r - 1][c - 1] == "#"

# --- wall patterns: 16 variants -------------------------------------------
def wall_pattern(idx):
    n, e, s, w = idx & 1, idx & 2, idx & 4, idx & 8
    pat = []
    for row in range(8):
        bits = 0xFF
        if not w:
            bits &= 0x7F
        if not e:
            bits &= 0xFE
        if not n and row == 0:
            bits = 0
        if not s and row == 7:
            bits = 0
        pat.append(bits)
    return pat

# --- map bake --------------------------------------------------------------
grid = []
for r in range(ROWS):
    line = []
    for c in range(COLS):
        if r == 0 or r == ROWS - 1 or c == 0 or c == COLS - 1:
            line.append(TREE)
        elif rows[r - 1][c - 1] == "#":
            idx = 0
            if solid(r - 1, c): idx |= 1
            if solid(r, c + 1): idx |= 2
            if solid(r + 1, c): idx |= 4
            if solid(r, c - 1): idx |= 8
            line.append(WALL0 + idx)
        else:
            line.append(ROAD)
    grid.append(line)

def data_byte_lines(vals, per=17, indent="\t"):
    out = []
    for i in range(0, len(vals), per):
        out.append(indent + "DATA BYTE " + ",".join("$%02X" % v for v in vals[i:i + per]))
    return out

lines = []
lines.append("\t' GENERATED by assets/genmap.py from assets/maze1.txt -- do not hand-edit.")
lines.append("\t' Wall chars 96-111 (16 neighbor variants), tree 112, road 113 (DESIGN.md 4).")
lines.append("wallpat:")
for idx in range(16):
    p = wall_pattern(idx)
    lines.append("\tDATA BYTE " + ",".join("$%02X" % b for b in p) + "\t' variant %d" % idx)
lines.append("wallcol:")
lines.append("\t' green (2) on tan (10) every row, all 16 variants")
for idx in range(16):
    lines.append("\tDATA BYTE $2A,$2A,$2A,$2A,$2A,$2A,$2A,$2A")
lines.append("radar_zero:")
lines.append("\t' 112 x 8 zero pattern rows: blank radar canvas (chars 144-255)")
for i in range(112):
    lines.append("\tDATA BYTE $00,$00,$00,$00,$00,$00,$00,$00")
lines.append("radar_base:")
lines.append("\t' 112 x 8 base colors: white dots on dark blue")
for i in range(112):
    lines.append("\tDATA BYTE $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4")
lines.append("map1:")
lines.append("\t' 58 rows x 34 cols, row-major, stride 34 (tree ring included)")
for r in range(ROWS):
    lines.extend(data_byte_lines(grid[r]))
open(SRC, "w").write("\n".join(lines) + "\n")
print("wrote", SRC, "-", ROWS, "x", COLS, "map,", 16, "wall variants")
