	' GENERATED by assets/genbang.py -- do not hand-edit.
	' chars 16-27 BANG burst (4x3). Popup box = chars 140-143, composed
	' in RAM at pickup from mini_font (see minifont.bas, TI bank 0).
	' NOTHING may land on char 32 (SPACE) -- redefining it wrecks every
	' blank cell on the screen.

bang_pat:
	DATA BYTE $01,$01,$31,$39,$1D,$0F,$C4,$AA
	DATA BYTE $80,$80,$8C,$9C,$B8,$F0,$A6,$E8
	DATA BYTE $CE,$AA,$CA,$1D,$39,$31,$01,$01
	DATA BYTE $EA,$EA,$A6,$B8,$9C,$8C,$80,$80
	DATA BYTE $01,$03,$73,$3B,$3F,$1F,$C4,$AA
	DATA BYTE $80,$84,$9C,$BC,$F8,$F0,$A6,$E8
	DATA BYTE $CE,$AA,$CA,$1F,$3D,$39,$21,$01
	DATA BYTE $EA,$EA,$A6,$FC,$DC,$CE,$C0,$80

bang_col:
	DATA BYTE $BA,$BA,$BA,$BA,$BA,$BA,$1B,$1B
	DATA BYTE $BA,$BA,$BA,$BA,$BA,$BA,$1B,$1B
	DATA BYTE $1B,$1B,$1B,$BA,$BA,$BA,$BA,$BA
	DATA BYTE $1B,$1B,$1B,$BA,$BA,$BA,$BA,$BA
	DATA BYTE $BA,$BA,$BA,$BA,$BA,$BA,$1B,$1B
	DATA BYTE $BA,$BA,$BA,$BA,$BA,$BA,$1B,$1B
	DATA BYTE $1B,$1B,$1B,$BA,$BA,$BA,$BA,$BA
	DATA BYTE $1B,$1B,$1B,$BA,$BA,$BA,$BA,$BA

pop_col:
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
