	' GENERATED by assets/genbang.py -- do not hand-edit.
	' chars 16-27 BANG burst (4x3). Popup box = chars 140-143, composed
	' in RAM at pickup from mini_font (see minifont.bas, TI bank 0).
	' NOTHING may land on char 32 (SPACE) -- redefining it wrecks every
	' blank cell on the screen.

bang_pat:
	DATA BYTE $00,$00,$00,$00,$07,$07,$03,$01
	DATA BYTE $00,$01,$03,$03,$83,$C3,$F3,$FB
	DATA BYTE $00,$80,$C0,$C0,$C1,$C3,$CF,$DF
	DATA BYTE $00,$00,$00,$00,$E0,$E0,$C0,$80
	DATA BYTE $3C,$36,$36,$3C,$36,$36,$3C,$00
	DATA BYTE $30,$6C,$6C,$7C,$6C,$6C,$6C,$00
	DATA BYTE $D8,$F9,$F9,$F9,$D9,$D9,$D8,$00
	DATA BYTE $E0,$80,$80,$B0,$B0,$B0,$E0,$00
	DATA BYTE $01,$03,$07,$07,$00,$00,$00,$00
	DATA BYTE $FB,$F3,$C3,$83,$03,$03,$01,$00
	DATA BYTE $DF,$CF,$C3,$C1,$C0,$C0,$80,$00
	DATA BYTE $80,$C0,$E0,$E0,$00,$00,$00,$00

bang_col:
	DATA BYTE $BA,$BA,$BA,$BA,$BA,$BA,$BA,$BA
	DATA BYTE $BA,$BA,$BA,$BA,$BA,$BA,$BA,$BA
	DATA BYTE $BA,$BA,$BA,$BA,$BA,$BA,$BA,$BA
	DATA BYTE $BA,$BA,$BA,$BA,$BA,$BA,$BA,$BA
	DATA BYTE $1B,$1B,$1B,$1B,$1B,$1B,$1B,$1B
	DATA BYTE $1B,$1B,$1B,$1B,$1B,$1B,$1B,$1B
	DATA BYTE $1B,$1B,$1B,$1B,$1B,$1B,$1B,$1B
	DATA BYTE $1B,$1B,$1B,$1B,$1B,$1B,$1B,$1B
	DATA BYTE $BA,$BA,$BA,$BA,$BA,$BA,$BA,$BA
	DATA BYTE $BA,$BA,$BA,$BA,$BA,$BA,$BA,$BA
	DATA BYTE $BA,$BA,$BA,$BA,$BA,$BA,$BA,$BA
	DATA BYTE $BA,$BA,$BA,$BA,$BA,$BA,$BA,$BA

pop_col:
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
