	' GENERATED by assets/genbang.py -- do not hand-edit.
	' 3x5 popup font, glyphs 0-9 then 'x'. MUST stay in TI bank 0:
	' gameplay PEEKs it while another bank is selected.

mini_font:
	DATA BYTE $E0,$A0,$A0,$A0,$E0
	DATA BYTE $40,$C0,$40,$40,$E0
	DATA BYTE $E0,$20,$E0,$80,$E0
	DATA BYTE $E0,$20,$E0,$20,$E0
	DATA BYTE $A0,$A0,$E0,$20,$20
	DATA BYTE $E0,$80,$E0,$20,$E0
	DATA BYTE $E0,$80,$E0,$A0,$E0
	DATA BYTE $E0,$20,$20,$20,$20
	DATA BYTE $E0,$A0,$E0,$A0,$E0
	DATA BYTE $E0,$A0,$E0,$20,$E0
	DATA BYTE $00,$A0,$40,$A0,$00
