#!/usr/bin/env python3
"""
PUZZLE BOBBLE - generates src/art.bas: bubble patterns, colours, sprite defs,
the aim table, and the drop-score BCD table.

Everything here is derived, not hand-typed, so the numbers in the ROM and the
numbers in assets/prevlevels.py cannot drift apart.

Run:  python3 genart.py
"""

import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "art.bas")

# --- the 16x16 bubble ------------------------------------------------------------------
# Per-pixel-row inset from each side. Rows 0..5 take the LIT shade, 6..15 the BASE shade,
# so every character scan line is one bubble shade on black -- never three colours.
# Same table as prevlevels.py: change both together.
INSET = [4, 3, 2, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 2, 3, 4]
LITROWS = 6

# bubble colour k (1..8) -> (base, lit) TMS9918 colour numbers. DESIGN.md section 4.
BUBBLE = [(8, 9), (12, 3), (4, 5), (10, 11), (7, 15), (13, 15), (14, 15), (6, 9)]
WELLBG = 1                      # black behind every bubble

NAIM = 32                       # aim steps, 0 = straight up .. 31 = 80 degrees
AIMSPD = 5.0                    # pixels per frame
AIMMAX = 80.0                   # degrees from vertical at full deflection
NDROP = 17                      # drop-score table entries (capped at 17, per the arcade)


def rowbits(y):
    """(left byte, right byte) of the sphere at pixel row y."""
    lo, hi = INSET[y], 16 - INSET[y]        # pixels lo..hi-1 are set
    left = right = 0
    for x in range(lo, hi):
        if x < 8:
            left |= 1 << (7 - x)
        else:
            right |= 1 << (15 - x)
    return left, right


def hexrow(vals):
    return ",".join("$%02X" % v for v in vals)


def main():
    L = [rowbits(y)[0] for y in range(16)]
    R = [rowbits(y)[1] for y in range(16)]

    out = []
    w = out.append

    w("\t' PUZZLE BOBBLE art + tables -- GENERATED by assets/genart.py")
    w("\t' Do not edit. Regenerate instead.")
    w("")

    # --- character patterns: one 2x2 stamp, shared by all 8 colours -------------------
    w("\t' The 16x16 bubble as four 8x8 characters (TL,TR,BL,BR). ALL EIGHT COLOURS")
    w("\t' SHARE THIS ONE PATTERN -- only DEFINE COLOR differs -- so the game issues")
    w("\t' eight DEFINE CHAR calls against these same 32 bytes instead of storing")
    w("\t' 8 x 32 bytes of identical pixels.")
    w("bub_pat:")
    w("\tDATA BYTE %s\t' TL, rows 0-7" % hexrow(L[0:8]))
    w("\tDATA BYTE %s\t' TR, rows 0-7" % hexrow(R[0:8]))
    w("\tDATA BYTE %s\t' BL, rows 8-15" % hexrow(L[8:16]))
    w("\tDATA BYTE %s\t' BR, rows 8-15" % hexrow(R[8:16]))
    w("")

    # --- character colours: 8 colours x 4 chars x 8 rows ------------------------------
    w("\t' Per-scan-line colours for chars 128..159 (8 colours x TL,TR,BL,BR).")
    w("\t' fg*16+bg; bg is always black. The TOP chars switch from lit to base at")
    w("\t' pixel row %d; the BOTTOM chars are all base." % LITROWS)
    w("bub_col:")
    for k, (base, lit) in enumerate(BUBBLE):
        b = base * 16 + WELLBG
        t = lit * 16 + WELLBG
        top = [t] * LITROWS + [b] * (8 - LITROWS)
        w("\t' colour %d  base=%-2d lit=%-2d" % (k + 1, base, lit))
        w("\tDATA BYTE %s\t' TL" % hexrow(top))
        w("\tDATA BYTE %s\t' TR" % hexrow(top))
        w("\tDATA BYTE %s\t' BL" % hexrow([b] * 8))
        w("\tDATA BYTE %s\t' BR" % hexrow([b] * 8))
    w("")

    # --- sprites ----------------------------------------------------------------------
    # CVBasic 16x16 sprite pattern = 16 bytes left column, then 16 bytes right column.
    w("\t' Flying bubble = TWO overlaid 16x16 sprites so it is pixel-identical to the")
    w("\t' same bubble once it sticks and becomes characters (a sprite is one colour).")
    w("\t' 16 bytes left column then 16 bytes right column -- NOT sequential scan lines.")
    w("spr_cap:\t' lit upper cap, pixel rows 0-%d" % (LITROWS - 1))
    w("\tDATA BYTE %s" % hexrow(L[:LITROWS] + [0] * (16 - LITROWS)))
    w("\tDATA BYTE %s" % hexrow(R[:LITROWS] + [0] * (16 - LITROWS)))
    w("spr_body:\t' base lower body, pixel rows %d-15" % LITROWS)
    w("\tDATA BYTE %s" % hexrow([0] * LITROWS + L[LITROWS:]))
    w("\tDATA BYTE %s" % hexrow([0] * LITROWS + R[LITROWS:]))
    dotl = [0] * 6 + [0x03] * 4 + [0] * 6
    dotr = [0] * 6 + [0xC0] * 4 + [0] * 6
    w("spr_dot:\t' 4x4 aim-guide dot, centred in the 16x16 cell")
    w("\tDATA BYTE %s" % hexrow(dotl))
    w("\tDATA BYTE %s" % hexrow(dotr))
    w("")

    # --- aim table --------------------------------------------------------------------
    w("\t' Aim table: %d steps from vertical to %g degrees, speed %g px/frame, 8.8 fixed" %
      (NAIM, AIMMAX, AIMSPD))
    w("\t' point. BOTH MAGNITUDES ARE POSITIVE -- direction is a separate flag, because")
    w("\t' CVBasic compiles every #var comparison UNSIGNED (a signed velocity would")
    w("\t' silently misbehave at every sign test).")
    dxs, dys = [], []
    for am in range(NAIM):
        th = math.radians(am * AIMMAX / (NAIM - 1))
        dxs.append(int(round(AIMSPD * math.sin(th) * 256)))
        dys.append(int(round(AIMSPD * math.cos(th) * 256)))
    w("#aimdx:")
    for i in range(0, NAIM, 8):
        w("\tDATA %s" % ",".join(str(v) for v in dxs[i:i + 8]))
    w("#aimdy:")
    for i in range(0, NAIM, 8):
        w("\tDATA %s" % ",".join(str(v) for v in dys[i:i + 8]))
    w("")

    # --- drop-score table -------------------------------------------------------------
    # The i-th dropped bubble is worth 20 * 2^(i-1) points = 2^i UNITS OF 10.
    # Capped at i=17 -> 131072 units = 1,310,720 points, the documented arcade maximum.
    w("\t' Drop score. The i-th dropped bubble is worth 20 * 2^(i-1) POINTS, which is")
    w("\t' exactly 2^i UNITS OF 10. Capped at i=%d -> %d units = %s points," %
      (NDROP, 2 ** NDROP, "{:,}".format(2 ** NDROP * 10)))
    w("\t' the documented arcade maximum for one drop.")
    w("\t' Stored as 6 BCD digits, most significant first, so adding into the score is")
    w("\t' a digit-wise add with carry -- no division, no 32-bit arithmetic, no overflow.")
    w("dropbcd:")
    for i in range(1, NDROP + 1):
        u = 2 ** i
        digs = [int(c) for c in "%06d" % u]
        w("\tDATA BYTE %s\t' %2d bubbles: %6d units = %s pts"
          % (hexrow(digs), i, u, "{:,}".format(u * 10)))
    w("")

    outdir = os.path.dirname(os.path.abspath(OUT))
    if not os.path.isdir(outdir):
        os.makedirs(outdir)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")

    total = 32 + 8 * 4 * 8 + 3 * 32 + NAIM * 4 + NDROP * 6
    print("wrote %s" % os.path.normpath(OUT))
    print("  patterns 32 B  colours %d B  sprites %d B  aim %d B  dropbcd %d B  = %d B"
          % (8 * 4 * 8, 3 * 32, NAIM * 4, NDROP * 6, total))
    print("  aim step 0 = (%d,%d)  step 31 = (%d,%d)  [8.8 fixed]"
          % (dxs[0], dys[0], dxs[-1], dys[-1]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
