"""Generate exact factory paddle positions, including three phase-offset tails."""
from pathlib import Path
import argparse
import re

SOURCE = Path(__file__).resolve().parent.parent / 'src/HARDHAT.bas'


def position(phase):
    phase %= 224
    if phase < 80:
        return 104, 64 + phase
    if phase < 112:
        return 104 + phase - 80, 144
    if phase < 192:
        return 136, 144 - (phase - 112)
    return 136 - (phase - 192), 64


def rewrite(source):
    for axis, name in enumerate(('lift_x', 'lift_y')):
        values = [position(p)[axis] for p in range(392)]
        block = name + ':\n\t\' Generated by assets/genmotion.py.\n'
        block += ''.join('\tDATA BYTE ' + ','.join(map(str, values[i:i+16])) + '\n'
                         for i in range(0, len(values), 16))
        source, count = re.subn(r'^' + name + r':\n.*?(?=^\w+:)',
                               lambda _: block, source, flags=re.M | re.S)
        assert count == 1, 'missing motion table ' + name
    return source


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    source = SOURCE.read_text(encoding='utf-8')
    generated = rewrite(source)
    if args.write:
        SOURCE.write_bytes(generated.encode('utf-8'))
        source = generated
    assert source == generated, 'stale motion tables; run genmotion.py --write'
    damaged = source.replace('lift_x:\n', 'lift_x:\n\tDATA BYTE 0\n', 1)
    assert rewrite(damaged) != damaged, 'accepted damaged motion table'
    print('Motion tables: exact 224-step circuit, four phased paddles, even byte counts')
