	' UFO! art -- GENERATED by assets/genart.py. Do not edit; regenerate.
	'
	' Sprites are QUADRANT-ORDERED for the TMS9918: 16 rows of the left half then
	' 16 rows of the right half.
	'
	' Every block is an EVEN number of bytes -- an odd DATA BYTE run leaves the
	' location counter odd and silently misaligns every word table after it
	' (CLAUDE.md 3A).

spr_ship:	' the cruiser -- 6x6, small so the force field owns the cell
	DATA BYTE $00,$00,$00,$00,$00,$03,$07,$06
	DATA BYTE $06,$07,$03,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$C0,$E0,$60
	DATA BYTE $60,$E0,$C0,$00,$00,$00,$00,$00

spr_ring:	' force field, 4 rotation phases -- COMPUTED, see genart.py
	DATA BYTE $01,$01,$30,$30,$00,$00,$00,$C0
	DATA BYTE $C0,$00,$0C,$0C,$30,$30,$01,$01
	DATA BYTE $80,$80,$0C,$0C,$30,$30,$00,$03
	DATA BYTE $03,$00,$00,$00,$0C,$0C,$80,$80
	DATA BYTE $00,$18,$18,$00,$0C,$0C,$C0,$C0
	DATA BYTE $00,$00,$00,$60,$60,$00,$03,$03
	DATA BYTE $C0,$C0,$00,$06,$06,$00,$00,$00
	DATA BYTE $03,$03,$30,$30,$00,$18,$18,$00
	DATA BYTE $00,$0C,$0C,$00,$60,$60,$00,$00
	DATA BYTE $00,$00,$6C,$6C,$00,$0C,$0C,$00
	DATA BYTE $00,$30,$30,$00,$36,$36,$00,$00
	DATA BYTE $00,$00,$06,$06,$00,$30,$30,$00
	DATA BYTE $03,$03,$00,$60,$6C,$0C,$00,$00
	DATA BYTE $C0,$C0,$00,$00,$00,$18,$18,$00
	DATA BYTE $00,$18,$18,$00,$00,$00,$03,$03
	DATA BYTE $00,$00,$30,$36,$06,$00,$C0,$C0

spr_gundot:	' the aiming dot -- always centred; direction lives in the offset table
	DATA BYTE $00,$00,$00,$00,$00,$00,$03,$03
	DATA BYTE $03,$03,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$C0,$C0
	DATA BYTE $C0,$C0,$00,$00,$00,$00,$00,$00

spr_sat:	' satellite: PLUS then CROSS -- the original's own fake-rotation trick
	DATA BYTE $00,$00,$00,$01,$01,$01,$01,$1F
	DATA BYTE $1F,$01,$01,$01,$01,$00,$00,$00
	DATA BYTE $00,$00,$00,$80,$80,$80,$80,$F8
	DATA BYTE $F8,$80,$80,$80,$80,$00,$00,$00
	DATA BYTE $00,$00,$00,$18,$0C,$06,$03,$01
	DATA BYTE $01,$03,$06,$0C,$18,$00,$00,$00
	DATA BYTE $00,$00,$00,$18,$30,$60,$C0,$80
	DATA BYTE $80,$C0,$60,$30,$18,$00,$00,$00

spr_ufo:	' Light-speed Starship, 2 frames
	DATA BYTE $00,$00,$00,$00,$03,$07,$3F,$7F
	DATA BYTE $66,$3F,$0C,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$C0,$E0,$FC,$FE
	DATA BYTE $66,$FC,$30,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$03,$07,$3F,$7F
	DATA BYTE $4C,$3F,$18,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$C0,$E0,$FC,$FE
	DATA BYTE $CF,$FC,$18,$00,$00,$00,$00,$00

spr_laser:	' player laser bolt
	DATA BYTE $00,$00,$00,$00,$00,$00,$01,$03
	DATA BYTE $03,$01,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$80,$C0
	DATA BYTE $C0,$80,$00,$00,$00,$00,$00,$00

spr_missile:	' enemy missile -- smaller than the bolt
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$01
	DATA BYTE $01,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$80
	DATA BYTE $80,$00,$00,$00,$00,$00,$00,$00

spr_boom:	' explosion, 3 frames -- shared by every death
	DATA BYTE $00,$00,$00,$00,$00,$02,$01,$03
	DATA BYTE $03,$01,$02,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$40,$80,$C0
	DATA BYTE $C0,$80,$40,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$04,$02,$0D,$07,$1F
	DATA BYTE $1F,$07,$0D,$02,$04,$00,$00,$00
	DATA BYTE $00,$00,$00,$20,$40,$B0,$E0,$F8
	DATA BYTE $F8,$E0,$B0,$40,$20,$00,$00,$00
	DATA BYTE $00,$08,$04,$22,$1A,$05,$30,$08
	DATA BYTE $08,$30,$05,$1A,$22,$04,$08,$00
	DATA BYTE $00,$10,$20,$44,$58,$A0,$0C,$10
	DATA BYTE $10,$0C,$A0,$58,$44,$20,$10,$00

chr_stars:	' starfield: small, medium, large -- static characters, free per frame
	DATA BYTE $00,$00,$00,$10,$00,$00,$00,$00
	DATA BYTE $00,$00,$10,$38,$10,$00,$00,$00
	DATA BYTE $00,$10,$10,$7C,$10,$10,$00,$00

