#!/usr/bin/env python3
"""UFO! art generator -- art in, src/art.bas out.

Sprites are 16x16 and the TMS9918 stores them QUADRANT-ORDERED: all 16 rows of
the LEFT half, then all 16 rows of the RIGHT half. Reading a 16-wide bitmap as
32 sequential rows produces garbage that still assembles, so the art lives here
in readable form and this file does the interleave once, correctly.

Two kinds of art live here, deliberately:

  * SHAPES are ASCII, because a saucer or a plus sign is something you draw.
  * THE FORCE-FIELD RING IS COMPUTED, because it is eight dots on a circle at
    four rotation phases -- thirty-two positions that have to stay evenly
    spaced and concentric. Placed by eye they wobble, and a wobbling ring reads
    as a rendering bug rather than as a shimmer.

Every emitted DATA BYTE block is padded to an EVEN length: an odd-length byte
run leaves the assembler's location counter odd and silently misaligns every
word table after it (CLAUDE.md 3A).

Run:  python3 genart.py      writes ../src/art.bas
"""

import math
import os

# ------------------------------------------------------------------ geometry
#
# All of these are in 16x16 sprite-cell pixels, measured from the cell's
# top-left, with the cell centre at (7.5, 7.5).
#
# The three radii are chosen so nothing ever merges into anything else:
#
#   ship        6x6 blob, x and y spanning 5..10
#   INNER dots  r = 4.6 -- at 90 deg that is x 12, clear of the ship's max x 10
#   OUTER ring  r = 6.8 -- at 90 deg that is x 14, two cells clear of the inner
#
# Squeezing these was tried and does not work: at r = 5.0 / 6.3 the inner and
# outer dots land on ADJACENT cells at the compass points and merge into a
# 4-px dash exactly four times per revolution, which looks like a glitch.
R_OUTER = 6.8
R_INNER = 4.6
CENTRE = 7.5

# Eight main dots, and the phase step is 45/4 deg so four phases carry the ring
# through exactly one dot position -- the animation is then seamless in both
# directions and cannot drift.
N_DOTS = 8
N_PHASE = 4

# The "two rapidly circling dots" (Gaming After 40's description of the real
# thing). They orbit at 90 deg per phase against the outer ring's 11.25, so
# they visibly race around inside it -- which is the whole point of them.
N_FAST = 2


def blank():
    return [[0] * 16 for _ in range(16)]


def dot(grid, cx, cy):
    """A 2x2 dot centred as near (cx, cy) as the pixel grid allows.

    1x1 would be more accurate and is invisible at this size; 3x3 merges with
    its neighbours at r = 4.6. 2x2 is the only size that reads as a dot.
    """
    x = int(round(cx - 0.5))
    y = int(round(cy - 0.5))
    for dy in range(2):
        for dx in range(2):
            px, py = x + dx, y + dy
            if 0 <= px < 16 and 0 <= py < 16:
                grid[py][px] = 1


def ring_grid(phase):
    g = blank()
    base = phase * (360.0 / N_DOTS / N_PHASE)      # 11.25 deg per phase
    for k in range(N_DOTS):
        a = math.radians(base + k * (360.0 / N_DOTS))
        dot(g, CENTRE + R_OUTER * math.sin(a), CENTRE - R_OUTER * math.cos(a))
    # +45 so a fast dot NEVER lines up radially with an outer dot. Without it,
    # phase 0 puts both on the vertical axis and the ring reads as a bar with
    # blobs on it rather than as a circle.
    fast = 45.0 + phase * (360.0 / N_PHASE)        # 90 deg per phase
    for k in range(N_FAST):
        a = math.radians(fast + k * (360.0 / N_FAST))
        dot(g, CENTRE + R_INNER * math.sin(a), CENTRE - R_INNER * math.cos(a))
    return g


# --------------------------------------------------------------------- shapes
# 16x16. '.' is transparent, anything else is on.

# THE SHIP IS SMALL ON PURPOSE. It is 6x6 in a 16x16 cell, because the cell
# belongs to the FORCE FIELD -- the ring is the thing the player reads, and a
# ship drawn large enough to fill the cell would leave nowhere for it. The
# Odyssey 2's ship was a handful of pixels for the same reason.
#
# It does not rotate (movement is 8-way and the hull never turns), so it is
# drawn as a compact hull that reads the same from every direction rather than
# as something with a nose.
SHIP = r"""
................
................
................
................
................
......XXXX......
.....XXXXXX.....
.....XX..XX.....
.....XX..XX.....
.....XXXXXX.....
......XXXX......
................
................
................
................
................
"""

# The gun dot: a 4x4 blob at the centre of its own cell. It is a SEPARATE
# sprite pushed to ship_position + (adx, ady) from the 16-entry offset table in
# UFO.bas, so the pattern itself is always centred -- the aim direction lives
# in the offset, never in the art.
GUNDOT = r"""
................
................
................
................
................
................
......XXXX......
......XXXX......
......XXXX......
......XXXX......
................
................
................
................
................
................
"""

# THE SATELLITE, AND THE ORIGINAL'S OWN TRICK.
#
# Averett had no way to rotate a sprite, so he faked it by flipping between the
# console's built-in PLUS and MULTIPLY characters -- the shape appears to spin
# because a plus rotated 45 degrees IS a multiply sign. Reproducing that
# exactly is most of why this reads as UFO! rather than as a generic shooter,
# and it costs 64 bytes.
SAT_PLUS = r"""
................
................
................
.......XX.......
.......XX.......
.......XX.......
.......XX.......
...XXXXXXXXXX...
...XXXXXXXXXX...
.......XX.......
.......XX.......
.......XX.......
.......XX.......
................
................
................
"""

SAT_CROSS = r"""
................
................
................
...XX......XX...
....XX....XX....
.....XX..XX.....
......XXXX......
.......XX.......
.......XX.......
......XXXX......
.....XX..XX.....
....XX....XX....
...XX......XX...
................
................
................
"""

# The Light-speed Starship: a saucer, two frames so its underside lights run.
# Deliberately NOT plus/cross -- this one is a ship, not a satellite, and the
# player has to be able to tell at a glance which of the three is bearing down.
UFO_A = r"""
................
................
................
................
......XXXX......
.....XXXXXX.....
..XXXXXXXXXXXX..
.XXXXXXXXXXXXXX.
.XX..XX..XX..XX.
..XXXXXXXXXXXX..
....XX....XX....
................
................
................
................
................
"""

UFO_B = r"""
................
................
................
................
......XXXX......
.....XXXXXX.....
..XXXXXXXXXXXX..
.XXXXXXXXXXXXXX.
.X..XX..XX..XX X
..XXXXXXXXXXXX..
...XX......XX...
................
................
................
................
................
"""

# A laser bolt: a short bar. It is drawn the same whichever way it travels --
# at 4 px/frame it is only ever on screen for a few frames at a time, and a
# 16-direction set of bolt art would cost 512 bytes to say almost nothing.
LASER = r"""
................
................
................
................
................
................
.......XX.......
......XXXX......
......XXXX......
.......XX.......
................
................
................
................
................
................
"""

# An enemy missile: smaller than the bolt, so incoming and outgoing fire are
# never confused. This one matters -- it is the thing that kills you.
MISSILE = r"""
................
................
................
................
................
................
................
.......XX.......
.......XX.......
................
................
................
................
................
................
................
"""

BOOM_A = r"""
................
................
................
................
................
......X..X......
.......XX.......
......XXXX......
......XXXX......
.......XX.......
......X..X......
................
................
................
................
................
"""

BOOM_B = r"""
................
................
................
.....X....X.....
......X..X......
....XX.XX.XX....
.....XXXXXX.....
...XXXXXXXXXX...
...XXXXXXXXXX...
.....XXXXXX.....
....XX.XX.XX....
......X..X......
.....X....X.....
................
................
................
"""

BOOM_C = r"""
................
....X......X....
.....X....X.....
..X...X..X...X..
...XX.X..X.XX...
.....X.XX.X.....
..XX........XX..
....X......X....
....X......X....
..XX........XX..
.....X.XX.X.....
...XX.X..X.XX...
..X...X..X...X..
.....X....X.....
....X......X....
................
"""

# ---------------------------------------------------------------- characters
# 8x8. The starfield is CHARACTERS, not sprites: painted once and never touched
# again, so it costs nothing per frame. It is also what makes wraparound
# legible -- with nothing fixed to see it against, a ship crossing the seam
# just looks like it teleported for no reason.

# The SPARE-SHIP icon for the HUD -- the same hexagonal hull as the sprite, at
# 6x6 in an 8x8 cell, so a reserve reads as unmistakably the thing you fly.
LIFE_CH = r"""
........
..XXXX..
.XXXXXX.
.XX..XX.
.XX..XX.
.XXXXXX.
..XXXX..
........
"""

STAR_S = r"""
........
........
........
...X....
........
........
........
........
"""

STAR_M = r"""
........
........
...X....
..XXX...
...X....
........
........
........
"""

STAR_L = r"""
........
...X....
...X....
.XXXXX..
...X....
...X....
........
........
"""


def rows(art):
    return [ln for ln in art.strip("\n").split("\n") if ln.strip("\n")]


def bits(line, lo, hi):
    v = 0
    for i in range(lo, hi):
        c = line[i] if i < len(line) else "."
        v = (v << 1) | (0 if c == "." else 1)
    return v


def sprite_bytes(art):
    """32 bytes: 16 rows of the left half, then 16 rows of the right half."""
    r = rows(art)
    assert len(r) == 16, (len(r), r[:2])
    return [bits(ln, 0, 8) for ln in r] + [bits(ln, 8, 16) for ln in r]


def grid_bytes(g):
    """The same quadrant order, from a computed 16x16 grid."""
    def pack(row, lo, hi):
        v = 0
        for i in range(lo, hi):
            v = (v << 1) | row[i]
        return v
    return [pack(r, 0, 8) for r in g] + [pack(r, 8, 16) for r in g]


def char_bytes(art):
    r = rows(art)
    assert len(r) == 8, len(r)
    return [bits(ln, 0, 8) for ln in r]


def emit(fh, label, data, comment):
    fh.write("%s:\t' %s\n" % (label, comment))
    if len(data) % 2:
        data = data + [0]
    for i in range(0, len(data), 8):
        fh.write("\tDATA BYTE " + ",".join("$%02X" % b for b in data[i:i + 8]) + "\n")
    fh.write("\n")


def preview(g):
    return "\n".join("".join("#" if v else "." for v in row) for row in g)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "src", "art.bas")

    with open(out, "w", newline="\n") as fh:
        fh.write("""\t' UFO! art -- GENERATED by assets/genart.py. Do not edit; regenerate.
\t'
\t' Sprites are QUADRANT-ORDERED for the TMS9918: 16 rows of the left half then
\t' 16 rows of the right half.
\t'
\t' Every block is an EVEN number of bytes -- an odd DATA BYTE run leaves the
\t' location counter odd and silently misaligns every word table after it
\t' (CLAUDE.md 3A).

""")
        emit(fh, "spr_ship", sprite_bytes(SHIP),
             "the cruiser -- 6x6, small so the force field owns the cell")

        data = []
        for p in range(N_PHASE):
            data += grid_bytes(ring_grid(p))
        emit(fh, "spr_ring", data,
             "force field, %d rotation phases -- COMPUTED, see genart.py" % N_PHASE)

        emit(fh, "spr_gundot", sprite_bytes(GUNDOT),
             "the aiming dot -- always centred; direction lives in the offset table")

        emit(fh, "spr_sat", sprite_bytes(SAT_PLUS) + sprite_bytes(SAT_CROSS),
             "satellite: PLUS then CROSS -- the original's own fake-rotation trick")

        emit(fh, "spr_ufo", sprite_bytes(UFO_A) + sprite_bytes(UFO_B),
             "Light-speed Starship, 2 frames")

        emit(fh, "spr_laser", sprite_bytes(LASER), "player laser bolt")
        emit(fh, "spr_missile", sprite_bytes(MISSILE), "enemy missile -- smaller than the bolt")

        emit(fh, "spr_boom", sprite_bytes(BOOM_A) + sprite_bytes(BOOM_B) + sprite_bytes(BOOM_C),
             "explosion, 3 frames -- shared by every death")

        emit(fh, "chr_stars", char_bytes(STAR_S) + char_bytes(STAR_M) + char_bytes(STAR_L),
             "starfield: small, medium, large -- static characters, free per frame")

        emit(fh, "chr_life", char_bytes(LIFE_CH),
             "spare-ship icon for the HUD -- SPARES, excluding the one being flown")

    print("wrote %s" % os.path.normpath(out))
    print()
    ship = rows(SHIP)
    grids = [ring_grid(p) for p in range(N_PHASE)]
    print("force field, all %d phases (ship overlaid as 'o'):" % N_PHASE)
    for y in range(16):
        cols = []
        for g in grids:
            line = ""
            for x in range(16):
                if g[y][x]:
                    line += "#"
                elif ship[y][x] != ".":
                    line += "o"
                else:
                    line += "."
            cols.append(line)
        print("   " + "   ".join(cols))
    same = [p for p in range(N_PHASE) if grids[p] == grids[(p + 1) % N_PHASE]]
    print()
    print("identical adjacent phases: %s" % (same if same else "none -- good"))


if __name__ == "__main__":
    main()
