#!/usr/bin/env python3
"""
BUST-A-BOBBLE 1+2 -- merges the two level sets into one 80-level table.

The combined cartridge carries both games, and the simplest way to hold them is
ONE table with the arcade rounds at 1-30 and the expert levels at 31-80. The
alternative -- including levels.bas and levels2.bas side by side -- cannot work:
both files define pb_lay, pb_seq and pb_meta, so the assembler would see each
label twice.

With one table the engine needs no second set of pointers either. A chosen set is
just a BASE (0 or 30) added to the round number, and a COUNT (30 or 50) to know
when the game is won. The HUD still shows round 1..30 or 1..50, because what it
prints is the round within the set, not the index into the table.

Nothing is re-authored and nothing is re-proven: these are the same levels in the
same order, renumbered. The proofs in WINNABILITY.txt and WINNABILITY2.txt still
describe them exactly.

Run:  python3 genboth.py
      python3 genlevels.py --in levels12.txt --out ../src/levels12.bas --levels 80
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ARCADE = os.path.join(HERE, "levels.txt")
EXPERT = os.path.join(HERE, "levels2.txt")
OUT = os.path.join(HERE, "levels12.txt")


def read_levels(path):
    """[(number, [lines])] -- each level's block, verbatim apart from its header."""
    out, cur = [], None
    for raw in open(path, encoding="utf-8"):
        line = raw.rstrip("\n")
        m = re.match(r"\s*LEVEL\s+(\d+)", line)
        if m:
            cur = (int(m.group(1)), [])
            out.append(cur)
            continue
        if cur is None:                     # file header comments
            continue
        if line.strip() or cur[1]:          # keep interior blanks, drop leading ones
            cur[1].append(line)
    # trim trailing blank lines off each block
    for _, body in out:
        while body and not body[-1].strip():
            body.pop()
    return out


def main():
    arcade = read_levels(ARCADE)
    expert = read_levels(EXPERT)
    if len(arcade) != 30 or len(expert) != 50:
        sys.stderr.write("error: expected 30 arcade and 50 expert levels, found "
                         "%d and %d\n" % (len(arcade), len(expert)))
        return 1

    with open(OUT, "w", newline="\n") as fh:
        fh.write("# BUST-A-BOBBLE 1+2 -- the combined 80-level table.\n"
                 "# GENERATED by assets/genboth.py from levels.txt and levels2.txt.\n"
                 "# Do not hand-edit: edit those and regenerate.\n"
                 "#\n"
                 "#   levels  1-30   the 30 arcade rounds, transcribed\n"
                 "#   levels 31-80   the 50 generated expert levels\n"
                 "#\n"
                 "# The engine picks a set with a BASE (0 or 30) and a COUNT (30 or\n"
                 "# 50), so the round shown to the player is still 1..30 or 1..50.\n"
                 "#\n"
                 "# One table because levels.bas and levels2.bas both define pb_lay,\n"
                 "# pb_seq and pb_meta -- including both would define each twice.\n\n")
        n = 0
        for src, label in ((arcade, "arcade"), (expert, "expert")):
            for _, body in src:
                n += 1
                fh.write("LEVEL %d\n" % n)
                fh.write("\n".join(body) + "\n\n")

    print("wrote %s -- %d levels (arcade 1-30, expert 31-%d)"
          % (os.path.normpath(OUT), n, n))
    return 0


if __name__ == "__main__":
    sys.exit(main())
