#!/usr/bin/env python3
"""JOUST art generator -- ASCII art in, src/art.bas out.

Sprites are 16x16 and the TMS9918 stores them QUADRANT-ORDERED: all 16 rows of
the LEFT half, then all 16 rows of the RIGHT half. Reading a 16-wide bitmap as
32 sequential rows produces garbage that still assembles, so the art lives here
as readable ASCII and this file does the interleave once, correctly.

Characters are 8x8, eight bytes each, straightforward.

Every emitted DATA BYTE block is padded to an EVEN length: an odd-length byte run
leaves the assembler's location counter odd and silently misaligns every word
table after it (TRUNCATION.md 1d).

Run:  python3 genart.py      writes ../src/art.bas
"""

import os

# --------------------------------------------------------------------- sprites
# 16x16. '.' is transparent, anything else is on.
#
# THE MOUNT FACES RIGHT, AND IT HAS TO BE OBVIOUS AT 16x16. The first version was
# ambiguous -- its bulk sat on the LEFT with no distinct head -- so a bird moving
# right read as facing left, and every actor in the game looked like it was flying
# backwards. Direction is carried by three things, in order of how much they help:
#
#   1. the HEAD AND BEAK poke out to the RIGHT, past the body, on their own rows
#   2. the TAIL trails to the LEFT, at the widest part of the body
#   3. the legs sit under the body's centre, not centred in the cell
#
# Facing left is the same frame mirrored -- stored twice rather than flipped at
# runtime, because the VDP cannot mirror a sprite.

# THE MOUNT FILLS THE 16x16 CELL, as it should.
#
# Shrinking the figure to 12 and then 14 was buying headroom under the top ledge by
# making the birds smaller, which is paying in the wrong currency: the mounts are
# the thing you look at. The clearance problem was solved properly instead -- every
# island moved DOWN 8 pixels (one character row), which costs nothing and gives the
# top ledge a full 8 px of margin under the ceiling.
#
# Direction has to be unmistakable at this size, and is carried by:
#   1. the HEAD AND BEAK poking RIGHT, past the body, on their own rows
#   2. the TAIL trailing LEFT at the widest part
#   3. legs under the body's centre
#
# The flight frames differ in the WING rows (5-9) so a flap reads as a beat.

PLAYER = {
"up": r"""
.......XX.......
......XXXX......
......XXXX......
.......XX.......
.....XXXXXX.....
....XX.XXXXX....
...XX..XXXXXXX..
..XX...XXXXXXXX.
.XX....XXXXXX...
.......XXXXX....
.....XXXXXXX....
....XXXXXXX.....
.....XX.XX......
....XX...XX.....
...XX.....XX....
..XX.......XX...
""",
"mid": r"""
.......XX.......
......XXXX......
......XXXX......
.......XX.......
.....XXXXXX.....
....XXXXXXXX....
...XXXXXXXXXXX..
..XXXXXXXXXXXXX.
.XXXXXXXXXXXX...
..XXXXXXXXXX....
....XXXXXXX.....
.....XXXXX......
.....XX.XX......
....XX...XX.....
...XX.....XX....
..XX.......XX...
""",
"down": r"""
.......XX.......
......XXXX......
......XXXX......
.......XX.......
.....XXXXXX.....
.....XXXXXXX....
....XXXXXXXXXX..
...XXXXXXXXXXXX.
..XXXXXXXXXXX...
.XX..XXXXXXX....
....XXXXXXX.....
.....XXXXX......
.....XX.XX......
....XX...XX.....
...XX.....XX....
..XX.......XX...
""",
"skid": r"""
.......XX.......
......XXXX......
......XXXX......
.......XX.......
.....XXXXXX.....
....XXXXXXXX....
...XXXXXXXXXXX..
..XXXXXXXXXXXXX.
.XXXXXXXXXXXX...
..XXXXXXXXXX....
....XXXXXXX.....
.....XXXXX......
....XXX..XXX....
...XX......XX...
..XXX......XXX..
................
""",
}

# EGG, CRACKED EGG and the MAN are ONE CHARACTER TALL -- 8 px, not 16. They are
# drawn in the sprite's LOWER half (rows 8-15) so that "feet at y+16" still puts
# them on a surface, and so the same landing arithmetic works for a small actor
# as for a full-size bird. A 16 px egg looked like a boulder next to the mount.

# EGG, CRACKED EGG and the MAN sit in the LOWER part of the cell, ending on row
# 15, so "feet at y+16" puts them on a surface with the same arithmetic a bird uses.
#
# THE EGG IS TALLER THAN IT IS WIDE -- eight across, nine down. That single
# proportion is what makes it an egg: drawn as wide as it is tall it reads as fat,
# a pebble or a ball, no matter how carefully the ends are rounded. Both ends ARE
# rounded (a point at the top reads as a teardrop), and the widest part sits below
# the middle.

EGG = r"""
................
................
................
................
................
................
................
.....XXXX.......
....XXXXXX......
....XXXXXX......
....XXXXXX......
...XXXXXXXX.....
...XXXXXXXX.....
....XXXXXX......
....XXXXXX......
.....XXXX.......
"""

# The crack is the warning: it appears before the man does.
EGG_CRACKED = r"""
................
................
................
................
................
................
................
.....XXXX.......
....XX.XXX......
....X.XXXX......
....XXX.XX......
...XXX.XXXXX....
...XX.XXXXXX....
....XXXX.XX.....
....XX.XXX......
.....XXXX.......
"""

# An unhorsed knight, on foot, holding his lance upright. He STANDS STILL -- the
# lance is the tell that he is a knight waiting for a mount and not scenery, and
# a vertical line is the only thing that reads as one at this size.
RUNNER = r"""
................
................
................
................
................
................
................
................
...X....XX......
...X....XX......
...X...XXXX.....
...X..XXXXXX....
...X...XXXX.....
...X...X..X.....
...X..XX..XX....
................
"""

# THE LAVA TROLL'S HAND. It rises out of the pit; the arm below it is drawn with
# a character, so the sprite is just the fist and wrist.
HAND = r"""
................
................
.XX...XX...XX...
.XX...XX...XX...
.XX..XXX..XXX...
.XXX.XXX..XXX...
.XXXXXXXXXXXX...
.XXXXXXXXXXXX...
..XXXXXXXXXXX...
..XXXXXXXXXX....
...XXXXXXXXX....
...XXXXXXXX.....
....XXXXXX......
....XXXXXX......
.....XXXX.......
.....XXXX.......
"""

# THE TROLL'S FOREARM -- angled, and NOT another fist. Two hands stacked read as
# two trolls; one long limb needs a forearm that clearly continues the hand.
ARM = r"""
......XXXX......
.....XXXXX......
.....XXXX.......
....XXXXX.......
....XXXX........
...XXXXX........
...XXXX.........
..XXXXX.........
..XXXX..........
.XXXXX..........
.XXXX...........
XXXXX...........
XXXX............
XXX.............
................
................
"""

# THE PTERODACTYL. Two frames: mouth shut, and mouth OPEN -- and only the open
# one can be killed, by a level lance straight down its throat. The silhouette
# has to differ enough that you can call the shot at speed, so the open frame
# drops the jaw a long way rather than a token pixel or two.
PTERO_SHUT = r"""
................
....XX..........
...XXXX.........
..XXXXXX........
.XXXXXXXX.......
XXXXXXXXXX......
.XXXXXXXXXXX....
..XXXXXXXXXXXX..
...XXXXXXXXXXXXX
....XXXXXXXXX...
.....XXXXXX.....
......XXXX......
.......XX.......
................
................
................
"""

PTERO_OPEN = r"""
................
....XX..........
...XXXX.........
..XXXXXX........
.XXXXXXXX.......
XXXXXXXXXX......
.XXXXXXXXXXX....
..XXXXXXXXXXXX..
...XXXXXXXXXXXXX
....XXXXX.......
.....XXX........
......X.........
.....XXX........
....XXXXX.......
...XXXXXXXXXXXXX
................
"""

# ------------------------------------------------------------------ characters
# 8x8 each.

CHARS = {
"plat_l": r"""
.XXXXXXX
XXXXXXXX
XX......
XX......
XX......
XX......
.X......
........
""",
"plat_m": r"""
XXXXXXXX
XXXXXXXX
........
........
........
........
........
........
""",
"plat_r": r"""
XXXXXXX.
XXXXXXXX
......XX
......XX
......XX
......XX
......X.
........
""",
"lava_a": r"""
X..XX..X
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
""",
"lava_b": r"""
.XX..XX.
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
""",
"lava_c": r"""
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
""",
"pad": r"""
XXXXXXXX
XXXXXXXX
XX.XX.XX
X......X
........
........
........
........
""",
"arm": r"""
..XXXX..
..XXXX..
.XXXXXX.
.XXXXXX.
.XXXXXX.
.XXXXXX.
..XXXX..
..XXXX..
""",
"life": r"""
..XX....
.XXXX...
.XXXX...
..XX....
.XXXXX..
XXXXXXX.
..XX.XX.
.XX...XX
""",
}


def rows(art):
    r = [ln for ln in art.strip("\n").split("\n") if ln.strip("\n")]
    return r


def bits(line, lo, hi):
    v = 0
    for i in range(lo, hi):
        c = line[i] if i < len(line) else "."
        v = (v << 1) | (0 if c == "." else 1)
    return v


def mirror8(b):
    out = 0
    for i in range(8):
        out = (out << 1) | ((b >> i) & 1)
    return out


def sprite_bytes(art, flip=False):
    """32 bytes: 16 rows of the left half, then 16 rows of the right half."""
    r = rows(art)
    assert len(r) == 16, len(r)
    left = [bits(ln, 0, 8) for ln in r]
    right = [bits(ln, 8, 16) for ln in r]
    if flip:
        left, right = [mirror8(b) for b in right], [mirror8(b) for b in left]
    return left + right


def char_bytes(art):
    r = rows(art)
    assert len(r) == 8, len(r)
    return [bits(ln, 0, 8) for ln in r]


def emit(fh, label, data, comment):
    fh.write("%s:\t' %s\n" % (label, comment))
    if len(data) % 2:
        data = data + [0]
    for i in range(0, len(data), 8):
        fh.write("\tDATA BYTE " + ",".join("$%02X" % b for b in data[i:i + 8]) + "\n")
    fh.write("\n")


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "src", "art.bas")
    with open(out, "w", newline="\n") as fh:
        fh.write("""\t' JOUST art -- GENERATED by assets/genart.py. Do not edit; regenerate.
\t'
\t' Sprites are QUADRANT-ORDERED for the TMS9918: 16 rows of the left half then
\t' 16 rows of the right half. Each mount is stored twice, facing right and facing
\t' left, because the VDP cannot mirror a sprite.
\t'
\t' Every block is an EVEN number of bytes -- an odd DATA BYTE run misaligns every
\t' word table after it (TRUNCATION.md 1d).

""")
        # player: 4 frames right, 4 frames left = 8 sprites = patterns 0..31
        data = []
        for k in ("up", "mid", "down", "skid"):
            data += sprite_bytes(PLAYER[k])
        emit(fh, "spr_mount_r", data, "ostrich/buzzard facing RIGHT: up, mid, down, skid")

        data = []
        for k in ("up", "mid", "down", "skid"):
            data += sprite_bytes(PLAYER[k], flip=True)
        emit(fh, "spr_mount_l", data, "the same four, facing LEFT")

        emit(fh, "spr_egg", sprite_bytes(EGG), "egg")
        emit(fh, "spr_runner", sprite_bytes(RUNNER), "unhorsed knight, on foot")
        emit(fh, "spr_egg_x", sprite_bytes(EGG_CRACKED), "egg, cracked -- about to hatch")
        emit(fh, "spr_hand", sprite_bytes(HAND), "the lava troll's hand")
        emit(fh, "spr_pt_s", sprite_bytes(PTERO_SHUT), "pterodactyl, mouth SHUT -- invulnerable")
        emit(fh, "spr_pt_o", sprite_bytes(PTERO_OPEN), "pterodactyl, mouth OPEN -- the only target")
        emit(fh, "spr_arm", sprite_bytes(ARM), "the troll's forearm -- angled, not a second hand")

        for name in ("plat_l", "plat_m", "plat_r", "lava_a", "lava_b", "lava_c", "life",
                     "pad", "arm"):
            emit(fh, "chr_" + name, char_bytes(CHARS[name]), name)

    n = os.path.getsize(out)
    print("wrote %s (%d bytes)" % (os.path.normpath(out), n))


if __name__ == "__main__":
    main()
