#!/usr/bin/env python3
"""JOUST art generator -- ASCII art in, src/art.bas out.

Sprites are 16x16 and the TMS9918 stores them QUADRANT-ORDERED: all 16 rows of
the LEFT half, then all 16 rows of the RIGHT half. Reading a 16-wide bitmap as
32 sequential rows produces garbage that still assembles, so the art lives here
as readable ASCII and this file does the interleave once, correctly.

Characters are 8x8, eight bytes each, straightforward.

Every emitted DATA BYTE block is padded to an EVEN length: an odd-length byte run
leaves the assembler's location counter odd and silently misaligns every word
table after it (TRUNCATION.md 1d).

Run:  python3 genart.py      writes ../src/art.bas
"""

import os

# --------------------------------------------------------------------- sprites
# 16x16. '.' is transparent, anything else is on.
#
# THE KNIGHTS ARE TWO SPRITES, RIDER OVER MOUNT, each in its own colour -- the
# arcade's yellow ostrich and green buzzards carry riders whose colour is their
# rank, and a one-colour 16x16 blob could show neither. The figure is drawn ONCE,
# on a 16x20 canvas, with R for the rider and M for the mount, and split here:
#
#   mount sprite = canvas rows 4-19, drawn at (x, y)      feet on row 15, as ever
#   rider sprite = canvas rows 0-15, drawn at (x, y - 4)
#
# so the figure is 18 px tall while every bit of physics still treats (x, y) as
# the top of a 16 px mount. NO PIXEL BELONGS TO BOTH LAYERS (compose() fails the
# build if one does): with SPRITE FLICKER rotating the slots, either layer may be
# the one drawn on top on a given frame, and disjoint art makes that invisible.
#
# Eight mount frames per facing: stand, four running beats, skid, wings up, wings
# down. The four beats are four DIFFERENT leg shapes (stride, front knee up,
# short stride, back leg kicked) -- a two-pose shuffle read as the bird
# vibrating, and a stride and its mirror are the same silhouette.
# Facing left is the same frame mirrored: the figures are asymmetric, so the
# mirror is a facing, not a beat.

RIDER = r"""
................
................
.....RR.........
....RRRR........
....RRRRRRRRRRRR
....RRRR........
...RRRRR........
...RRRR.........
....RRR.........
....RR..........
................
................
................
................
................
................
................
................
................
................
"""
_OBODY = r"""
................
................
................
................
................
................
...........MM...
..........MMMMM.
..........MM....
..MM......MM....
.MMMMMMM.MM.....
MMMMMMMMMMM.....
.MMMMMMMMMM.....
..MMMMMMMM......
....MMMMM.......
"""
LEGS = {
"stand": r"""
.....M..M.......
.....M..M.......
.....M..M.......
.....M..M.......
....MM..MM......
""",
"run1": r"""
.....MM.M.......
....M....M......
...M......M.....
..M........M....
.MM.........MM..
""",
"run2": r"""
.....M.MMM......
.....M....M.....
.....M...M......
.....M..........
....MM..........
""",
"run3": r"""
.....M.M........
.....M..M.......
....M...M.......
...M....M.......
..MM....MM......
""",
"run4": r"""
....MMM.M.......
...M....M.......
..M.....M.......
........M.......
........MM......
""",
"skid": r"""
......M.M.......
.......M.M......
........M.M.....
.........M.M....
.........MMMMM..
""",
"tuck": r"""
....MMMMM.......
...MM...........
................
................
................
""",
}
WINGUP = r"""
................
M...............
MM..............
MMM.............
MMM.............
.MMM............
.MM.............
..M.............
..MM............
...M............
"""
WINGDN = r"""
................
................
................
................
................
................
................
................
................
................
................
................
................
...MMMMM........
...MMMMM........
....MMMM........
.....MMM........
......MM........
"""
_BBODY = r"""
................
................
................
................
................
................
..........MMM...
.........MMMMMM.
.........MMM..M.
..M......MMM....
.MMM...MMMM.....
MMMMMMMMMMM.....
.MMMMMMMMMM.....
..MMMMMMMMM.....
...MMMMMMM......
"""
BLEGS = {
"stand": r"""
.....MM.MM......
.....M...M......
.....M...M......
.....M...M......
....MMM.MMM.....
""",
"run1": r"""
.....MMMM.......
....MM...M......
...M......M.....
..M........M....
.MMM.......MMM..
""",
"run2": r"""
.....MMMMM......
.....M....M.....
.....M...MM.....
.....M..........
....MMM.........
""",
"run3": r"""
.....MMM........
.....M..M.......
....M...M.......
...M....M.......
..MMM...MMM.....
""",
"run4": r"""
....MMMMM.......
...M....M.......
..MM....M.......
........M.......
.......MMM......
""",
"skid": r"""
......MMM.......
.......M.M......
........M.M.....
.........M.M....
.........MMMMM..
""",
"tuck": r"""
....MMMMMM......
...MMM..........
................
................
................
""",
}
BWINGUP = r"""
M...............
MM..............
MMM.............
MMM.............
.MMM............
.MMM............
.MM.............
..M.............
..MM............
..MM............
"""
BWINGDN = r"""
................
................
................
................
................
................
................
................
................
................
................
................
................
...MMMMMM.......
...MMMMMMM......
....MMMMMM......
.....MMMMM......
......MMM.......
"""


def compose(*layers):
    """Overlay canvas layers into one 16x20 figure. A 5-row layer is legs and
    sits on the bottom rows; anything else starts at the top. Overlap fails."""
    out = []
    for y in range(20):
        row = ["."] * 16
        for layer in layers:
            rr = [r for r in layer.strip("\n").split("\n")]
            off = 20 - len(rr) if len(rr) == 5 else 0
            if off <= y < off + len(rr):
                for x, c in enumerate(rr[y - off]):
                    if c != ".":
                        if row[x] not in (".", c):
                            raise SystemExit("genart: rider and mount overlap at row %d col %d" % (y, x))
                        row[x] = c
        out.append("".join(row))
    return out


def layer(fig, ch, top):
    """One sprite's 16 rows out of a composed figure: pixels marked ch only."""
    return "\n".join("".join("X" if c == ch else "." for c in fig[r]) for r in range(top, top + 16))


MOUNT_FRAMES = ("stand", "run1", "run2", "run3", "run4", "skid", "up", "down")


def figures(body, legs, wup, wdn):
    out = []
    for f in MOUNT_FRAMES:
        if f == "up":
            out.append(compose(RIDER, body, legs["tuck"], wup))
        elif f == "down":
            out.append(compose(RIDER, body, legs["tuck"], wdn))
        else:
            out.append(compose(RIDER, body, legs[f]))
    return out


# EGG, CRACKED EGG and the MAN are ONE CHARACTER TALL -- 8 px, not 16. They are
# drawn in the sprite's LOWER half (rows 8-15) so that "feet at y+16" still puts
# them on a surface, and so the same landing arithmetic works for a small actor
# as for a full-size bird. A 16 px egg looked like a boulder next to the mount.

# EGG, CRACKED EGG and the MAN sit in the LOWER part of the cell, ending on row
# 15, so "feet at y+16" puts them on a surface with the same arithmetic a bird uses.
#
# THE EGG IS TALLER THAN IT IS WIDE -- eight across, nine down. That single
# proportion is what makes it an egg: drawn as wide as it is tall it reads as fat,
# a pebble or a ball, no matter how carefully the ends are rounded. Both ends ARE
# rounded (a point at the top reads as a teardrop), and the widest part sits below
# the middle.

EGG = r"""
................
................
................
................
................
................
................
.....XXXX.......
....XXXXXX......
....XXXXXX......
....XXXXXX......
...XXXXXXXX.....
...XXXXXXXX.....
....XXXXXX......
....XXXXXX......
.....XXXX.......
"""

# The crack is the warning: it appears before the man does.
EGG_CRACKED = r"""
................
................
................
................
................
................
................
.....XXXX.......
....XX.XXX......
....X.XXXX......
....XXX.XX......
...XXX.XXXXX....
...XX.XXXXXX....
....XXXX.XX.....
....XX.XXX......
.....XXXX.......
"""

# An unhorsed knight, on foot, holding his lance upright. He STANDS STILL -- the
# lance is the tell that he is a knight waiting for a mount and not scenery, and
# a vertical line is the only thing that reads as one at this size.
RUNNER = r"""
................
................
................
................
................
................
......X.........
......X..XX.....
......X.XXXX....
......X.XXXX....
......XXXXXX....
......X.XXXX....
......X.XXXX....
......X.X..X....
......X.X..X....
......X.XX.XX...
"""
# THE LAVA TROLL'S HAND. It rises out of the pit; the arm below it is drawn with
# a character, so the sprite is just the fist and wrist.
HAND = r"""
................
................
.XX...XX...XX...
.XX...XX...XX...
.XX..XXX..XXX...
.XXX.XXX..XXX...
.XXXXXXXXXXXX...
.XXXXXXXXXXXX...
..XXXXXXXXXXX...
..XXXXXXXXXX....
...XXXXXXXXX....
...XXXXXXXX.....
....XXXXXX......
....XXXXXX......
.....XXXX.......
.....XXXX.......
"""

# THE TROLL'S FOREARM -- angled, and NOT another fist. Two hands stacked read as
# two trolls; one long limb needs a forearm that clearly continues the hand.
ARM = r"""
......XXXX......
.....XXXXX......
.....XXXX.......
....XXXXX.......
....XXXX........
...XXXXX........
...XXXX.........
..XXXXX.........
..XXXX..........
.XXXXX..........
.XXXX...........
XXXXX...........
XXXX............
XXX.............
................
................
"""

# THE PTERODACTYL. Two frames: mouth shut, and mouth OPEN -- and only the open
# one can be killed, by a level lance straight down its throat. The silhouette
# has to differ enough that you can call the shot at speed, so the open frame
# drops the jaw a long way rather than a token pixel or two.
PTERO_SHUT = r"""
................
................
X...............
XX..............
.XXX............
..XXXX......XX..
...XXXXX...XXXXX
XXXXXXXXXXXXX...
.XXXXXXXXXXX....
....XXXXXX......
....XX..........
...XX...........
................
................
................
................
"""

PTERO_OPEN = r"""
................
................
................
................
................
............XX..
...XXXXX...XXXXX
XXXXXXXXXXXX....
.XXXXXXXXXXX.XXX
..XXXXXXXX..XX..
.XXXX.XX........
XXX..XX.........
XX..............
X...............
................
................
"""
# ------------------------------------------------------------------ characters
# 8x8 each, WITH THEIR COLOURS: one (foreground, background) pair per pixel row,
# because the TMS9918's default mode colours each 8x1 line separately. Both live
# here so a character and its colour table cannot drift apart; the generator
# emits chr_* in CHAR_ORDER and col_chars in the same order, and JOUST.bas
# uploads them as one run from 128.
#
# TMS colours: 1 black, 2 green, 3 lt green, 4 dk blue, 5 lt blue, 6 dk red,
# 7 cyan, 8 red, 9 lt red, 10 dk yellow, 11 lt yellow, 12 dk green, 13 magenta,
# 14 grey, 15 white.
#
# THE LEDGES ARE ROCK, ONE CHARACTER TALL. The arcade's ledges are slabs of
# brown rock with a lit top edge and a ragged underside, not lines; drawn in the
# single surface row they keep every collision band exactly where it was (the
# head-bump band IS that row).

K, R6, R8, Y10, Y11, W, CY, GR = 1, 6, 8, 10, 11, 15, 7, 14

CHARS = {
"plat_l": (r"""
XXXXXXXX
XXXXXXXX
.XXXXXXX
..XXXXXX
....XXXX
......XX
.......X
........
""", [(Y11, K), (Y10, K), (Y10, K), (Y10, K), (R6, K), (R6, K), (R6, K), (R6, K)]),
"plat_m": (r"""
XXXXXXXX
XXXXXXXX
XX.XXXX.
XXXXX.XX
X.XXXXXX
XXXX.XXX
XXXXXXX.
.XXXXXXX
""", [(Y11, K), (Y10, K), (Y10, R6), (Y10, R6), (Y10, R6), (R6, Y10), (R6, Y10), (R6, Y10)]),
"plat_r": (r"""
XXXXXXXX
XXXXXXXX
XXXXXXX.
XXXXXX..
XXXX....
XX......
X.......
........
""", [(Y11, K), (Y10, K), (Y10, K), (Y10, K), (R6, K), (R6, K), (R6, K), (R6, K)]),
# THE LAVA'S SURFACE: flames. Two characters so neighbouring cells are out of
# step; both are re-uploaded from FLAMES as the game runs (lava_tick), which
# animates the whole pit for 16 bytes instead of rewriting every cell.
"lava_a": (r"""
...X....
..XX..X.
..XX.XX.
.XXXXXX.
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
""", [(Y11, K), (Y11, K), (Y10, K), (Y10, K), (R8, Y10), (R8, Y10), (R8, R6), (R6, R8)]),
"lava_b": (r"""
......X.
.X...XX.
.XX..XX.
XXXX.XXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
""", [(Y11, K), (Y11, K), (Y10, K), (Y10, K), (R8, Y10), (R8, Y10), (R8, R6), (R6, R8)]),
"lava_c": (r"""
XXXXXXXX
XX.XXXXX
XXXXX.XX
XXXXXXXX
X.XXXXXX
XXXX.XXX
XXXXXXXX
XXXXXXX.
""", [(R8, R6)] * 8),
"life": (r"""
..XX....
.XXXX...
.XXXX...
..XX....
.XXXXX..
XXXXXXX.
..XX.XX.
.XX...XX
""", [(Y11, K)] * 8),
# A SPAWN PAD is a stretch of ledge whose lit edge glows: the same rock, a
# cyan top. It has to read as a pad against the rock and still as ledge.
"pad": (r"""
XXXXXXXX
XXXXXXXX
XX.XXXX.
XXXXX.XX
X.XXXXXX
XXXX.XXX
XXXXXXX.
.XXXXXXX
""", [(W, K), (CY, K), (Y10, R6), (Y10, R6), (Y10, R6), (R6, Y10), (R6, Y10), (R6, Y10)]),
# THE BASE'S BODY, below its surface: solid rock down into the lava, with the
# score panel cut into it.
"rock": (r"""
XX.XXXXX
XXXXX.XX
X.XXXXXX
XXXX.XXX
XXXXXXX.
.XXXXXXX
XXX.XXXX
XXXXXX.X
""", [(Y10, R6)] * 8),
"egg": (r"""
..XXXX..
.XXXXXX.
.XXXXXX.
XXXXXXXX
XXXXXXXX
.XXXXXX.
.XXXXXX.
..XXXX..
""", [(W, K)] * 8),
# The base's body slopes in at each end, so it stands IN the lava rather than
# being a box sitting on it.
"rock_l": (r"""
XXXXXXXX
.XXXXX.X
.XXXXXXX
..XX.XXX
..XXXXXX
...XXXX.
...XXXXX
....X.XX
""", [(Y10, R6), (Y10, R6), (Y10, R6), (Y10, R6), (Y10, R6), (Y10, R6), (Y10, R6), (Y10, R6)]),
"rock_r": (r"""
XXXXXXXX
X.XXXXX.
XXXXXXX.
XXX.XX..
XXXXXX..
.XXXX...
XXXXX...
XX.X....
""", [(Y10, R6), (Y10, R6), (Y10, R6), (Y10, R6), (Y10, R6), (Y10, R6), (Y10, R6), (Y10, R6)]),
}

# A LEDGE'S UNDERSIDE, the row below its surface: thin at the ends, deepest in
# the middle, so each slab reads as a natural lump of rock hanging in the air
# under a flat top. draw_plat picks one per column by its distance from the
# nearer end (1 -> und1, 2 -> und2, 3+ -> und3a/b). Collision still treats the
# ledge as the one surface row.
CHARS["plat_m2"] = (r"""
XXXXXXXX
XXXXXXXX
XXXX.XXX
X.XXXXX.
XXXXX.XX
XX.XXXXX
.XXXXX.X
XXXX.XXX
""", [(Y11, K), (Y10, K), (Y10, R6), (Y10, R6), (Y10, R6), (R6, Y10), (R6, Y10), (R6, Y10)])
CHARS["und1l"] = (r"""
.XXXXXXX
...XXXXX
.....XXX
.......X
........
........
........
........
""", [(R6, K)] * 8)
CHARS["und1r"] = (r"""
XXXXXXX.
XXXXX...
XXX.....
X.......
........
........
........
........
""", [(R6, K)] * 8)
CHARS["und2"] = (r"""
XXXXXXXX
XXXXXXXX
XXXXXXXX
.XXXXX.X
..XXX...
...X....
........
........
""", [(R6, Y10), (R6, K), (R6, K), (R6, K), (R6, K), (R6, K), (R6, K), (R6, K)])
CHARS["und3a"] = (r"""
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXX.
.XXXXX..
..XXX...
...X....
""", [(R6, Y10), (R6, Y10), (R6, K), (R6, K), (R6, K), (R6, K), (R6, K), (R6, K)])
CHARS["und3b"] = (r"""
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
.XXXXXXX
..XXXXXX
...XX.X.
....X...
""", [(R6, Y10), (R6, Y10), (R6, K), (R6, K), (R6, K), (R6, K), (R6, K), (R6, K)])

CHAR_ORDER = ("plat_l", "plat_m", "plat_r", "lava_a", "lava_b", "lava_c", "life",
              "pad", "rock", "egg", "rock_l", "rock_r",
              "plat_m2", "und1l", "und1r", "und2", "und3a", "und3b")

# FLAME FRAMES for the two lava-surface characters, cycled by lava_tick. Four
# shapes, so the fire licks rather than blinks.
FLAMES = [r"""
...X....
..XX..X.
..XX.XX.
.XXXXXX.
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
""", r"""
..X.....
..X..X..
.XXX.XX.
.XXXXXX.
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
""", r"""
........
.X....X.
.XX..XXX
XXXX.XXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
""", r"""
.....X..
.X...X..
.X..XXX.
XXX.XXX.
XXXXXXXX
XXXXXXXX
XXXXXXXX
XXXXXXXX
"""]



# ------------------------------------------------------------------ title logo
# "JOUST", 160 x 24 px: five heavy letters on a 4 px grid, corners rounded, shaded
# white-hot at the top through yellow and orange to dark red at the foot -- the
# same fire as the font. Cut into 8x8 tiles, duplicates (per tile row, since the
# colour runs down the rows) shared; empty tiles are the space character.
LOGO_LETTERS = {
"J": [".######", "....##.", "....##.", "##..##.", "##..##.", ".####.."],
"O": [".#####.", "##...##", "##...##", "##...##", "##...##", ".#####."],
"U": ["##...##", "##...##", "##...##", "##...##", "##...##", ".#####."],
"S": [".######", "##.....", ".#####.", ".....##", ".....##", "######."],
"T": ["#######", "..###..", "..###..", "..###..", "..###..", "..###.."],
}
LOGO_GRAD = [15, 11, 11, 11, 11, 11, 11, 10, 10, 10, 10, 10, 9, 9, 9, 9, 9,
             8, 8, 8, 8, 6, 6, 6]
LOGO_FIRST = 160


def logo_bitmap():
    W, H = 160, 24
    px = [[0] * W for _ in range(H)]
    x0 = 2
    for ch in "JOUST":
        g = LOGO_LETTERS[ch]
        for uy in range(6):
            for ux in range(7):
                if g[uy][ux] == "#":
                    for y in range(4):
                        for x in range(4):
                            px[uy * 4 + y][x0 + ux * 4 + x] = 1
        # ROUND THE CORNERS: an empty unit with filled units on two adjacent
        # sides gets a 4 px quarter fill, and a filled outside corner loses one.
        def at(ux, uy):
            return 0 <= ux < 7 and 0 <= uy < 6 and g[uy][ux] == "#"
        for uy in range(6):
            for ux in range(7):
                for dx, dy in ((1, 1), (-1, 1), (1, -1), (-1, -1)):
                    if at(ux, uy) and not at(ux - dx, uy) and not at(ux, uy - dy) and not at(ux - dx, uy - dy):
                        # outside corner of a filled unit: shave it
                        for k in range(3):
                            for j in range(3 - k):
                                xx = x0 + ux * 4 + (j if dx > 0 else 3 - j)
                                yy = uy * 4 + (k if dy > 0 else 3 - k)
                                px[yy][xx] = 0
        x0 += 32
    return px


def logo_tiles():
    px = logo_bitmap()
    tiles, cols, keys, amap = [], [], {}, []
    for tr in range(3):
        for tc in range(20):
            b = []
            for y in range(8):
                v = 0
                for x in range(8):
                    v = (v << 1) | px[tr * 8 + y][tc * 8 + x]
                b.append(v)
            if not any(b):
                amap.append(32)
                continue
            key = (tr, tuple(b))
            if key not in keys:
                keys[key] = LOGO_FIRST + len(tiles)
                tiles.append(b)
                cols.append([LOGO_GRAD[tr * 8 + y] << 4 | 1 for y in range(8)])
            amap.append(keys[key])
    return tiles, cols, amap


def rows(art):
    r = [ln for ln in art.strip("\n").split("\n") if ln.strip("\n")]
    return r


def bits(line, lo, hi):
    v = 0
    for i in range(lo, hi):
        c = line[i] if i < len(line) else "."
        v = (v << 1) | (0 if c == "." else 1)
    return v


def mirror8(b):
    out = 0
    for i in range(8):
        out = (out << 1) | ((b >> i) & 1)
    return out


def sprite_bytes(art, flip=False):
    """32 bytes: 16 rows of the left half, then 16 rows of the right half."""
    r = rows(art)
    assert len(r) == 16, len(r)
    left = [bits(ln, 0, 8) for ln in r]
    right = [bits(ln, 8, 16) for ln in r]
    if flip:
        left, right = [mirror8(b) for b in right], [mirror8(b) for b in left]
    return left + right


def char_bytes(art):
    r = rows(art)
    assert len(r) == 8, len(r)
    return [bits(ln, 0, 8) for ln in r]


def emit(fh, label, data, comment):
    fh.write("%s:\t' %s\n" % (label, comment))
    if len(data) % 2:
        data = data + [0]
    for i in range(0, len(data), 8):
        fh.write("\tDATA BYTE " + ",".join("$%02X" % b for b in data[i:i + 8]) + "\n")
    fh.write("\n")


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "src", "art.bas")
    with open(out, "w", newline="\n") as fh:
        fh.write("""\t' JOUST art -- GENERATED by assets/genart.py. Do not edit; regenerate.
\t'
\t' Sprites are QUADRANT-ORDERED for the TMS9918: 16 rows of the left half then
\t' 16 rows of the right half. Each mount is stored twice, facing right and facing
\t' left, because the VDP cannot mirror a sprite.
\t'
\t' Every block is an EVEN number of bytes -- an odd DATA BYTE run misaligns every
\t' word table after it (TRUNCATION.md 1d).

""")
        # mounts: 8 frames facing right, then the same 8 facing left, per bird
        ost = figures(_OBODY, LEGS, WINGUP, WINGDN)
        buz = figures(_BBODY, BLEGS, BWINGUP, BWINGDN)
        for label, figs, what in (("spr_ost", ost, "the player's OSTRICH"),
                                  ("spr_buz", buz, "the knights' BUZZARD")):
            for flip, side in ((False, "RIGHT"), (True, "LEFT")):
                data = []
                for f in figs:
                    data += sprite_bytes(layer(f, "M", 4), flip=flip)
                emit(fh, label + ("_l" if flip else "_r"), data,
                     what + " facing " + side + ": " + ", ".join(MOUNT_FRAMES))
        # one rider, right then left; the frame does not change him
        data = sprite_bytes(layer(ost[0], "R", 0)) + sprite_bytes(layer(ost[0], "R", 0), flip=True)
        emit(fh, "spr_rider", data, "the rider, facing right then left -- drawn 4 px above his mount")
        emit(fh, "spr_egg", sprite_bytes(EGG), "egg")
        emit(fh, "spr_egg_x", sprite_bytes(EGG_CRACKED), "egg, cracked -- about to hatch")
        emit(fh, "spr_runner", sprite_bytes(RUNNER) + sprite_bytes(RUNNER, flip=True),
             "unhorsed knight, on foot, facing right then left")
        emit(fh, "spr_hand", sprite_bytes(HAND), "the lava troll's hand")
        emit(fh, "spr_arm", sprite_bytes(ARM), "the troll's forearm -- angled, not a second hand")
        emit(fh, "spr_pt", sprite_bytes(PTERO_SHUT) + sprite_bytes(PTERO_OPEN)
             + sprite_bytes(PTERO_SHUT, flip=True) + sprite_bytes(PTERO_OPEN, flip=True),
             "pterodactyl: shut, OPEN facing right; shut, OPEN facing left")

        for name in CHAR_ORDER:
            emit(fh, "chr_" + name, char_bytes(CHARS[name][0]), name)
        data = []
        for name in CHAR_ORDER:
            data += [fg << 4 | bg for fg, bg in CHARS[name][1]]
        emit(fh, "col_chars", data, "their colours, 8 bytes each, same order")
        for i, f in enumerate(FLAMES):
            emit(fh, "flame%d" % i, char_bytes(f), "lava flame, frame %d" % i)
        tiles, cols, amap = logo_tiles()
        fh.write("\t' TITLE LOGO: %d tiles from character %d, their colours, and the\n"
                 "\t' 20 x 3 name map (32 = an empty tile).\n" % (len(tiles), LOGO_FIRST))
        fh.write("\tCONST LOGON = %d\n" % len(tiles))
        emit(fh, "logo_chr", sum(tiles, []), "logo tiles")
        emit(fh, "logo_col", sum(cols, []), "logo tile colours")
        emit(fh, "logo_map", amap, "logo name map, 20 x 3")

    n = os.path.getsize(out)
    print("wrote %s (%d bytes)" % (os.path.normpath(out), n))


if __name__ == "__main__":
    main()
