"""Original editable pixel art and ROM scenery. Run from the project root."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def canvas(w, h):
    return [[0] * w for _ in range(h)]

def rect(a, x, y, w, h, ink=1):
    for row in range(y, y+h):
        for col in range(x, x+w):
            a[row][col] = ink

def sprite_bytes(a):
    assert len(a) == 16 and all(len(r) == 16 for r in a)
    return [sum(a[y][x+b] << (7-b) for b in range(8))
            for x in (0, 8) for y in range(16)]

def heli(front=False, beat=0):
    a = canvas(32, 16)
    rect(a, 3 if beat == 0 else 8, 1, 26 if beat == 0 else 15, 1)
    rect(a, 17, 2, 1, 3)
    if front:
        rect(a, 12, 5, 10, 7)
        rect(a, 10, 7, 14, 4)
        rect(a, 13, 6, 3, 3, 0)
        rect(a, 18, 6, 3, 3, 0)
        rect(a, 12, 12, 2, 2)
        rect(a, 20, 12, 2, 2)
        rect(a, 9, 14, 7, 1)
        rect(a, 18, 14, 7, 1)
    else:
        rect(a, 13, 5, 12, 7)
        rect(a, 11, 7, 17, 4)
        rect(a, 24, 7, 5, 3)
        rect(a, 21, 6, 4, 3, 0)
        rect(a, 14, 7, 3, 4, 0)
        rect(a, 3, 8, 10, 2)
        rect(a, 2, 4, 2, 6)
        rect(a, 0, 6, 7, 1)
        rect(a, 15, 12, 1, 2)
        rect(a, 24, 12, 1, 2)
        rect(a, 11, 14, 18, 1)
    return a

SPRITES = []
for facing in ('right', 'left', 'front'):
    for beat in range(2):
        a = heli(facing == 'front', beat)
        if facing == 'left':
            a = [r[::-1] for r in a]
        SPRITES.extend([([r[:16] for r in a]), ([r[16:] for r in a])])
# 12 tank, 13/14 runner, 15 jet, 16 drone, 17 shot, 18/19 blast
a = canvas(16, 16)
rect(a, 1, 7, 14, 5); rect(a, 4, 4, 8, 4); rect(a, 0, 4, 8, 1)
for x in (3, 7, 11): rect(a, x, 10, 2, 1, 0)
SPRITES.append(a)
for beat in range(2):
    a = canvas(16, 16)
    rect(a, 3, 0, 3, 2); rect(a, 4, 2, 1, 3)
    rect(a, 1 if beat else 2, 3, 6 if beat else 4, 1)
    rect(a, 3, 5, 1, 2); rect(a, 5 if beat else 4, 5, 1, 2)
    rect(a, 2 if beat else 3, 7, 2, 1); rect(a, 5, 7, 2, 1)
    SPRITES.append(a)
a = canvas(16, 16)
rect(a, 0, 7, 16, 3); rect(a, 6, 3, 3, 10); rect(a, 13, 4, 2, 7)
rect(a, 3, 6, 9, 1); SPRITES.append(a)
a = canvas(16, 16)
rect(a, 4, 4, 8, 8); rect(a, 2, 6, 12, 4)
rect(a, 6, 2, 4, 12); rect(a, 6, 6, 4, 4, 0); SPRITES.append(a)
a = canvas(16, 16); rect(a, 0, 0, 3, 3); SPRITES.append(a)
for beat in range(2):
    a = canvas(16, 16)
    for y in range(16):
        for x in range(16):
            d = abs(x-7) + abs(y-7)
            if (3+beat*2 <= d <= 7+beat*3) and (x+y*3) % 4 != 0: a[y][x] = 1
    SPRITES.append(a)

# Characters 128..143. Eight explicit colour bytes per character.
TILES = [
    ([255,0,0,0,0,0,0,0], 0x31),       # 128 grass
    ([255,170,255,85,255,170,255,85],0x31), # 129 soil
    ([1,3,7,15,31,63,127,255],0x41),   # 130 hill rising
    ([128,192,224,240,248,252,254,255],0x41),
    ([255]*8,0x41),                    # 132 hill fill
    ([255,129,189,165,165,189,129,255],0xE1), # 133 wall
    ([255,0,255,0,255,0,255,0],0x61),   # 134 roof
    ([126,66,66,66,66,66,66,126],0xB1), # 135 closed door
    ([255,129,129,129,129,129,129,255],0xE1), # 136 open
    ([255,0,0,0,0,0,0,0],0xF1),       # 137 pad
    ([129,129,129,255,129,129,129,0],0xF1), # 138 H
    ([8,8,8,8,8,8,8,8],0xB1),        # 139 border
    ([0,126,24,63,127,24,126,0],0xF1), # 140 spare
    ([24,24,126,24,24,36,66,0],0xB1), # 141 queue
    ([0,0,0,0,0,0,0,0],0x11),        # 142 dark
    ([0,24,60,126,255,126,60,24],0xA1), # 143 beacon
]

# Five rows; map row 0 appears at screen row 17. Camps are 48 pixels wide.
MAP = [[32]*160 for _ in range(5)]
MAP[4] = [128]*160
for c in range(160):
    phase = c % 18
    if phase in (0,1,2,3):
        MAP[2][c] = 130 if phase < 2 else 131
        MAP[3][c] = 132
for camp in (16,48,80,112):
    for c in range(camp-3, camp+3):
        MAP[1][c] = 134
        MAP[2][c] = 133
        MAP[3][c] = 133
    MAP[2][camp] = 135; MAP[3][camp] = 135
for c in range(142,147):
    MAP[0][c] = 134
    MAP[1][c] = 133
    MAP[2][c] = 133
    MAP[3][c] = 133
MAP[2][144] = 136; MAP[3][144] = 136
for c in range(148,156): MAP[4][c] = 137
MAP[4][151] = 138
for y in range(5): MAP[y][134] = 139

def emit(label, data):
    assert len(data) % 2 == 0, label
    return label + ':\n' + ''.join('    DATA BYTE '+','.join(str(v) for v in data[i:i+16])+'\n' for i in range(0,len(data),16))

def generate():
    text = "' Generated by assets/generate.py; edit the generator.\n"
    text += emit('sprite_art', [b for a in SPRITES for b in sprite_bytes(a)])
    text += emit('tile_art', [b for bits,_ in TILES for b in bits])
    text += emit('tile_colors', [c for _,c in TILES for _ in range(8)])
    text += emit('world_map', [c for r in MAP for c in r])
    text += emit('ground_row', [129]*32)
    (ROOT/'src/assets.bas').write_text(text, encoding='utf-8', newline='\n')
    print(f'Assets: {len(SPRITES)} sprites, {len(TILES)} tiles, {len(MAP)*160} map bytes')

if __name__ == '__main__': generate()
