	' JOUST art -- GENERATED by assets/genart.py. Do not edit; regenerate.
	'
	' Sprites are QUADRANT-ORDERED for the TMS9918: 16 rows of the left half then
	' 16 rows of the right half. Each mount is stored twice, facing right and facing
	' left, because the VDP cannot mirror a sprite.
	'
	' Every block is an EVEN number of bytes -- an odd DATA BYTE run misaligns every
	' word table after it (TRUNCATION.md 1d).

spr_mount_r:	' ostrich/buzzard facing RIGHT: up, mid, down, skid
	DATA BYTE $01,$03,$03,$01,$07,$0D,$19,$31
	DATA BYTE $61,$01,$07,$0F,$06,$0C,$18,$30
	DATA BYTE $80,$C0,$C0,$80,$E0,$F0,$FC,$FE
	DATA BYTE $F8,$F0,$F0,$E0,$C0,$60,$30,$18
	DATA BYTE $01,$03,$03,$01,$07,$0F,$1F,$3F
	DATA BYTE $7F,$3F,$0F,$07,$06,$0C,$18,$30
	DATA BYTE $80,$C0,$C0,$80,$E0,$F0,$FC,$FE
	DATA BYTE $F8,$F0,$E0,$C0,$C0,$60,$30,$18
	DATA BYTE $01,$03,$03,$01,$07,$07,$0F,$1F
	DATA BYTE $3F,$67,$0F,$07,$06,$0C,$18,$30
	DATA BYTE $80,$C0,$C0,$80,$E0,$F0,$FC,$FE
	DATA BYTE $F8,$F0,$E0,$C0,$C0,$60,$30,$18
	DATA BYTE $01,$03,$03,$01,$07,$0F,$1F,$3F
	DATA BYTE $7F,$3F,$0F,$07,$0E,$18,$38,$00
	DATA BYTE $80,$C0,$C0,$80,$E0,$F0,$FC,$FE
	DATA BYTE $F8,$F0,$E0,$C0,$70,$18,$1C,$00

spr_mount_l:	' the same four, facing LEFT
	DATA BYTE $01,$03,$03,$01,$07,$0F,$3F,$7F
	DATA BYTE $1F,$0F,$0F,$07,$03,$06,$0C,$18
	DATA BYTE $80,$C0,$C0,$80,$E0,$B0,$98,$8C
	DATA BYTE $86,$80,$E0,$F0,$60,$30,$18,$0C
	DATA BYTE $01,$03,$03,$01,$07,$0F,$3F,$7F
	DATA BYTE $1F,$0F,$07,$03,$03,$06,$0C,$18
	DATA BYTE $80,$C0,$C0,$80,$E0,$F0,$F8,$FC
	DATA BYTE $FE,$FC,$F0,$E0,$60,$30,$18,$0C
	DATA BYTE $01,$03,$03,$01,$07,$0F,$3F,$7F
	DATA BYTE $1F,$0F,$07,$03,$03,$06,$0C,$18
	DATA BYTE $80,$C0,$C0,$80,$E0,$E0,$F0,$F8
	DATA BYTE $FC,$E6,$F0,$E0,$60,$30,$18,$0C
	DATA BYTE $01,$03,$03,$01,$07,$0F,$3F,$7F
	DATA BYTE $1F,$0F,$07,$03,$0E,$18,$38,$00
	DATA BYTE $80,$C0,$C0,$80,$E0,$F0,$F8,$FC
	DATA BYTE $FE,$FC,$F0,$E0,$70,$18,$1C,$00

spr_egg:	' egg
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$07
	DATA BYTE $0F,$0F,$0F,$1F,$1F,$0F,$0F,$07
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$80
	DATA BYTE $C0,$C0,$C0,$E0,$E0,$C0,$C0,$80

spr_runner:	' unhorsed knight, on foot
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $10,$10,$11,$13,$11,$11,$13,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $C0,$C0,$E0,$F0,$E0,$20,$30,$00

spr_egg_x:	' egg, cracked -- about to hatch
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$07
	DATA BYTE $0D,$0B,$0E,$1D,$1B,$0F,$0D,$07
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$80
	DATA BYTE $C0,$C0,$C0,$F0,$F0,$60,$C0,$80

spr_hand:	' the lava troll's hand
	DATA BYTE $00,$00,$63,$63,$67,$77,$7F,$7F
	DATA BYTE $3F,$3F,$1F,$1F,$0F,$0F,$07,$07
	DATA BYTE $00,$00,$18,$18,$38,$38,$F8,$F8
	DATA BYTE $F8,$F0,$F0,$E0,$C0,$C0,$80,$80

spr_pt_s:	' pterodactyl, mouth SHUT -- invulnerable
	DATA BYTE $00,$0C,$1E,$3F,$7F,$FF,$7F,$3F
	DATA BYTE $1F,$0F,$07,$03,$01,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$80,$C0,$F0,$FC
	DATA BYTE $FF,$F8,$E0,$C0,$80,$00,$00,$00

spr_pt_o:	' pterodactyl, mouth OPEN -- the only target
	DATA BYTE $00,$0C,$1E,$3F,$7F,$FF,$7F,$3F
	DATA BYTE $1F,$0F,$07,$02,$07,$0F,$1F,$00
	DATA BYTE $00,$00,$00,$00,$80,$C0,$F0,$FC
	DATA BYTE $FF,$80,$00,$00,$00,$80,$FF,$00

spr_arm:	' the troll's forearm -- angled, not a second hand
	DATA BYTE $03,$07,$07,$0F,$0F,$1F,$1E,$3E
	DATA BYTE $3C,$7C,$78,$F8,$F0,$E0,$00,$00
	DATA BYTE $C0,$C0,$80,$80,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00

chr_plat_l:	' plat_l
	DATA BYTE $7F,$FF,$C0,$C0,$C0,$C0,$40,$00

chr_plat_m:	' plat_m
	DATA BYTE $FF,$FF,$00,$00,$00,$00,$00,$00

chr_plat_r:	' plat_r
	DATA BYTE $FE,$FF,$03,$03,$03,$03,$02,$00

chr_lava_a:	' lava_a
	DATA BYTE $99,$FF,$FF,$FF,$FF,$FF,$FF,$FF

chr_lava_b:	' lava_b
	DATA BYTE $66,$FF,$FF,$FF,$FF,$FF,$FF,$FF

chr_lava_c:	' lava_c
	DATA BYTE $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF

chr_life:	' life
	DATA BYTE $30,$78,$78,$30,$7C,$FE,$36,$63

chr_pad:	' pad
	DATA BYTE $FF,$FF,$DB,$81,$00,$00,$00,$00

chr_arm:	' arm
	DATA BYTE $3C,$3C,$7E,$7E,$7E,$7E,$3C,$3C

