	' JOUST art -- GENERATED by assets/genart.py. Do not edit; regenerate.
	'
	' Sprites are QUADRANT-ORDERED for the TMS9918: 16 rows of the left half then
	' 16 rows of the right half. Each mount is stored twice, facing right and facing
	' left, because the VDP cannot mirror a sprite.
	'
	' Every block is an EVEN number of bytes -- an odd DATA BYTE run misaligns every
	' word table after it (TRUNCATION.md 1d).

spr_ost_r:	' the player's OSTRICH facing RIGHT: stand, run1, run2, run3, run4, skid, up, down
	DATA BYTE $00,$00,$00,$00,$00,$30,$7F,$FF
	DATA BYTE $7F,$3F,$0F,$04,$04,$04,$04,$0C
	DATA BYTE $00,$00,$18,$3E,$30,$30,$60,$E0
	DATA BYTE $E0,$C0,$80,$80,$80,$80,$80,$C0
	DATA BYTE $00,$00,$00,$00,$00,$30,$7F,$FF
	DATA BYTE $7F,$3F,$0F,$06,$08,$10,$20,$60
	DATA BYTE $00,$00,$18,$3E,$30,$30,$60,$E0
	DATA BYTE $E0,$C0,$80,$80,$40,$20,$10,$0C
	DATA BYTE $00,$00,$00,$00,$00,$30,$7F,$FF
	DATA BYTE $7F,$3F,$0F,$05,$04,$04,$04,$0C
	DATA BYTE $00,$00,$18,$3E,$30,$30,$60,$E0
	DATA BYTE $E0,$C0,$80,$C0,$20,$40,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$30,$7F,$FF
	DATA BYTE $7F,$3F,$0F,$05,$04,$08,$10,$30
	DATA BYTE $00,$00,$18,$3E,$30,$30,$60,$E0
	DATA BYTE $E0,$C0,$80,$00,$80,$80,$80,$C0
	DATA BYTE $00,$00,$00,$00,$00,$30,$7F,$FF
	DATA BYTE $7F,$3F,$0F,$0E,$10,$20,$00,$00
	DATA BYTE $00,$00,$18,$3E,$30,$30,$60,$E0
	DATA BYTE $E0,$C0,$80,$80,$80,$80,$80,$C0
	DATA BYTE $00,$00,$00,$00,$00,$30,$7F,$FF
	DATA BYTE $7F,$3F,$0F,$02,$01,$00,$00,$00
	DATA BYTE $00,$00,$18,$3E,$30,$30,$60,$E0
	DATA BYTE $E0,$C0,$80,$80,$40,$A0,$50,$7C
	DATA BYTE $E0,$70,$60,$20,$30,$30,$7F,$FF
	DATA BYTE $7F,$3F,$0F,$0F,$18,$00,$00,$00
	DATA BYTE $00,$00,$18,$3E,$30,$30,$60,$E0
	DATA BYTE $E0,$C0,$80,$80,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$30,$7F,$FF
	DATA BYTE $7F,$3F,$1F,$0F,$1F,$03,$00,$00
	DATA BYTE $00,$00,$18,$3E,$30,$30,$60,$E0
	DATA BYTE $E0,$C0,$80,$80,$00,$00,$00,$00

spr_ost_l:	' the player's OSTRICH facing LEFT: stand, run1, run2, run3, run4, skid, up, down
	DATA BYTE $00,$00,$18,$7C,$0C,$0C,$06,$07
	DATA BYTE $07,$03,$01,$01,$01,$01,$01,$03
	DATA BYTE $00,$00,$00,$00,$00,$0C,$FE,$FF
	DATA BYTE $FE,$FC,$F0,$20,$20,$20,$20,$30
	DATA BYTE $00,$00,$18,$7C,$0C,$0C,$06,$07
	DATA BYTE $07,$03,$01,$01,$02,$04,$08,$30
	DATA BYTE $00,$00,$00,$00,$00,$0C,$FE,$FF
	DATA BYTE $FE,$FC,$F0,$60,$10,$08,$04,$06
	DATA BYTE $00,$00,$18,$7C,$0C,$0C,$06,$07
	DATA BYTE $07,$03,$01,$03,$04,$02,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$0C,$FE,$FF
	DATA BYTE $FE,$FC,$F0,$A0,$20,$20,$20,$30
	DATA BYTE $00,$00,$18,$7C,$0C,$0C,$06,$07
	DATA BYTE $07,$03,$01,$00,$01,$01,$01,$03
	DATA BYTE $00,$00,$00,$00,$00,$0C,$FE,$FF
	DATA BYTE $FE,$FC,$F0,$A0,$20,$10,$08,$0C
	DATA BYTE $00,$00,$18,$7C,$0C,$0C,$06,$07
	DATA BYTE $07,$03,$01,$01,$01,$01,$01,$03
	DATA BYTE $00,$00,$00,$00,$00,$0C,$FE,$FF
	DATA BYTE $FE,$FC,$F0,$70,$08,$04,$00,$00
	DATA BYTE $00,$00,$18,$7C,$0C,$0C,$06,$07
	DATA BYTE $07,$03,$01,$01,$02,$05,$0A,$3E
	DATA BYTE $00,$00,$00,$00,$00,$0C,$FE,$FF
	DATA BYTE $FE,$FC,$F0,$40,$80,$00,$00,$00
	DATA BYTE $00,$00,$18,$7C,$0C,$0C,$06,$07
	DATA BYTE $07,$03,$01,$01,$00,$00,$00,$00
	DATA BYTE $07,$0E,$06,$04,$0C,$0C,$FE,$FF
	DATA BYTE $FE,$FC,$F0,$F0,$18,$00,$00,$00
	DATA BYTE $00,$00,$18,$7C,$0C,$0C,$06,$07
	DATA BYTE $07,$03,$01,$01,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$0C,$FE,$FF
	DATA BYTE $FE,$FC,$F8,$F0,$F8,$C0,$00,$00

spr_buz_r:	' the knights' BUZZARD facing RIGHT: stand, run1, run2, run3, run4, skid, up, down
	DATA BYTE $00,$00,$00,$00,$00,$20,$71,$FF
	DATA BYTE $7F,$3F,$1F,$06,$04,$04,$04,$0E
	DATA BYTE $00,$00,$38,$7E,$72,$70,$E0,$E0
	DATA BYTE $E0,$E0,$C0,$C0,$40,$40,$40,$E0
	DATA BYTE $00,$00,$00,$00,$00,$20,$71,$FF
	DATA BYTE $7F,$3F,$1F,$07,$0C,$10,$20,$70
	DATA BYTE $00,$00,$38,$7E,$72,$70,$E0,$E0
	DATA BYTE $E0,$E0,$C0,$80,$40,$20,$10,$1C
	DATA BYTE $00,$00,$00,$00,$00,$20,$71,$FF
	DATA BYTE $7F,$3F,$1F,$07,$04,$04,$04,$0E
	DATA BYTE $00,$00,$38,$7E,$72,$70,$E0,$E0
	DATA BYTE $E0,$E0,$C0,$C0,$20,$60,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$20,$71,$FF
	DATA BYTE $7F,$3F,$1F,$07,$04,$08,$10,$38
	DATA BYTE $00,$00,$38,$7E,$72,$70,$E0,$E0
	DATA BYTE $E0,$E0,$C0,$00,$80,$80,$80,$E0
	DATA BYTE $00,$00,$00,$00,$00,$20,$71,$FF
	DATA BYTE $7F,$3F,$1F,$0F,$10,$30,$00,$01
	DATA BYTE $00,$00,$38,$7E,$72,$70,$E0,$E0
	DATA BYTE $E0,$E0,$C0,$80,$80,$80,$80,$C0
	DATA BYTE $00,$00,$00,$00,$00,$20,$71,$FF
	DATA BYTE $7F,$3F,$1F,$03,$01,$00,$00,$00
	DATA BYTE $00,$00,$38,$7E,$72,$70,$E0,$E0
	DATA BYTE $E0,$E0,$C0,$80,$40,$A0,$50,$7C
	DATA BYTE $70,$70,$60,$20,$30,$30,$71,$FF
	DATA BYTE $7F,$3F,$1F,$0F,$1C,$00,$00,$00
	DATA BYTE $00,$00,$38,$7E,$72,$70,$E0,$E0
	DATA BYTE $E0,$E0,$C0,$C0,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$20,$71,$FF
	DATA BYTE $7F,$3F,$1F,$0F,$1F,$03,$00,$00
	DATA BYTE $00,$00,$38,$7E,$72,$70,$E0,$E0
	DATA BYTE $E0,$E0,$C0,$C0,$C0,$80,$00,$00

spr_buz_l:	' the knights' BUZZARD facing LEFT: stand, run1, run2, run3, run4, skid, up, down
	DATA BYTE $00,$00,$1C,$7E,$4E,$0E,$07,$07
	DATA BYTE $07,$07,$03,$03,$02,$02,$02,$07
	DATA BYTE $00,$00,$00,$00,$00,$04,$8E,$FF
	DATA BYTE $FE,$FC,$F8,$60,$20,$20,$20,$70
	DATA BYTE $00,$00,$1C,$7E,$4E,$0E,$07,$07
	DATA BYTE $07,$07,$03,$01,$02,$04,$08,$38
	DATA BYTE $00,$00,$00,$00,$00,$04,$8E,$FF
	DATA BYTE $FE,$FC,$F8,$E0,$30,$08,$04,$0E
	DATA BYTE $00,$00,$1C,$7E,$4E,$0E,$07,$07
	DATA BYTE $07,$07,$03,$03,$04,$06,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$04,$8E,$FF
	DATA BYTE $FE,$FC,$F8,$E0,$20,$20,$20,$70
	DATA BYTE $00,$00,$1C,$7E,$4E,$0E,$07,$07
	DATA BYTE $07,$07,$03,$00,$01,$01,$01,$07
	DATA BYTE $00,$00,$00,$00,$00,$04,$8E,$FF
	DATA BYTE $FE,$FC,$F8,$E0,$20,$10,$08,$1C
	DATA BYTE $00,$00,$1C,$7E,$4E,$0E,$07,$07
	DATA BYTE $07,$07,$03,$01,$01,$01,$01,$03
	DATA BYTE $00,$00,$00,$00,$00,$04,$8E,$FF
	DATA BYTE $FE,$FC,$F8,$F0,$08,$0C,$00,$80
	DATA BYTE $00,$00,$1C,$7E,$4E,$0E,$07,$07
	DATA BYTE $07,$07,$03,$01,$02,$05,$0A,$3E
	DATA BYTE $00,$00,$00,$00,$00,$04,$8E,$FF
	DATA BYTE $FE,$FC,$F8,$C0,$80,$00,$00,$00
	DATA BYTE $00,$00,$1C,$7E,$4E,$0E,$07,$07
	DATA BYTE $07,$07,$03,$03,$00,$00,$00,$00
	DATA BYTE $0E,$0E,$06,$04,$0C,$0C,$8E,$FF
	DATA BYTE $FE,$FC,$F8,$F0,$38,$00,$00,$00
	DATA BYTE $00,$00,$1C,$7E,$4E,$0E,$07,$07
	DATA BYTE $07,$07,$03,$03,$03,$01,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$04,$8E,$FF
	DATA BYTE $FE,$FC,$F8,$F0,$F8,$C0,$00,$00

spr_rider:	' the rider, facing right then left -- drawn 4 px above his mount
	DATA BYTE $00,$00,$06,$0F,$0F,$0F,$1F,$1E
	DATA BYTE $0E,$0C,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$FF,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$FF,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$60,$F0,$F0,$F0,$F8,$78
	DATA BYTE $70,$30,$00,$00,$00,$00,$00,$00

spr_egg:	' egg
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$07
	DATA BYTE $0F,$0F,$0F,$1F,$1F,$0F,$0F,$07
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$80
	DATA BYTE $C0,$C0,$C0,$E0,$E0,$C0,$C0,$80

spr_egg_x:	' egg, cracked -- about to hatch
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$07
	DATA BYTE $0D,$0B,$0E,$1D,$1B,$0F,$0D,$07
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$80
	DATA BYTE $C0,$C0,$C0,$F0,$F0,$60,$C0,$80

spr_runner:	' unhorsed knight, on foot, facing right then left
	DATA BYTE $00,$00,$00,$00,$00,$00,$02,$02
	DATA BYTE $02,$02,$03,$02,$02,$02,$02,$02
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$60
	DATA BYTE $F0,$F0,$F0,$F0,$F0,$90,$90,$D8
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$06
	DATA BYTE $0F,$0F,$0F,$0F,$0F,$09,$09,$1B
	DATA BYTE $00,$00,$00,$00,$00,$00,$40,$40
	DATA BYTE $40,$40,$C0,$40,$40,$40,$40,$40

spr_hand:	' the lava troll's hand
	DATA BYTE $00,$00,$63,$63,$67,$77,$7F,$7F
	DATA BYTE $3F,$3F,$1F,$1F,$0F,$0F,$07,$07
	DATA BYTE $00,$00,$18,$18,$38,$38,$F8,$F8
	DATA BYTE $F8,$F0,$F0,$E0,$C0,$C0,$80,$80

spr_arm:	' the troll's forearm -- angled, not a second hand
	DATA BYTE $03,$07,$07,$0F,$0F,$1F,$1E,$3E
	DATA BYTE $3C,$7C,$78,$F8,$F0,$E0,$00,$00
	DATA BYTE $C0,$C0,$80,$80,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00

spr_pt:	' pterodactyl: shut, OPEN facing right; shut, OPEN facing left
	DATA BYTE $00,$00,$80,$C0,$70,$3C,$1F,$FF
	DATA BYTE $7F,$0F,$0C,$18,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$0C,$1F,$F8
	DATA BYTE $F0,$C0,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$1F,$FF
	DATA BYTE $7F,$3F,$7B,$E6,$C0,$80,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$0C,$1F,$F0
	DATA BYTE $F7,$CC,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$30,$F8,$1F
	DATA BYTE $0F,$03,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$01,$03,$0E,$3C,$F8,$FF
	DATA BYTE $FE,$F0,$30,$18,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$30,$F8,$0F
	DATA BYTE $EF,$33,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$F8,$FF
	DATA BYTE $FE,$FC,$DE,$67,$03,$01,$00,$00

chr_plat_l:	' plat_l
	DATA BYTE $FF,$FF,$3F,$0F,$02,$00,$00,$00

chr_plat_m:	' plat_m
	DATA BYTE $FF,$FF,$FF,$FF,$76,$22,$00,$00

chr_plat_r:	' plat_r
	DATA BYTE $FF,$FF,$FC,$F0,$40,$00,$00,$00

chr_lava_a:	' lava_a
	DATA BYTE $10,$32,$36,$7E,$FF,$FF,$FF,$FF

chr_lava_b:	' lava_b
	DATA BYTE $02,$46,$66,$F7,$FF,$FF,$FF,$FF

chr_lava_c:	' lava_c
	DATA BYTE $FF,$FF,$CF,$FF,$FF,$FC,$FF,$FF

chr_life:	' life
	DATA BYTE $30,$78,$78,$30,$7C,$FE,$36,$63

chr_pad:	' pad
	DATA BYTE $FF,$FF,$FF,$FF,$FE,$7E,$3E,$3C

chr_rock:	' rock
	DATA BYTE $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF

chr_egg:	' egg
	DATA BYTE $3C,$7E,$7E,$FF,$FF,$7E,$7E,$3C

chr_rock_l:	' rock_l
	DATA BYTE $FF,$7F,$7F,$3F,$3F,$1F,$1F,$0F

chr_rock_r:	' rock_r
	DATA BYTE $FF,$FE,$FE,$FC,$FC,$F8,$F8,$F0

chr_plat_m2:	' plat_m2
	DATA BYTE $FF,$FF,$FF,$FF,$FE,$7E,$3E,$3C

chr_und1l:	' und1l
	DATA BYTE $30,$20,$00,$00,$00,$00,$00,$00

chr_und1r:	' und1r
	DATA BYTE $1C,$08,$08,$00,$00,$00,$00,$00

chr_und2:	' und2
	DATA BYTE $3C,$18,$10,$00,$00,$00,$00,$00

chr_und3a:	' und3a
	DATA BYTE $38,$30,$10,$10,$00,$00,$00,$00

chr_und3b:	' und3b
	DATA BYTE $2C,$24,$04,$00,$00,$00,$00,$00

chr_floor:	' floor
	DATA BYTE $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF

chr_pad_floor:	' pad_floor
	DATA BYTE $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF

col_chars:	' their colours, 8 bytes each, same order
	DATA BYTE $A1,$61,$61,$61,$61,$61,$61,$61
	DATA BYTE $A1,$61,$61,$61,$61,$61,$61,$61
	DATA BYTE $A1,$61,$61,$61,$61,$61,$61,$61
	DATA BYTE $B1,$B1,$A1,$A1,$8A,$8A,$86,$68
	DATA BYTE $B1,$B1,$A1,$A1,$8A,$8A,$86,$68
	DATA BYTE $89,$89,$89,$89,$89,$89,$89,$89
	DATA BYTE $B1,$B1,$B1,$B1,$B1,$B1,$B1,$B1
	DATA BYTE $F1,$E1,$61,$61,$61,$61,$61,$61
	DATA BYTE $61,$61,$61,$A1,$61,$61,$61,$61
	DATA BYTE $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
	DATA BYTE $61,$61,$61,$A1,$68,$68,$68,$68
	DATA BYTE $61,$61,$61,$A1,$68,$68,$68,$68
	DATA BYTE $A1,$61,$61,$61,$61,$61,$61,$61
	DATA BYTE $61,$61,$61,$61,$61,$61,$61,$61
	DATA BYTE $61,$61,$61,$61,$61,$61,$61,$61
	DATA BYTE $61,$61,$61,$61,$61,$61,$61,$61
	DATA BYTE $61,$61,$61,$61,$61,$61,$61,$61
	DATA BYTE $61,$61,$61,$61,$61,$61,$61,$61
	DATA BYTE $A1,$61,$61,$61,$61,$61,$61,$61
	DATA BYTE $F1,$E1,$61,$61,$61,$61,$61,$61

flame0:	' lava flame, frame 0
	DATA BYTE $10,$32,$36,$7E,$FF,$FF,$FF,$FF

flame1:	' lava flame, frame 1
	DATA BYTE $20,$24,$76,$7E,$FF,$FF,$FF,$FF

flame2:	' lava flame, frame 2
	DATA BYTE $00,$42,$67,$F7,$FF,$FF,$FF,$FF

flame3:	' lava flame, frame 3
	DATA BYTE $04,$44,$4E,$EE,$FF,$FF,$FF,$FF

	' TITLE LOGO: 36 tiles from character 160, their colours, and the
	' 20 x 3 name map (32 = an empty tile).
	CONST LOGON = 36
logo_chr:	' logo tiles
	DATA BYTE $7F,$FF,$FF,$7F,$00,$00,$00,$00
	DATA BYTE $FF,$FF,$FF,$FF,$3F,$3F,$3F,$3F
	DATA BYTE $E0,$F0,$F0,$E0,$C0,$C0,$C0,$C0
	DATA BYTE $00,$00,$01,$03,$07,$0F,$1F,$3F
	DATA BYTE $7F,$FF,$FF,$FF,$C0,$C0,$C0,$C0
	DATA BYTE $FE,$FF,$FF,$FF,$03,$03,$03,$03
	DATA BYTE $00,$00,$80,$C0,$E0,$F0,$F8,$FC
	DATA BYTE $06,$0F,$1F,$3F,$3F,$3F,$3F,$3F
	DATA BYTE $00,$00,$80,$C0,$C0,$C0,$C0,$C0
	DATA BYTE $00,$00,$01,$03,$03,$03,$03,$03
	DATA BYTE $60,$F0,$F8,$FC,$FC,$FC,$FC,$FC
	DATA BYTE $00,$00,$01,$03,$07,$0F,$0F,$07
	DATA BYTE $FF,$FF,$FF,$FF,$00,$00,$00,$00
	DATA BYTE $E0,$F0,$F0,$E0,$00,$00,$00,$00
	DATA BYTE $07,$0F,$0F,$07,$00,$00,$00,$00
	DATA BYTE $FF,$FF,$FF,$FF,$FC,$FC,$FC,$FC
	DATA BYTE $00,$00,$00,$00,$06,$0F,$1F,$3F
	DATA BYTE $00,$00,$00,$00,$00,$00,$80,$C0
	DATA BYTE $3F,$3F,$3F,$3F,$3F,$3F,$3F,$3F
	DATA BYTE $C0,$C0,$C0,$C0,$C0,$C0,$C0,$C0
	DATA BYTE $03,$03,$03,$03,$03,$03,$03,$03
	DATA BYTE $FC,$FC,$FC,$FC,$FC,$FC,$FC,$FC
	DATA BYTE $03,$01,$00,$00,$00,$00,$00,$00
	DATA BYTE $FF,$FF,$FF,$7F,$00,$00,$00,$00
	DATA BYTE $FE,$FF,$FF,$FF,$03,$03,$03,$03
	DATA BYTE $00,$00,$80,$C0,$E0,$F0,$F8,$FC
	DATA BYTE $3F,$1F,$0F,$07,$03,$01,$00,$00
	DATA BYTE $C0,$C0,$C0,$C0,$FF,$FF,$FF,$7F
	DATA BYTE $3F,$3F,$3F,$3E,$FC,$F8,$F0,$E0
	DATA BYTE $C0,$80,$00,$00,$00,$00,$00,$00
	DATA BYTE $03,$03,$03,$03,$FF,$FF,$FF,$FE
	DATA BYTE $FC,$F8,$F0,$E0,$C0,$80,$00,$00
	DATA BYTE $00,$00,$00,$00,$07,$0F,$0F,$07
	DATA BYTE $00,$00,$00,$00,$FF,$FF,$FF,$FF
	DATA BYTE $3F,$3F,$3F,$3F,$3F,$1F,$0F,$07
	DATA BYTE $FC,$FC,$FC,$FC,$FC,$F8,$F0,$E0

logo_col:	' logo tile colours
	DATA BYTE $F1,$B1,$B1,$B1,$B1,$B1,$B1,$A1
	DATA BYTE $F1,$B1,$B1,$B1,$B1,$B1,$B1,$A1
	DATA BYTE $F1,$B1,$B1,$B1,$B1,$B1,$B1,$A1
	DATA BYTE $F1,$B1,$B1,$B1,$B1,$B1,$B1,$A1
	DATA BYTE $F1,$B1,$B1,$B1,$B1,$B1,$B1,$A1
	DATA BYTE $F1,$B1,$B1,$B1,$B1,$B1,$B1,$A1
	DATA BYTE $F1,$B1,$B1,$B1,$B1,$B1,$B1,$A1
	DATA BYTE $F1,$B1,$B1,$B1,$B1,$B1,$B1,$A1
	DATA BYTE $F1,$B1,$B1,$B1,$B1,$B1,$B1,$A1
	DATA BYTE $F1,$B1,$B1,$B1,$B1,$B1,$B1,$A1
	DATA BYTE $F1,$B1,$B1,$B1,$B1,$B1,$B1,$A1
	DATA BYTE $F1,$B1,$B1,$B1,$B1,$B1,$B1,$A1
	DATA BYTE $F1,$B1,$B1,$B1,$B1,$B1,$B1,$A1
	DATA BYTE $F1,$B1,$B1,$B1,$B1,$B1,$B1,$A1
	DATA BYTE $F1,$B1,$B1,$B1,$B1,$B1,$B1,$A1
	DATA BYTE $F1,$B1,$B1,$B1,$B1,$B1,$B1,$A1
	DATA BYTE $A1,$A1,$A1,$A1,$91,$91,$91,$91
	DATA BYTE $A1,$A1,$A1,$A1,$91,$91,$91,$91
	DATA BYTE $A1,$A1,$A1,$A1,$91,$91,$91,$91
	DATA BYTE $A1,$A1,$A1,$A1,$91,$91,$91,$91
	DATA BYTE $A1,$A1,$A1,$A1,$91,$91,$91,$91
	DATA BYTE $A1,$A1,$A1,$A1,$91,$91,$91,$91
	DATA BYTE $A1,$A1,$A1,$A1,$91,$91,$91,$91
	DATA BYTE $A1,$A1,$A1,$A1,$91,$91,$91,$91
	DATA BYTE $A1,$A1,$A1,$A1,$91,$91,$91,$91
	DATA BYTE $A1,$A1,$A1,$A1,$91,$91,$91,$91
	DATA BYTE $91,$81,$81,$81,$81,$61,$61,$61
	DATA BYTE $91,$81,$81,$81,$81,$61,$61,$61
	DATA BYTE $91,$81,$81,$81,$81,$61,$61,$61
	DATA BYTE $91,$81,$81,$81,$81,$61,$61,$61
	DATA BYTE $91,$81,$81,$81,$81,$61,$61,$61
	DATA BYTE $91,$81,$81,$81,$81,$61,$61,$61
	DATA BYTE $91,$81,$81,$81,$81,$61,$61,$61
	DATA BYTE $91,$81,$81,$81,$81,$61,$61,$61
	DATA BYTE $91,$81,$81,$81,$81,$61,$61,$61
	DATA BYTE $91,$81,$81,$81,$81,$61,$61,$61

logo_map:	' logo name map, 20 x 3
	DATA BYTE $20,$A0,$A1,$A2,$A3,$A4,$A5,$A6
	DATA BYTE $A7,$A8,$A9,$AA,$AB,$A4,$AC,$AD
	DATA BYTE $AE,$A1,$AF,$AD,$B0,$B1,$B2,$B3
	DATA BYTE $B2,$B3,$B4,$B5,$B2,$B3,$B4,$B5
	DATA BYTE $B6,$B7,$B8,$B9,$20,$B2,$B5,$20
	DATA BYTE $BA,$BB,$BC,$BD,$BA,$BB,$BE,$BF
	DATA BYTE $BA,$BB,$BE,$BF,$C0,$C1,$BE,$BF
	DATA BYTE $20,$C2,$C3,$20

