	' JOUST art -- GENERATED by assets/genart.py. Do not edit; regenerate.
	'
	' Sprites are QUADRANT-ORDERED for the TMS9918: 16 rows of the left half then
	' 16 rows of the right half. Each mount is stored twice, facing right and facing
	' left, because the VDP cannot mirror a sprite.
	'
	' Every block is an EVEN number of bytes -- an odd DATA BYTE run misaligns every
	' word table after it (TRUNCATION.md 1d).

spr_mount_r:	' ostrich/buzzard facing RIGHT: up, mid, down, skid
	DATA BYTE $00,$00,$00,$00,$1F,$31,$60,$C0
	DATA BYTE $1F,$3F,$7F,$3F,$0C,$18,$30,$00
	DATA BYTE $60,$F0,$F0,$60,$E0,$EC,$FF,$FE
	DATA BYTE $F8,$F0,$E0,$C0,$C0,$60,$30,$00
	DATA BYTE $00,$00,$00,$00,$03,$07,$0F,$FF
	DATA BYTE $FF,$7F,$3F,$1F,$0C,$18,$30,$00
	DATA BYTE $60,$F0,$F0,$60,$F0,$FC,$FF,$FE
	DATA BYTE $FC,$F0,$E0,$C0,$C0,$60,$30,$00
	DATA BYTE $00,$00,$00,$00,$03,$03,$07,$0F
	DATA BYTE $3F,$7F,$C7,$07,$0C,$18,$30,$00
	DATA BYTE $60,$F0,$F0,$60,$F0,$FC,$FF,$FE
	DATA BYTE $FC,$F8,$F0,$F0,$C0,$60,$30,$00
	DATA BYTE $00,$00,$00,$00,$03,$07,$0F,$FF
	DATA BYTE $FF,$7F,$3F,$1F,$1C,$30,$70,$00
	DATA BYTE $60,$F0,$F0,$60,$F0,$FC,$FF,$FE
	DATA BYTE $FC,$F0,$E0,$C0,$E0,$30,$38,$00

spr_mount_l:	' the same four, facing LEFT
	DATA BYTE $06,$0F,$0F,$06,$07,$37,$FF,$7F
	DATA BYTE $1F,$0F,$07,$03,$03,$06,$0C,$00
	DATA BYTE $00,$00,$00,$00,$F8,$8C,$06,$03
	DATA BYTE $F8,$FC,$FE,$FC,$30,$18,$0C,$00
	DATA BYTE $06,$0F,$0F,$06,$0F,$3F,$FF,$7F
	DATA BYTE $3F,$0F,$07,$03,$03,$06,$0C,$00
	DATA BYTE $00,$00,$00,$00,$C0,$E0,$F0,$FF
	DATA BYTE $FF,$FE,$FC,$F8,$30,$18,$0C,$00
	DATA BYTE $06,$0F,$0F,$06,$0F,$3F,$FF,$7F
	DATA BYTE $3F,$1F,$0F,$0F,$03,$06,$0C,$00
	DATA BYTE $00,$00,$00,$00,$C0,$C0,$E0,$F0
	DATA BYTE $FC,$FE,$E3,$E0,$30,$18,$0C,$00
	DATA BYTE $06,$0F,$0F,$06,$0F,$3F,$FF,$7F
	DATA BYTE $3F,$0F,$07,$03,$07,$0C,$1C,$00
	DATA BYTE $00,$00,$00,$00,$C0,$E0,$F0,$FF
	DATA BYTE $FF,$FE,$FC,$F8,$38,$0C,$0E,$00

spr_egg:	' egg
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $07,$0F,$1F,$1F,$1F,$0F,$07,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $80,$C0,$E0,$E0,$E0,$C0,$80,$00

spr_runner:	' unhorsed knight, on foot
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $03,$03,$0F,$17,$07,$04,$0C,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $00,$00,$C0,$A0,$80,$80,$C0,$00

spr_egg_x:	' egg, cracked -- about to hatch
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $06,$0D,$1D,$1B,$1E,$0E,$05,$00
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00
	DATA BYTE $80,$C0,$E0,$E0,$E0,$C0,$80,$00

chr_plat_l:	' plat_l
	DATA BYTE $7F,$FF,$C0,$C0,$C0,$C0,$40,$00

chr_plat_m:	' plat_m
	DATA BYTE $FF,$FF,$00,$00,$00,$00,$00,$00

chr_plat_r:	' plat_r
	DATA BYTE $FE,$FF,$03,$03,$03,$03,$02,$00

chr_lava_a:	' lava_a
	DATA BYTE $99,$FF,$FF,$FF,$FF,$FF,$FF,$FF

chr_lava_b:	' lava_b
	DATA BYTE $66,$FF,$FF,$FF,$FF,$FF,$FF,$FF

chr_lava_c:	' lava_c
	DATA BYTE $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF

chr_life:	' life
	DATA BYTE $30,$78,$78,$30,$7C,$FE,$36,$63

chr_pad:	' pad
	DATA BYTE $FF,$FF,$DB,$81,$00,$00,$00,$00

