	' JOUST font -- GENERATED by assets/genfont.py. Do not edit; regenerate.
	'
	' Characters 32-90 (59 of them), 8 bytes each = 472 bytes. Williams' cabinet face:
	' heavy, squared, flat terminals, no serifs -- drawn 5x7 inside the 8x8 cell so a
	' blank column at the right and a blank row at the bottom keep it legible.
	'
	' Loaded with DEFINE CHAR 32,59,font_bits. The run must be CONTIGUOUS, so slots
	' with no glyph emit blanks rather than being skipped -- a gap would shift every
	' letter after it.

font_bits:
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00	' space
	DATA BYTE $20,$20,$20,$20,$20,$00,$20,$00	' !
	DATA BYTE $50,$50,$00,$00,$00,$00,$00,$00	' "
	DATA BYTE $50,$F8,$50,$50,$F8,$50,$00,$00	' #
	DATA BYTE $20,$78,$A0,$70,$28,$F0,$20,$00	' $
	DATA BYTE $C8,$C8,$10,$20,$40,$98,$98,$00	' %
	DATA BYTE $60,$90,$A0,$40,$A8,$90,$68,$00	' &
	DATA BYTE $20,$20,$00,$00,$00,$00,$00,$00	' '
	DATA BYTE $10,$20,$40,$40,$40,$20,$10,$00	' (
	DATA BYTE $40,$20,$10,$10,$10,$20,$40,$00	' )
	DATA BYTE $00,$A8,$70,$F8,$70,$A8,$00,$00	' *
	DATA BYTE $00,$20,$20,$F8,$20,$20,$00,$00	' +
	DATA BYTE $00,$00,$00,$00,$60,$60,$40,$00	' ,
	DATA BYTE $00,$00,$00,$F8,$00,$00,$00,$00	' -
	DATA BYTE $00,$00,$00,$00,$00,$60,$60,$00	' .
	DATA BYTE $08,$08,$10,$20,$40,$80,$80,$00	' /
	DATA BYTE $70,$88,$98,$A8,$C8,$88,$70,$00	' 0
	DATA BYTE $20,$60,$20,$20,$20,$20,$70,$00	' 1
	DATA BYTE $70,$88,$08,$30,$40,$80,$F8,$00	' 2
	DATA BYTE $F0,$08,$08,$70,$08,$08,$F0,$00	' 3
	DATA BYTE $10,$30,$50,$90,$F8,$10,$10,$00	' 4
	DATA BYTE $F8,$80,$F0,$08,$08,$88,$70,$00	' 5
	DATA BYTE $70,$80,$80,$F0,$88,$88,$70,$00	' 6
	DATA BYTE $F8,$08,$10,$20,$40,$40,$40,$00	' 7
	DATA BYTE $70,$88,$88,$70,$88,$88,$70,$00	' 8
	DATA BYTE $70,$88,$88,$78,$08,$08,$70,$00	' 9
	DATA BYTE $00,$60,$60,$00,$60,$60,$00,$00	' :
	DATA BYTE $00,$60,$60,$00,$60,$60,$40,$00	' ;
	DATA BYTE $10,$20,$40,$80,$40,$20,$10,$00	' <
	DATA BYTE $00,$00,$F8,$00,$F8,$00,$00,$00	' =
	DATA BYTE $40,$20,$10,$08,$10,$20,$40,$00	' >
	DATA BYTE $70,$88,$08,$30,$20,$00,$20,$00	' ?
	DATA BYTE $70,$88,$B8,$A8,$B8,$80,$70,$00	' @
	DATA BYTE $70,$88,$88,$88,$F8,$88,$88,$00	' A
	DATA BYTE $F0,$88,$88,$F0,$88,$88,$F0,$00	' B
	DATA BYTE $70,$88,$80,$80,$80,$88,$70,$00	' C
	DATA BYTE $E0,$90,$88,$88,$88,$90,$E0,$00	' D
	DATA BYTE $F8,$80,$80,$F0,$80,$80,$F8,$00	' E
	DATA BYTE $F8,$80,$80,$F0,$80,$80,$80,$00	' F
	DATA BYTE $70,$88,$80,$B8,$88,$88,$78,$00	' G
	DATA BYTE $88,$88,$88,$F8,$88,$88,$88,$00	' H
	DATA BYTE $70,$20,$20,$20,$20,$20,$70,$00	' I
	DATA BYTE $38,$10,$10,$10,$90,$90,$60,$00	' J
	DATA BYTE $88,$90,$A0,$C0,$A0,$90,$88,$00	' K
	DATA BYTE $80,$80,$80,$80,$80,$80,$F8,$00	' L
	DATA BYTE $88,$D8,$A8,$A8,$88,$88,$88,$00	' M
	DATA BYTE $88,$C8,$A8,$A8,$98,$88,$88,$00	' N
	DATA BYTE $70,$88,$88,$88,$88,$88,$70,$00	' O
	DATA BYTE $F0,$88,$88,$F0,$80,$80,$80,$00	' P
	DATA BYTE $70,$88,$88,$88,$A8,$90,$68,$00	' Q
	DATA BYTE $F0,$88,$88,$F0,$A0,$90,$88,$00	' R
	DATA BYTE $78,$80,$80,$70,$08,$08,$F0,$00	' S
	DATA BYTE $F8,$20,$20,$20,$20,$20,$20,$00	' T
	DATA BYTE $88,$88,$88,$88,$88,$88,$70,$00	' U
	DATA BYTE $88,$88,$88,$88,$88,$50,$20,$00	' V
	DATA BYTE $88,$88,$88,$A8,$A8,$D8,$88,$00	' W
	DATA BYTE $88,$88,$50,$20,$50,$88,$88,$00	' X
	DATA BYTE $88,$88,$50,$20,$20,$20,$20,$00	' Y
	DATA BYTE $F8,$08,$10,$20,$40,$80,$F8,$00	' Z
