	' JOUST font -- GENERATED by assets/genfont.py. Do not edit; regenerate.
	'
	' Characters 32-90 (59 of them), 8 bytes each = 472 bytes. Williams' cabinet face:
	' heavy, squared, flat terminals, no serifs -- drawn 5x7 inside the 8x8 cell so a
	' blank column at the right and a blank row at the bottom keep it legible.
	'
	' Loaded with DEFINE CHAR 32,59,font_bits. The run must be CONTIGUOUS, so slots
	' with no glyph emit blanks rather than being skipped -- a gap would shift every
	' letter after it.

font_bits:
	DATA BYTE $00,$00,$00,$00,$00,$00,$00,$00	' space
	DATA BYTE $30,$30,$30,$30,$30,$00,$30,$00	' !
	DATA BYTE $50,$50,$00,$00,$00,$00,$00,$00	' "
	DATA BYTE $50,$F8,$50,$50,$F8,$50,$00,$00	' #
	DATA BYTE $20,$78,$A0,$70,$28,$F0,$20,$00	' $
	DATA BYTE $C8,$C8,$10,$20,$40,$98,$98,$00	' %
	DATA BYTE $70,$D8,$D8,$70,$DC,$D8,$74,$00	' &
	DATA BYTE $30,$30,$00,$00,$00,$00,$00,$00	' '
	DATA BYTE $18,$30,$60,$60,$60,$30,$18,$00	' (
	DATA BYTE $60,$30,$18,$18,$18,$30,$60,$00	' )
	DATA BYTE $00,$CC,$78,$FC,$78,$CC,$00,$00	' *
	DATA BYTE $00,$20,$20,$F8,$20,$20,$00,$00	' +
	DATA BYTE $00,$00,$00,$00,$60,$60,$40,$00	' ,
	DATA BYTE $00,$00,$00,$FC,$00,$00,$00,$00	' -
	DATA BYTE $00,$00,$00,$00,$00,$60,$60,$00	' .
	DATA BYTE $0C,$18,$18,$30,$60,$60,$C0,$00	' /
	DATA BYTE $78,$CC,$DC,$EC,$CC,$CC,$78,$00	' 0
	DATA BYTE $30,$70,$30,$30,$30,$30,$78,$00	' 1
	DATA BYTE $78,$CC,$0C,$38,$60,$C0,$FC,$00	' 2
	DATA BYTE $F8,$0C,$0C,$78,$0C,$0C,$F8,$00	' 3
	DATA BYTE $18,$38,$78,$D8,$FC,$18,$18,$00	' 4
	DATA BYTE $FC,$C0,$F8,$0C,$0C,$CC,$78,$00	' 5
	DATA BYTE $78,$C0,$C0,$F8,$CC,$CC,$78,$00	' 6
	DATA BYTE $FC,$0C,$18,$30,$60,$60,$60,$00	' 7
	DATA BYTE $78,$CC,$CC,$78,$CC,$CC,$78,$00	' 8
	DATA BYTE $78,$CC,$CC,$7C,$0C,$0C,$78,$00	' 9
	DATA BYTE $00,$60,$60,$00,$60,$60,$00,$00	' :
	DATA BYTE $00,$60,$60,$00,$60,$60,$40,$00	' ;
	DATA BYTE $10,$20,$40,$80,$40,$20,$10,$00	' <
	DATA BYTE $00,$00,$F8,$00,$F8,$00,$00,$00	' =
	DATA BYTE $40,$20,$10,$08,$10,$20,$40,$00	' >
	DATA BYTE $70,$88,$08,$30,$20,$00,$20,$00	' ?
	DATA BYTE $70,$88,$B8,$A8,$B8,$80,$70,$00	' @
	DATA BYTE $30,$78,$CC,$CC,$FC,$CC,$CC,$00	' A
	DATA BYTE $F8,$CC,$CC,$F8,$CC,$CC,$F8,$00	' B
	DATA BYTE $78,$CC,$C0,$C0,$C0,$CC,$78,$00	' C
	DATA BYTE $F0,$D8,$CC,$CC,$CC,$D8,$F0,$00	' D
	DATA BYTE $FC,$C0,$C0,$F8,$C0,$C0,$FC,$00	' E
	DATA BYTE $FC,$C0,$C0,$F8,$C0,$C0,$C0,$00	' F
	DATA BYTE $78,$CC,$C0,$DC,$CC,$CC,$7C,$00	' G
	DATA BYTE $CC,$CC,$CC,$FC,$CC,$CC,$CC,$00	' H
	DATA BYTE $FC,$30,$30,$30,$30,$30,$FC,$00	' I
	DATA BYTE $3C,$0C,$0C,$0C,$CC,$CC,$78,$00	' J
	DATA BYTE $CC,$D8,$F0,$E0,$F0,$D8,$CC,$00	' K
	DATA BYTE $C0,$C0,$C0,$C0,$C0,$C0,$FC,$00	' L
	DATA BYTE $C6,$EE,$FE,$D6,$C6,$C6,$C6,$00	' M
	DATA BYTE $CC,$EC,$FC,$DC,$CC,$CC,$CC,$00	' N
	DATA BYTE $78,$CC,$CC,$CC,$CC,$CC,$78,$00	' O
	DATA BYTE $F8,$CC,$CC,$F8,$C0,$C0,$C0,$00	' P
	DATA BYTE $78,$CC,$CC,$CC,$DC,$D8,$6C,$00	' Q
	DATA BYTE $F8,$CC,$CC,$F8,$F0,$D8,$CC,$00	' R
	DATA BYTE $78,$CC,$C0,$78,$0C,$CC,$78,$00	' S
	DATA BYTE $FC,$30,$30,$30,$30,$30,$30,$00	' T
	DATA BYTE $CC,$CC,$CC,$CC,$CC,$CC,$78,$00	' U
	DATA BYTE $CC,$CC,$CC,$CC,$CC,$78,$30,$00	' V
	DATA BYTE $C6,$C6,$C6,$D6,$FE,$EE,$C6,$00	' W
	DATA BYTE $CC,$CC,$78,$30,$78,$CC,$CC,$00	' X
	DATA BYTE $CC,$CC,$CC,$78,$30,$30,$30,$00	' Y
	DATA BYTE $FC,$0C,$18,$30,$60,$C0,$FC,$00	' Z

	' Font colours: yellow to red down each glyph, 8 bytes a character.
font_col:
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
	DATA BYTE $B1,$B1,$B1,$A1,$A1,$91,$81,$81
