#!/usr/bin/env python3
"""No upload may write art into codes another table owns.

THE BUG THIS EXISTS FOR
-----------------------
Harry's standing pose has no slot of its own -- the sprite table is full -- so on
the TI `esc_stand` writes it OVER his running body at patterns 72..87 and
`esc_run` puts the run back. On the NES that swap went through `nes_def`, which
turns rendering off for about two frames, and mounting an escalator flashed the
whole screen.

The attempted fix was to make both facings RESIDENT, "at 176..207, a 32-code gap
nothing else uses". **There is no such gap.** 176..207 is `HLLEG1..4` and
`HLLEGS1..4` -- Harry's own left-facing leg bands. The setup upload wrote the
standing pose straight over them, so running LEFT drew standing art in the leg
slots: a detached striped block a dozen pixels below his feet, alternating with
the run cycle, plus a malformed Harry. Reported as *"a ball shaped thing drops
below his feet every other frame"*.

**Nothing failed.** The art loaded correctly, at the address it was given, and
every other gate passed. The real free space at the time was twelve patterns
against the sixteen per facing the pose needed -- so it was never available and
the claim was never checked against anything. This file PRINTS the free list on
every run for exactly that reason: the next reader is told rather than guessing.

WHY THE OTHER CHECKS COULD NOT SEE IT
-------------------------------------
`checkchars.py` was extended at the same time to verify `CONST P_HSTB` against
the `nchr` of the upload beside `VARPTR spr_hstand(0)`. That is two halves of one
mistake agreeing with each other: both said 176, so it passed. **A constant is
only checked when it is compared with something independent of it.** Here the
independent thing is genart's own table, which says who owns 176.

WHAT THIS CHECKS
----------------
Every upload in the program -- the NES `nchr`/`ncnt`/`ntab` form and the TI
`DEFINE CHAR`/`DEFINE SPRITE` form -- is resolved to a destination RANGE and a
SOURCE table, and the range must be owned by that source. Ownership comes from
genart for the sprites and from the three font/store loads for the characters.

Deliberate overwrites are real and are listed in BORROWS by name, with the reason
and the range. That is a NAMED EXEMPTION, not a loosened rule: a borrow outside
its declared range still fails, and a new borrow has to be written down.

Run:  python3 checkpat.py        exits non-zero on an overwrite
"""

import os
import re
import sys

import genart as g
import gennescolor as nesart

HERE = os.path.dirname(os.path.abspath(__file__))
BAS = os.path.join(HERE, "..", "src", "KEYSTONE.bas")

SPRITE_TABLE, CHAR_TABLE = 0, 1

# THE RUNTIME SWAPS, each of which overwrites a resident table ON PURPOSE.
#   label -> (table, first code, count, why)
BORROWS = {
    "store_nes_chr": (CHAR_TABLE, 96, len(g.CHARS),
                      "NES-native alternative to the TMS store tiles"),
    "spr_hstand":  (SPRITE_TABLE, 72, 16, "Harry's standing pose, over his "
                                          "running body while he rides"),
    "spr_hstandl": (SPRITE_TABLE, 72, 16, "the same pose facing the other way"),
    "spr_hbod4":   (SPRITE_TABLE, 72, 16, "the run put back when he steps off"),
    "esc_phw0": (CHAR_TABLE, 110, 6, "west flight, animation phase 0"),
    "esc_phw1": (CHAR_TABLE, 110, 6, "west flight, animation phase 1"),
    "esc_phw2": (CHAR_TABLE, 110, 6, "west flight, animation phase 2"),
    "esc_phw3": (CHAR_TABLE, 110, 6, "west flight, animation phase 3"),
    "esc_phe0": (CHAR_TABLE, 116, 6, "east flight, animation phase 0"),
    "esc_phe1": (CHAR_TABLE, 116, 6, "east flight, animation phase 1"),
    "esc_phe2": (CHAR_TABLE, 116, 6, "east flight, animation phase 2"),
    "esc_phe3": (CHAR_TABLE, 116, 6, "east flight, animation phase 3"),
    "bulb_lit": (CHAR_TABLE, None, 1, "one marquee lamp, code chosen at run time"),
    "bulb_off": (CHAR_TABLE, None, 1, "the lamp before it, likewise"),
}

# Variables used as a destination code, and the range they can take.
VAR_RANGE = {"bcode": ("BULB0", 4)}

CONST_RE = re.compile(r"^\s*CONST (CH_\w+|P_\w+)\s*=\s*(\d+)")
NCHR_RE = re.compile(r"^\s*nchr = (.+?)\s*(?:'.*)?$")
NCNT_RE = re.compile(r"^\s*ncnt = (\d+)")
NTAB_RE = re.compile(r"^\s*ntab = (\d+)")
VARPTR_RE = re.compile(r"VARPTR (\w+)\(0\)")
DEFCHAR_RE = re.compile(r"DEFINE CHAR (\w+),(\d+),(\w+)")
DEFSPR_RE = re.compile(r"DEFINE SPRITE (\d+),(\d+),(\w+)")


def owners():
    """code -> owning label, for both tables."""
    spr, chars = {}, {}
    for label, _a, _c in g.SPRITES:
        first, count = g.SPR_FIRST[label], g.SPR_FIRST[label + "_n"]
        for p in range(first, first + count * 4):
            spr[p] = label
    for p in range(g.CHARS_BASE if isinstance(getattr(g, "CHARS_BASE", 96), int)
                   else 96, 96 + len(g.CHARS)):
        chars[p] = "store_pat"
    # the two fonts are not generated by genart; their loads declare them
    #
    # AND THE RADAR CANVAS OWNS EVERYTHING FROM SCAN_FIRST UP, which no upload
    # declares: scan_wipe writes those patterns as RAW VRAM, every frame, so
    # nothing in the source looks like a claim on them. That invisibility cost
    # a session. A second font copy was put at 197..255 -- "free", said this
    # very file -- and the top 48 of those codes are the canvas, which scribbled
    # over the copy on the first frame. Eleven of the fifty-nine characters
    # survived and the HUD came out as bands of the wrong art.
    #
    # Taken from genart rather than written down, so moving SCAN_FIRST moves
    # this with it.
    for p in range(g.SCAN_FIRST, 256):
        chars.setdefault(p, "the radar canvas (genart.SCAN_FIRST)")
    for first, count, label in ((0, 32, "tfont_pat0"), (32, 59, "font_bits"),
                                (185, 12, "tfont_pat1")):
        for p in range(first, first + count):
            chars.setdefault(p, label)
    # NES 8x16 reserve icons select background-table tiles 198/199.
    for p in (198, 199):
        assert p not in chars, "HUD hats overlap another CHR owner"
        chars[p] = "hud_hat_pat"
    for p in nesart.DETAIL_CODES.values():
        assert p not in chars, "NES detail art overlaps another CHR owner"
        chars[p] = "detail_nes_chr"
    for p in range(92, 96):
        assert p not in chars, "Suitcase overlay overlaps another CHR owner"
        chars[p] = "suitcase_nes_chr"
    return {SPRITE_TABLE: spr, CHAR_TABLE: chars}


def free_runs(owned, limit=256):
    runs = []
    for p in range(limit):
        if p in owned:
            continue
        if runs and runs[-1][1] == p - 1:
            runs[-1][1] = p
        else:
            runs.append([p, p])
    return ", ".join("%d-%d" % (a, b) for a, b in runs) or "none"


SWAP_ROUTINE = "nes_swp16"


def check_swapper(src, bad):
    """The shared chunked uploader, whose SOURCE comes from its callers.

    `nes_swp16` writes the borrowed sixteen patterns in four queued chunks and
    is handed `#nsrc` by esc_stand or esc_run. Its own lines therefore have no
    VARPTR in reach and the generic rule cannot judge them -- so the routine is
    checked as a whole (does it tile exactly the borrowed range?) and its
    CALLERS are checked for what they point it at.

    Declaring it exempt instead would have been the same mistake as anchoring
    P_HSTB to its own upload: the thing that needs checking is precisely the
    destination, and it must be compared against something independent.
    """
    a = next((i for i, l in enumerate(src)
              if l.strip() == SWAP_ROUTINE + ":"), None)
    if a is None:
        bad.append("checkpat: no %s routine found -- if the chunked uploader "
                   "was renamed this check has stopped applying"
                   % SWAP_ROUTINE)
        return set()

    b = next((i for i in range(a + 1, len(src))
              if re.match(r"^[a-z_][a-z0-9_]*:", src[i])), len(src))
    lines = set(range(a, b))

    bases, cnt, tab = [], None, None
    for i in range(a, b):
        m = NCNT_RE.match(src[i])
        if m:
            cnt = int(m.group(1))
        m = NTAB_RE.match(src[i])
        if m:
            tab = int(m.group(1))
        m = NCHR_RE.match(src[i])
        if m:
            e = m.group(1).strip()
            if e in consts_global:
                bases.append(consts_global[e])
            elif re.match(r"^nchr \+ (\d+)$", e) and bases:
                bases.append(bases[-1] + int(e.split("+")[1]))

    want_tab, want_base, want_cnt, _why = BORROWS["spr_hstand"]
    covered = []
    for base in bases:
        covered.extend(range(base, base + (cnt or 0)))
    if tab != want_tab or sorted(covered) != list(
            range(want_base, want_base + want_cnt)):
        bad.append("%s writes table %s codes %s, but the borrow it exists to "
                   "perform is sprite patterns %d..%d. Four chunks of four must "
                   "tile that range exactly."
                   % (SWAP_ROUTINE, tab,
                      sorted(set(covered)) or "nothing",
                      want_base, want_base + want_cnt - 1))

    callers = 0
    for i, l in enumerate(src):
        if "GOSUB " + SWAP_ROUTINE not in l:
            continue
        callers += 1
        label = None
        for j in range(max(0, i - 6), i):
            m = VARPTR_RE.search(src[j])
            if m:
                label = m.group(1)
        if label is None:
            bad.append("line %d: GOSUB %s with no `VARPTR ...(0)` above it -- "
                       "it would upload whatever #nsrc happened to hold"
                       % (i + 1, SWAP_ROUTINE))
        elif label not in BORROWS:
            bad.append("line %d: GOSUB %s is handed %s, which is not one of the "
                       "declared borrows. It would write that table's art over "
                       "sprite patterns %d..%d."
                       % (i + 1, SWAP_ROUTINE, label, want_base,
                          want_base + want_cnt - 1))
    if callers == 0:
        bad.append("checkpat: nothing calls %s -- the borrow it performs is "
                   "either dead or has moved" % SWAP_ROUTINE)
    return lines


def main(path=None, quiet=False):
    src = open(path or BAS, encoding="utf-8").read().split("\n")
    consts = {}
    for ln in src:
        m = CONST_RE.match(ln)
        if m:
            consts[m.group(1)] = int(m.group(2))
    own = owners()
    bad, sites = [], []
    global consts_global
    consts_global = consts
    swap_lines = check_swapper(src, bad)

    # ---- the NES form: nchr / ncnt / ntab plus a VARPTR ------------------
    last_base = None
    for i, ln in enumerate(src):
        m = NCHR_RE.match(ln)
        if not m or i in swap_lines:
            continue
        expr = m.group(1).strip()
        ctx = src[max(0, i - 6):i + 8]
        cnt = next((int(x.group(1)) for c in ctx
                    for x in [NCNT_RE.match(c)] if x), None)
        tab = next((int(x.group(1)) for c in ctx
                    for x in [NTAB_RE.match(c)] if x), None)
        labels = [x.group(1) for c in ctx for x in [VARPTR_RE.search(c)]
                  if x and not x.group(1).startswith("nes_")]
        label = labels[0] if labels else None

        if expr.isdigit():
            base = int(expr)
        elif expr in consts:
            base = consts[expr]
        elif re.match(r"^nchr \+ (\d+)$", expr) and last_base is not None:
            base = last_base + int(re.match(r"^nchr \+ (\d+)$", expr).group(1))
            cnt = cnt if cnt is not None else sites[-1][2]
            tab = tab if tab is not None else sites[-1][3]
            label = label or sites[-1][4]
        elif expr in VAR_RANGE:
            cname, n = VAR_RANGE[expr]
            base, cnt = g.CODES[cname], n
        else:
            bad.append("line %d: `nchr = %s` cannot be resolved to a code, so "
                       "the range it writes cannot be checked. Give it a CONST "
                       "or add it to VAR_RANGE -- an upload this file cannot "
                       "measure is the one that overwrites something."
                       % (i + 1, expr))
            continue
        last_base = base
        if cnt is None or tab is None:
            bad.append("line %d: an upload at code %d has no ncnt/ntab nearby, "
                       "so its range and table are unknown" % (i + 1, base))
            continue
        sites.append((i, "upload", cnt, tab, label, base))

    # ---- the TI form -----------------------------------------------------
    for i, ln in enumerate(src):
        m = DEFCHAR_RE.search(ln)
        if m:
            first, cnt, label = m.group(1), int(m.group(2)), m.group(3)
            if first.isdigit():
                base = int(first)
            elif first in consts:
                base = consts[first]
            elif first in VAR_RANGE:
                cname, n = VAR_RANGE[first]
                base, cnt = g.CODES[cname], n
            else:
                bad.append("line %d: DEFINE CHAR at `%s`, which does not "
                           "resolve to a code" % (i + 1, first))
                continue
            sites.append((i, "DEFINE CHAR", cnt, CHAR_TABLE, label, base))
        m = DEFSPR_RE.search(ln)
        if m:
            # DEFINE SPRITE indexes SPRITES; a sprite is four patterns
            sites.append((i, "DEFINE SPRITE", int(m.group(2)) * 4,
                          SPRITE_TABLE, m.group(3), int(m.group(1)) * 4))

    # ---- the rule --------------------------------------------------------
    for i, kind, cnt, tab, label, base in sites:
        if label is None:
            bad.append("line %d: %s at %d has no source table in reach"
                       % (i + 1, kind, base))
            continue
        rng = range(base, base + cnt)
        if label in BORROWS:
            btab, bbase, bcnt, why = BORROWS[label]
            if bbase is None:
                continue                # code chosen at run time, range declared
            if tab != btab or base != bbase or cnt != bcnt:
                bad.append("line %d: %s is a declared BORROW (%s) of %s %d..%d, "
                           "but this writes %s %d..%d. A borrow outside its "
                           "declared range is the overwrite this file is for."
                           % (i + 1, label, why,
                              "sprites" if btab == SPRITE_TABLE else "chars",
                              bbase, bbase + bcnt - 1,
                              "sprites" if tab == SPRITE_TABLE else "chars",
                              base, base + cnt - 1))
            continue
        clash = sorted(set(own[tab][p] for p in rng
                           if p in own[tab] and own[tab][p] != label))
        if clash:
            bad.append(
                "line %d: %s writes %s %d..%d from %s, but that range belongs "
                "to %s. The art loads fine and the WRONG THING draws it -- "
                "nothing fails. Free %s codes: %s"
                % (i + 1, kind,
                   "sprite patterns" if tab == SPRITE_TABLE else "characters",
                   base, base + cnt - 1, label, ", ".join(clash),
                   "sprite" if tab == SPRITE_TABLE else "character",
                   free_runs(own[tab])))
        missing = [p for p in rng if p not in own[tab]]
        if missing and not clash:
            bad.append("line %d: %s writes %s %d..%d from %s, which no table "
                       "claims -- either the source grew or the base is stale"
                       % (i + 1, kind,
                          "sprite patterns" if tab == SPRITE_TABLE else "chars",
                          base, base + cnt - 1, label))

    if quiet:
        return 1 if bad else 0
    print("%d upload site(s) checked" % len(sites))
    print("  free sprite patterns: %s" % free_runs(own[SPRITE_TABLE]))
    print("  free characters:      %s" % free_runs(own[CHAR_TABLE]))
    if bad:
        print()
        for b in bad:
            print("FAIL: " + b)
        return 1
    print("patterns OK -- every upload lands in codes its own table owns, and "
          "every deliberate overwrite is one of the %d declared borrows"
          % len(BORROWS))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else None))
