#!/usr/bin/env python3
"""Generate src/lzss_play.bas: the TI's play tables, LZSS-compressed.

TI ONLY (the ColecoVision and NES builds never include it). This is step 1 of
the TI single-bank work (Keystone DESIGN.md section 53): the tables the game
reads DURING PLAY -- store templates, level and store tables, escalator
phases, Harry's swap poses, the message boxes, the marquee lamps -- taken from
the generated sources exactly as the ROM holds them today, concatenated in
PLAY order, compressed, and checked here by decoding them back.

    lz_play     the compressed stream (padded to an even length)
    #lz_meta    words: table count, total bytes, then per table
                length, s1, s2 (lzss.checksums), which lz_verify checks after
                the 9900 unpacks the stream into RAM
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import lzss  # noqa: E402

SRC = os.path.join(HERE, '..', 'src')

# Read during play on the TI (DESIGN.md section 53 has the classification).
PLAY = ['stor_tpl', 'stor_lvl', 'stor_arc', 'esc_cap', 'stor_co', 'stor_pil',
        'stor_ix', 'stor_esc', 'spr_hstand', 'spr_hstandl', 'spr_hbod4',
        'msg_away', 'msg_gothim', 'msg_over', 'msg_plane', 'msg_timeup',
        'bulb_lit', 'bulb_off'] + ['esc_ph%s%d' % (s, p) for p in range(4) for s in 'we']


# STEP-1 PROBE: bank 2 has room for the decoder test but not yet for the whole
# stream (the tables only LEAVE bank 1 in step 2). This subset covers every
# kind of data in the stream -- long runs (templates), sparse level data,
# message text, escalator pattern art and a sprite -- 3,092 bytes -> ~802.
PROBE = ['stor_tpl', 'stor_lvl', 'msg_away', 'msg_gothim', 'esc_phw0',
         'esc_phe0', 'spr_hstand']


def main():
    global PLAY
    if '--probe' in sys.argv:
        PLAY = PROBE
    tables = {}
    for f in ('store.bas', 'art.bas', 'title.bas'):
        tables.update(lzss.read_tables(os.path.join(SRC, f)))
    missing = [t for t in PLAY if t not in tables or not tables[t]]
    if missing:
        sys.exit('genlzss: tables not found in the generated sources: %s' % missing)
    raw = b''.join(tables[t] for t in PLAY)
    comp = lzss.compress(raw)
    if lzss.decompress(comp, len(raw)) != raw:
        sys.exit('genlzss: the play stream does not round-trip')
    # MUTATION TEST ONLY: KK_LZ_CORRUPT=1 flips one literal byte AFTER the
    # round-trip check, so a build carries a stream the TI must reject. Used to
    # prove the on-machine verification can fail; never set in a real build.
    if os.environ.get('KK_LZ_CORRUPT') == '1':
        comp = bytearray(comp)
        comp[1] ^= 0x55          # byte 0 is a flag; byte 1 is the first literal
        comp = bytes(comp)
        print('genlzss: KK_LZ_CORRUPT=1 -- the stream is DELIBERATELY corrupted')
    meta = [len(PLAY), len(raw)]
    for t in PLAY:
        s1, s2 = lzss.checksums(tables[t])
        meta += [len(tables[t]), s1, s2]
    with open(os.path.join(SRC, 'lzss_play.bas'), 'w', newline='\n') as fh:
        fh.write("\t' GENERATED by assets/genlzss.py -- do not edit.\n")
        fh.write("\t' TI only. %d play tables, %d bytes, compressed to %d.\n"
                 % (len(PLAY), len(raw), len(comp)))
        fh.write("\t' Order: %s\n" % ', '.join(PLAY))
        lzss.emit_bytes(fh, 'lz_play', comp, 'LZSS -- see assets/lzss.py')
        fh.write('#lz_meta:\n')
        for i in range(0, len(meta), 12):
            fh.write('\tDATA %s\n' % ','.join(str(v) for v in meta[i:i + 12]))
    print('genlzss: %d play tables, %d B -> %d B' % (len(PLAY), len(raw), len(comp)))


if __name__ == '__main__':
    main()
