#!/usr/bin/env python3
"""Generate src/titlemusic.bas -- the title screen's tune (TI only).

The tune is not written here. It is STREET from the tunes bench
(sound/tunes, page 3 key 5), rendered by that bench's own generator, so the
game plays exactly what was auditioned there and an edit to the tune in
sound/tunes/assets/gentunes.py reaches the game on its next build.

The label is renamed to `title_tune` so KEYSTONE.bas does not name a bench
tune directly; to change the title music, change PICK.

The data goes in TI bank 2 (see KEYSTONE.bas: title_music_on). The data is
1 tick byte + 4 bytes a row + 1 REPEAT byte, which is EVEN -- asserted
below, because an odd-length block misaligns every word table after it in
the bank (CLAUDE.md 3A).
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', 'sound', 'tunes', 'assets'))
import gentunes  # noqa: E402

PICK = 'tune_street'


def main():
    tune = [t for t in gentunes.TUNES if t['label'] == PICK]
    if len(tune) != 1:
        sys.exit('genmusic: %s not found in sound/tunes/assets/gentunes.py' % PICK)
    t = tune[0]
    if not t.get('loop', True):
        sys.exit('genmusic: %s plays once; the title needs a looping tune' % PICK)
    body = gentunes.render(t)
    size = 1 + 4 * len(body) + 1
    if size % 2:
        sys.exit('genmusic: title tune is %d bytes, odd -- would misalign bank 2' % size)
    lines = [
        "\t' GENERATED by assets/genmusic.py from the tunes bench's %s --" % PICK,
        "\t' edit sound/tunes/assets/gentunes.py, not this.",
        "\t' %d bars, %d rows, %d bytes." % (len(t['bars']), len(body), size),
        'title_tune:',
        '\tDATA BYTE %d' % t['ticks'],
    ]
    lines.extend(body)
    lines.append('\tMUSIC REPEAT')
    lines.append('')
    with open(os.path.join(HERE, '..', 'src', 'titlemusic.bas'), 'w', newline='\n') as f:
        f.write('\n'.join(lines))
    print('genmusic: %s -> src/titlemusic.bas (%d bytes)' % (PICK, size))


if __name__ == '__main__':
    main()
