#!/usr/bin/env python3
"""Generate src/titlemusic.bas -- the game's music (TI only).

The tunes are not written here. They come from the tunes bench
(sound/tunes), rendered by that bench's own generator, so the game plays
exactly what was auditioned there and an edit in
sound/tunes/assets/gentunes.py reaches the game on its next build.

    title_tune  TITLE_PICK, full three voices + drums (PLAY FULL)
    game_tune   GAME_PICK, cut to TWO voices, melody and bass, no drums, for
                PLAY SIMPLE NO DRUMS during play. That mode owns channels 0
                and 1 only, which leaves channel 2 (prizes, lives, tally) and
                noise (footsteps) to the effects; jumps (ch 0) and hits
                (ch 1) duck the music instead -- see music_duck.

The labels are fixed so KEYSTONE.bas never names a bench tune; to change a
tune, change its PICK.

Each block is 1 tick byte + 4 bytes a row + 1 REPEAT byte, which is EVEN --
asserted below, because an odd-length block misaligns every word table after
it in the bank (CLAUDE.md 3A).
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', 'sound', 'tunes', 'assets'))
import gentunes  # noqa: E402

TITLE_PICK = 'tune_street'
GAME_PICK = 'tune_chase'


def pick(label):
    tune = [t for t in gentunes.TUNES if t['label'] == label]
    if len(tune) != 1:
        sys.exit('genmusic: %s not found in sound/tunes/assets/gentunes.py' % label)
    if not tune[0].get('loop', True):
        sys.exit('genmusic: %s plays once; a screen needs a looping tune' % label)
    return tune[0]


def two_voice(rows):
    """MUSIC mel,comp,bass,drum -> MUSIC mel,bass.

    PLAY SIMPLE plays the first two voices, so the bass has to move up to
    second place and the comping goes. The bass keeps its Z (it is on its
    first note) and the melody its W.
    """
    out = []
    for r in rows:
        head, args = r.split('MUSIC ', 1)
        a = args.split(',')
        if len(a) != 4:
            sys.exit('genmusic: unexpected MUSIC row %r' % r)
        out.append('%sMUSIC %s,%s' % (head, a[0], a[2]))
    return out


def block(label, source, t, rows, note):
    size = 1 + 4 * len(rows) + 1
    if size % 2:
        sys.exit('genmusic: %s is %d bytes, odd -- would misalign bank 2' % (label, size))
    lines = [
        "\t' %s: the tunes bench's %s, %s. %d bars, %d rows, %d bytes."
        % (label, source, note, len(t['bars']), len(rows), size),
        '%s:' % label,
        '\tDATA BYTE %d' % t['ticks'],
    ]
    lines.extend(rows)
    lines.append('\tMUSIC REPEAT')
    lines.append('')
    return lines, size


def main():
    title = pick(TITLE_PICK)
    game = pick(GAME_PICK)
    out = ["\t' GENERATED by assets/genmusic.py -- edit sound/tunes/assets/gentunes.py,",
           "\t' not this.", '']
    tl, ts = block('title_tune', TITLE_PICK, title, gentunes.render(title),
                   'three voices and drums')
    gl, gs = block('game_tune', GAME_PICK, game, two_voice(gentunes.render(game)),
                   'melody and bass only')
    out += tl + gl
    with open(os.path.join(HERE, '..', 'src', 'titlemusic.bas'), 'w', newline='\n') as f:
        f.write('\n'.join(out))
    print('genmusic: %s -> title_tune (%d B), %s -> game_tune (%d B)'
          % (TITLE_PICK, ts, GAME_PICK, gs))


if __name__ == '__main__':
    main()
