#!/usr/bin/env python3
"""NES background colours and per-screen attributes, derived from the live art.

Grey is shared colour zero. P0: green/black/gold; P1: blue/pink/gold;
P2: orange/black/gold; P3: green/blue/gold. Buildings and pillars therefore
stay grey in every palette. Fixtures with black outlines switch back to P0.
"""
from pathlib import Path
import genart as art
import genstore as store

SKY_ROWS = {'SKY0': 0, 'BLDGM0': 0, 'BLDGW0': 0,
            'SKY1': 1, 'BLDGM1': 1,
            'SKY2': 2, 'BLDGL': 2, 'BLDGH': 2}


def colours():
    out = []
    for name, code, pattern, fg, bg in art.CHARS:
        rows = art.colour_block(name, fg, bg)
        if name in SKY_ROWS:
            skyrow = SKY_ROWS[name]
            for y, value in enumerate(rows):
                if value & 15 != art.GRAY:
                    # These source colours encode indices 1, 2 and 3 under
                    # nes_inkmap; their actual hues come from P1/P2.
                    paper = art.MGREEN if skyrow == 0 else art.BLACK
                    if skyrow == 2:
                        paper = art.MGREEN if y < 4 else art.LYELL
                    rows[y] = (value & 240) | paper
        if name == 'SHELFT':
            rows = [0xB1] * 3 + [0x11] * 5  # gold lip, blue body in P3
        elif name == 'SHELFB':
            rows = [0x11] * 8
        out.extend(rows)
    return out


def attributes(screen):
    # One palette number per 16x16 quadrant, then pack four into each byte.
    quads = [[0] * 16 for _ in range(16)]
    for y in range(3):  # HUD plus first two skyline tile rows (PPU rows 4,5)
        quads[y] = [1] * 16
    quads[3] = [2] * 16  # skyline rows 6,7; orange then gold, grey buildings
    templates = dict(store.TEMPLATES)
    for level, start in enumerate((19, 14, 9)):
        tilemap = templates[store.INDEX[level][screen]]
        for y, row in enumerate(tilemap):
            for x, tile in enumerate(row):
                if tile in (store.SHELFT, store.SHELFB):
                    quads[(start + y) // 2][x // 2] = 3
    return [quads[y][x] | quads[y][x+1] << 2 |
            quads[y+1][x] << 4 | quads[y+1][x+1] << 6
            for y in range(0, 16, 2) for x in range(0, 16, 2)]


def main():
    path = Path(__file__).resolve().parent.parent / 'src' / 'nescolor.bas'
    with path.open('w', encoding='utf-8', newline='') as f:
        f.write("\t' GENERATED by assets/gennescolor.py; NES only.\n")
        hat = next(pattern for name, code, pattern, fg, bg in art.CHARS if name == 'KOPIC')
        art.emit(f, 'hud_hat_pat', art.char_bytes(hat) + [0]*8,
                 'NES reserve icon: CHR 198/199, used by OAM 56..60')
        art.emit(f, 'nes_store_col', colours(), 'per-row colours for store_pat')
        art.emit(f, 'nes_attrs', [v for s in range(8) for v in attributes(s)],
                 'eight screens, 64 attribute bytes each; fixtures mask to P0')


if __name__ == '__main__':
    main()
