#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""The title's display face -- one 16x16 letter per 2x2 block of characters.

WHY A SECOND FACE AT ALL
------------------------
The game's font is 8x8 and the title card wants the name to READ as a name, the
way the Activision original does: stacked, and much larger than everything round
it. Spacing the ordinary font out (`K E Y S T O N E`) was the cheap approximation
and it is still a small line of body text with gaps in it.

Each letter here is 16x16 -- four characters, laid out as

    TL TR        two cells across, two cells down; the display list places the
    BL BR        top row of every letter, then the bottom row

so a word is two runs in the same table format as everything else, and the
walker that draws the rest of the title draws this too. No new mechanism again.

WHERE IT LIVES. Forty characters is 320 bytes of pattern and 320 of colour, and
bank 1 had 370 free -- it does not fit. It does not need to: these are read ONCE,
by `DEFINE CHAR`/`DEFINE COLOR` at setup, exactly like the font, so they belong
in **bank 2** with it and are loaded inside the same one-and-only bank switch the
program makes. Bank 2 had 7,204 bytes spare.

THE GLYPHS are drawn on a 13-row cap height inside 16 rows, with the stems three
pixels wide, so they hold up against the marquee's lamps. Columns 13-15 are the
letter's own right-hand sidebearing -- the gap between letters is part of the
glyph rather than a separate spacing cell, which is what lets a word be one
contiguous run.
"""

# Only the letters KEYSTONE KAPERS needs. Adding a word to the title means
# adding its letters here; `gentitle.py` fails loudly on a letter it has no
# glyph for rather than drawing a hole.
GLYPHS = {}

GLYPHS["K"] = """
................
.###.....###....
..##....##......
..##...##.......
..##..##........
..##.##.........
..#####.........
..#####.........
..##.##.........
..##..##........
..##...##.......
..##....##......
..##.....##.....
.###......###...
................
................
"""

GLYPHS["E"] = """
................
.##########.....
.##########.....
..##............
..##............
..##............
..########......
..########......
..##............
..##............
..##............
.##########.....
.##########.....
................
................
................
"""

GLYPHS["Y"] = """
................
.###.....###....
..##.....##.....
..##....##......
...##..##.......
...##.##........
....###.........
....###.........
.....##.........
.....##.........
.....##.........
....####........
....####........
................
................
................
"""

# THE S IS THE ONE THAT HAD TO BE DRAWN TWICE. Its first version wandered --
# the lower bowl started at column 12 while the upper one ended at column 8 --
# and it rendered as a stray mark rather than a letter. An S is two bowls that
# have to MEET in the middle; drawing it row by row without holding the spine in
# mind gives a shape that is symmetrical nowhere and reads as damage.
GLYPHS["S"] = """
................
...#######......
..#########.....
..###....##.....
..##............
..###...........
...######.......
.....######.....
.........###....
..##.....###....
..###...###.....
..#########.....
...#######......
................
................
................
"""

GLYPHS["T"] = """
................
.###########....
.###########....
.....##.........
.....##.........
.....##.........
.....##.........
.....##.........
.....##.........
.....##.........
.....##.........
....####........
....####........
................
................
................
"""

GLYPHS["O"] = """
................
....######......
...########.....
..###....###....
..##......##....
..##......##....
..##......##....
..##......##....
..##......##....
..###....###....
...########.....
....######......
................
................
................
................
"""

GLYPHS["N"] = """
................
.###.....###....
.####....###....
.#####...###....
.##.##...###....
.##..##..###....
.##...##.###....
.##....#####....
.##.....####....
.##......###....
.##......###....
.###.....###....
................
................
................
................
"""

GLYPHS["A"] = """
................
.....####.......
....######......
....##..##......
...##....##.....
...##....##.....
..##########....
..##########....
..##......##....
.##........##...
.##........##...
.###......###...
................
................
................
................
"""

GLYPHS["P"] = """
................
.#########......
.##########.....
.##......##.....
.##......##.....
.##......##.....
.##########.....
.#########......
.##.............
.##.............
.##.............
.####...........
.####...........
................
................
................
"""

GLYPHS["R"] = """
................
.#########......
.##########.....
.##......##.....
.##......##.....
.##########.....
.#########......
.##...##........
.##....##.......
.##.....##......
.##......##.....
.###......###...
................
................
................
................
"""

CELL = 8            # characters are 8x8
WIDE = 2            # a letter is 2 cells across
TALL = 2            # and 2 down

# WHERE THE FACE LIVES, AND WHY IT IS IN TWO PIECES.
#
# The character table is 256 codes and this game has very little of it left:
#
#     32..90    the font
#     96..181   the store art
#     208..255  the radar canvas
#
# leaving 0..31, 91..95 and 182..207 -- sixty-three codes, but the longest run
# is thirty-two and forty are needed.
#
# THE FIRST ATTEMPT PUT THE FACE AT 182..221 AND RAN INTO THE RADAR. Codes
# 208..217 are the radar's own characters, so `S` and `T` came out as the
# scanner's green escalator diagonals -- on the TITLE SCREEN, where no radar is
# drawn, because the collision is in the PATTERN table and has nothing to do
# with what is on screen. The offline previewer could not show it either: it
# paints from the generated blocks and had the face exactly where the generator
# said, so it agreed with the bug. Only the emulator disagreed.
#
# So the face is allocated across the two usable runs, largest first. Two
# `DEFINE CHAR`/`DEFINE COLOR` pairs load it; `gentitle.py` prints the exact
# arguments and `checkchars.py` verifies them against this table.
FREE_RUNS = [(182, 26), (0, 14)]


def codes():
    """Every code the face occupies, in pattern order."""
    out = []
    for start, count in FREE_RUNS:
        out += list(range(start, start + count))
    need = 4 * len(GLYPHS)
    if len(out) < need:
        raise SystemExit(
            "titleface: the display face needs %d character codes and the "
            "table has %d free. Drop a letter, or make the glyphs 1 cell wide."
            % (need, len(out)))
    return out[:need]


def blocks():
    """[(code, count)] -- the DEFINE CHAR runs, in pattern order."""
    need = 4 * len(GLYPHS)
    out, taken = [], 0
    for start, count in FREE_RUNS:
        if taken >= need:
            break
        n = min(count, need - taken)
        out.append((start, n))
        taken += n
    return out


def rows_of(letter):
    """A glyph as exactly 16 rows of 16 columns."""
    art = GLYPHS[letter]
    rows = [r for r in art.split("\n") if r != ""]
    if len(rows) != CELL * TALL:
        raise SystemExit("titleface: %r has %d rows, expected %d"
                         % (letter, len(rows), CELL * TALL))
    out = []
    for r in rows:
        if len(r) > CELL * WIDE:
            raise SystemExit("titleface: %r has a %d-column row, max %d"
                             % (letter, len(r), CELL * WIDE))
        out.append((r + "." * (CELL * WIDE))[:CELL * WIDE])
    return out


def quads(letter):
    """The four 8x8 cells of a letter, in name-table order: TL TR BL BR."""
    rows = rows_of(letter)
    out = []
    for cy in range(TALL):
        for cx in range(WIDE):
            cell = []
            for y in range(CELL):
                r = rows[cy * CELL + y]
                cell.append(r[cx * CELL:(cx + 1) * CELL])
            out.append(cell)
    return out


def char_bytes(cell):
    """8 bytes from an 8x8 cell."""
    return [sum(1 << (7 - x) for x in range(CELL) if row[x] == "#")
            for row in cell]


def letters():
    """The alphabet, in a fixed order -- the order IS the code assignment."""
    return sorted(GLYPHS)


def patterns():
    """All pattern bytes, four characters per letter, in `letters()` order."""
    data = []
    for ch in letters():
        for cell in quads(ch):
            data += char_bytes(cell)
    return data


def code_of(letter, quad):
    """Character code for one quadrant of one letter.

    `quad` is 0=TL 1=TR 2=BL 3=BR. Taken from the allocation, never written
    down twice -- a hand-typed character number is a bug waiting for a
    renumber, and this one already collided with the radar once.
    """
    if letter not in GLYPHS:
        raise SystemExit(
            "titleface: no display glyph for %r. Add it to GLYPHS -- the title "
            "cannot draw a letter it has no art for." % letter)
    return codes()[4 * letters().index(letter) + quad]
