#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""The title's name, drawn as WHOLE WORDS and sliced into characters.

WHY WORDS AND NOT LETTERS
-------------------------
The first display face gave every letter its own 2x2 block of characters, which
means every letter starts on an 8-pixel boundary. That is not typesetting, it is
a grid: the spacing cannot vary, nothing can tuck under anything else, and the
result reads as separate stamps rather than as a piece of lettering.

The reference is KERNED -- the letters are fitted to each other and drawn as one
image. So this composites the letters into a WORD bitmap at whatever advance
each pair wants, and only then slices the result on the character grid. A cell
may hold parts of two letters; that is the point.

THE BUDGET DECIDES THE WIDTH, and it is worth showing the arithmetic because it
is the whole design constraint:

    font 32..90, store art 96..181, radar canvas 208..255
      -> free: 0..31, 91..95, 182..207 = 63 codes

Three cells tall is what the name needs to look like a sign. At a 12-pixel
advance KEYSTONE is 12 cells wide and KAPERS 9, so 21 x 3 = 63 -- exactly the
budget, before any saving from blank or repeated cells. At 13 it is 69 and does
not fit at any price short of moving the store art into another bank.

So: 12-pixel advance, letters drawn up to 12 wide, tightly fitted. Condensed is
not a compromise here -- the reference's own face is tall and narrow.

DEDUPING IS NOT AN OPTIMISATION, IT IS HEADROOM. Blank cells become the space
character and identical cells share a code, which is what buys back the margin
the 63 leaves none of.
"""

WIDTH = 12          # advance per letter -- see the arithmetic above
ROWS = 24           # three characters tall
CAP_TOP, CAP_BOT = 2, 21


GLYPHS = {}

GLYPHS["K"] = """
............
............
.####...####
.####...####
..##.....##.
..##....##..
..##...##...
..##..##....
..##.##.....
..#####.....
..####......
..#####.....
..##.##.....
..##..##....
..##...##...
..##....##..
..##.....##.
..##.....##.
..##......##
..##......##
.####...####
.####...####
............
............
"""

GLYPHS["E"] = """
............
............
.##########.
.##########.
..##........
..##........
..##........
..##........
..##........
..#######...
..#######...
..#######...
..##........
..##........
..##........
..##........
..##........
..##........
..##........
..##........
.##########.
.##########.
............
............
"""

GLYPHS["Y"] = """
............
............
.####...####
.####...####
..##.....##.
...##...##..
...##...##..
....##.##...
....##.##...
.....###....
.....###....
......##....
......##....
......##....
......##....
......##....
......##....
......##....
......##....
......##....
....######..
....######..
............
............
"""

GLYPHS["S"] = """
............
............
...######...
..########..
.###....###.
.##......##.
.##.........
.###........
..####......
...####.....
....####....
.....####...
......####..
.......####.
........###.
.........##.
.........##.
.##......##.
.##......##.
.###....###.
..########..
...######...
............
............
"""

GLYPHS["T"] = """
............
............
.##########.
.##########.
.....##.....
.....##.....
.....##.....
.....##.....
.....##.....
.....##.....
.....##.....
.....##.....
.....##.....
.....##.....
.....##.....
.....##.....
.....##.....
.....##.....
.....##.....
.....##.....
...######...
...######...
............
............
"""

GLYPHS["O"] = """
............
............
...######...
..########..
.###....###.
.##......##.
.##......##.
.##......##.
.##......##.
.##......##.
.##......##.
.##......##.
.##......##.
.##......##.
.##......##.
.##......##.
.##......##.
.##......##.
.##......##.
.###....###.
..########..
...######...
............
............
"""

GLYPHS["N"] = """
............
............
.####...####
.####....##.
..###....##.
..###....##.
..####...##.
..##.##..##.
..##.##..##.
..##..##.##.
..##..##.##.
..##..##.##.
..##...####.
..##...####.
..##....###.
..##....###.
..##.....##.
..##.....##.
..##.....##.
..##.....##.
.####...####
.####...####
............
............
"""

GLYPHS["A"] = """
............
............
.....##.....
....####....
....####....
....####....
...##..##...
...##..##...
...##..##...
..##....##..
..##....##..
..########..
..########..
..##....##..
.##......##.
.##......##.
.##......##.
.##......##.
.##......##.
.##......##.
####....####
####....####
............
............
"""

GLYPHS["P"] = """
............
............
.#########..
.##########.
..##.....##.
..##.....##.
..##.....##.
..##.....##.
..##.....##.
..##....##..
..########..
..#######...
..##........
..##........
..##........
..##........
..##........
..##........
..##........
..##........
.####.......
.####.......
............
............
"""

GLYPHS["R"] = """
............
............
.#########..
.##########.
..##.....##.
..##.....##.
..##.....##.
..##.....##.
..##....##..
..########..
..#######...
..##.##.....
..##..##....
..##..##....
..##...##...
..##...##...
..##....##..
..##....##..
..##.....##.
..##.....##.
.####...####
.####...####
............
............
"""

CELL = 8


def rows_of(letter):
    """A glyph as exactly ROWS rows of WIDTH columns."""
    if letter not in GLYPHS:
        raise SystemExit(
            "titleword: no glyph for %r -- the title cannot draw a letter it "
            "has no art for. Add it to GLYPHS." % letter)
    rows = [r for r in GLYPHS[letter].split("\n") if r != ""]
    if len(rows) != ROWS:
        raise SystemExit("titleword: %r has %d rows, expected %d"
                         % (letter, len(rows), ROWS))
    out = []
    for r in rows:
        if len(r) > WIDTH:
            raise SystemExit("titleword: %r has a %d-column row, max %d"
                             % (letter, len(r), WIDTH))
        out.append((r + "." * WIDTH)[:WIDTH])
    return out


def check_heights():
    """One cap height for the whole face.

    The previous face ran from eleven rows to thirteen with tops and bottoms on
    different lines, which reads as letters sitting at different depths. A
    display face has ONE cap height; this asserts it rather than trusting ten
    hand-drawn grids to agree.
    """
    bad = []
    for letter in sorted(GLYPHS):
        rows = rows_of(letter)
        on = [i for i, r in enumerate(rows) if "#" in r]
        if not on:
            bad.append("%s is blank" % letter)
        elif (on[0], on[-1]) != (CAP_TOP, CAP_BOT):
            bad.append("%s occupies rows %d..%d, not %d..%d"
                       % (letter, on[0], on[-1], CAP_TOP, CAP_BOT))
    if bad:
        raise SystemExit("titleword: not one cap height:\n  "
                         + "\n  ".join(bad))


def bitmap(word):
    """The word as one image -- [row strings], letters composited at WIDTH."""
    px = [["."] * (WIDTH * len(word)) for _ in range(ROWS)]
    for i, ch in enumerate(word):
        if ch == " ":
            continue
        g = rows_of(ch)
        for y in range(ROWS):
            for x in range(WIDTH):
                if g[y][x] == "#":
                    px[y][i * WIDTH + x] = "#"
    return ["".join(r) for r in px]


def cells(word):
    """[[cell]] -- the word sliced on the character grid, row-major.

    A cell is 8 rows of 8 columns. The word is padded to whole cells; the
    padding is blank and becomes the space character.
    """
    img = bitmap(word)
    w = len(img[0])
    cw = (w + CELL - 1) // CELL
    img = [(r + "." * (cw * CELL))[:cw * CELL] for r in img]
    out = []
    for cy in range(ROWS // CELL):
        row = []
        for cx in range(cw):
            row.append([img[cy * CELL + y][cx * CELL:(cx + 1) * CELL]
                        for y in range(CELL)])
        out.append(row)
    return out


def char_bytes(cell):
    return [sum(1 << (7 - x) for x in range(CELL) if row[x] == "#")
            for row in cell]
